### ISSUE TITLE
Draft a new release?

### ISSUE THREAD

**Issue by enoch85** [owncloud/contacts#1016]
Would be nice if someone could draft a new release so that the annoying https://github.com/owncloud/contacts/pull/973 bug is fixed.

Please also push it to the app store.

@DeepDiver1975 maybe?

**Comment by DeepDiver1975** [comment]
> Would be nice if someone could draft a new release so that the annoying #973 bug is fixed.
> 
> Please also push it to the app store.

That's the pity of have no maintainer for this app ...

**Comment by enoch85** [comment]
@DeepDiver1975 I can draft the release if it's just straightforward? I patched the fix for myself already, but I'm thinking of everyone else.

**Comment by RealRancor** [comment]
@enoch85 Some steps how to draft a new release where provided here:

https://github.com/owncloud/core/issues/18116#issuecomment-129445478

Currently i'm also running the patched version of the contacts app with the fixes from https://github.com/owncloud/contacts/pull/973 and https://github.com/owncloud/contacts/pull/971 without any problems. So i think a new release of stable8.1 shouldn't be a problem.

**Comment by enoch85** [comment]
@RealRancor As I´m a bit uncertain on how to draft a new release, you think you can do it? :wink:

**Comment by RealRancor** [comment]
@enoch85 Sorry, don't have "Collaborator" permissions.

**Comment by enoch85** [comment]
@RealRancor Aah, too bad. You contribute so much, you should really concider it. :smile:

**Comment by enoch85** [comment]
@DeepDiver1975 I think I did it correct. Can you check please? https://github.com/owncloud/contacts/releases/tag/untagged-cdf156a55df0536de8a6

**Comment by RealRancor** [comment]
@enoch85 Can't you use the steps provided here: https://github.com/owncloud/core/issues/18116#issuecomment-129445478 ?

**Comment by enoch85** [comment]
@RealRancor Sure, I´m just afraid of doing something wrong. And there is no 8.1.1, so would v0.4.0.1 be OK as a tag?

**Comment by enoch85** [comment]
Anyway, I followed the steps, except that I uploaded a tar.gz like @DeepDiver1975 did in previous pre-releases. I published it, if it's wrong - please change.

**Comment by RealRancor** [comment]
@enoch85 The current tag is from master but i think you should only tag the latest head of stable8.1

**Comment by RealRancor** [comment]
@LukasReschke Can you help here in drafting a new release of the current stable8.1 ? The two commits since the last release of 0.40.0 are working here just fine without any problems.

**Comment by enoch85** [comment]
Delete my release as it contained errors. cc @LukasReschke

**Comment by matzex** [comment]
Any updates on this?
This should also fix [calendar/#902](https://github.com/owncloud/calendar/issues/902).

**Comment by enoch85** [comment]
@matzex As I failed with the draft and don´t know how to do, it would be nice if someone else could give it a try.

**Comment by RealRancor** [comment]
The main problem here is that it needs someone having permissions to update the link on apps.owncloud.com to point to the new release.

**Comment by timorei** [comment]
I was hoping that this had progressed. For now my respective clients take care of displaying the contacts birthdays, but the webinterface is lacking this information, badly. Has the contacts dev gone into hiding?

**Comment by RealRancor** [comment]
@timorei There is already an existing (one line) fix available since 3 months here: https://github.com/owncloud/contacts/pull/970/files

**Comment by timorei** [comment]
I'll take a look if adding this fix works. I was hoping on keeping my server's applications on "official releases", to be honest. But if this is the only way to get it working as it should, I'll just have to.

**Comment by dper** [comment]
@timorei You might end up waiting for a long time. There's no official maintainer, and without one it's hard to get a new release posted. Sadly. In the meantime, this fix is a decent way to go.

**Comment by RealRancor** [comment]
@enoch85 A new version of the app was released so this as well as https://github.com/owncloud/contacts/issues/976 probably can be closed.
