### ISSUE TITLE
question: is there version control for contacts?

### ISSUE THREAD

**Issue by megies** [owncloud/contacts#1020]
I could not find information on whether contacts/address books are kept under version control (like normal files in owncloud). To me it seems as if there is no backup of older versions of the address book, or am I missing something?

I am just a bit concerned about address books getting emptied by accident (e.g. by accidental user action or app bug) and then during a sync losing some or all contacts..

So, is there a possibility to roll back to an older version of an address book?

**Comment by RealRancor** [comment]
Hi,

there is no version conyrol for calendars/contacts. Those are also no files but data in your database.

As oC and especially the version control is no backup you should do backups anyway.
