### ISSUE TITLE
Whoops - Version 0.4.0.1 still has version 0.4.0.0 set

### ISSUE THREAD

**Issue by javaboyuk** [owncloud/contacts#1021]
Guys
 I have updated to version 0.4.0.1 (as tagged I think? will as the file in the releases area) manually.

 Have noticed the appinfo was not changed to version 0.4.0.1 so still shows as 0.4.0.0. This is clear in the appinfo file has not been updated to 0.4.0.1 before it was tagged, its still the old version number.

 So I expect thats why it did not show up as an auto update for me.

 Looks great that we have had some work carried out on fixing a number of issues thank you!

(I dont have access but would suggest just "edit" the version file, re-tag and release maybe to 0.4.0.2 so save any confusion?)

JB

**Comment by RealRancor** [comment]
Hi,

i don't think that the master (which is now tagged as 0.40.1) should be currently used as also proposed here: https://github.com/owncloud/contacts/issues/1016#issuecomment-131762039

**Comment by RealRancor** [comment]
@enoch85 Could you remove the 0.4.0.1 release again as the current master is really nothing which should be released in my opinion.

**Comment by enoch85** [comment]
@RealRancor Done.
