### ISSUE TITLE
Changing name N | FN

### ISSUE THREAD

**Issue by prilly** [owncloud/contacts#1024]
When changing names of a contact in owncloud (webpage and contact app)
only the FN "Friendly name" is updated, the N "name" atribute is not changed,

From SQL table: oc_contacts_cards_properties

 	FN 	Dell Pro support 	0
	N 	;Dell-Pro-support;;; 	0

Only the FN has been changed and not the N.

**Comment by gvde** [comment]
Dup of #999?

**Comment by prilly** [comment]
Seems that pull fixed the issue. This ticket can be closed.
