### ISSUE TITLE
Make Organization and Title a group

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#103]
Similar to the address fields, the fields for »Organization« and »Title« belong together and should be made a group. Title should always appear below the Organization field. That’s also how Android and others do it.

Visually, we could then also add some whitespace above and below that group similarly to how we do with the address.

**Comment by tomneedham** [comment]
@DeepDiver1975, been trying to crack this one. Tried adding a template for 'organisation' type which included the title field but they then share the same ng-model. 

Second attempt I tried adding a check when 'org' is selected and also adding the 'title' field. Now need to filter out title from the add field selector.

Also... what is `role` when there is `title` as well? Is title meaning 'Mr' or 'Mrs' etc?

**Comment by DeepDiver1975** [comment]
> Also... what is role when there is title as well? Is title meaning 'Mr' or 'Mrs' etc?

https://tools.ietf.org/html/rfc6350#section-6.6.1

**Comment by DeepDiver1975** [comment]
@tomneedham I have no clue on how to handle this - TBH

**Comment by jancborchardt** [comment]
@DeepDiver1975 seeing as there is even more confusion about the »Role« field I now would vote »yes« for that we do not show it at all. ;) As long as it’s preserved in the backend that’s fine.
