### ISSUE TITLE
Backslashes in N field

### ISSUE THREAD

**Issue by pacija** [owncloud/contacts#1051]
Hi,
I'm using owncloud 8.1.3 and contacts 0.4.0.0.

When creating a contact in web interface, I'm entering two strings (eg. Name Surname) in non-expanded Name field, and then continue to enter other details such as email, phone etc.

This results in vcf which has backslashes in N field:
```
N:Surname\;Name\;\;\;;;;;
```
This looks rather ugly on android smartphone when synchronized with DAVdroid (my main purpose of having contacts in owncloud).

If creating contacts with expanded Name field there are no backslashes. Also, backslashes are corrected if existing contact's Name field is expanded, and at least one of Name or Surname changed.

Thank you in advance, hope this gets fixed. And if so, I have at least 3 more bugs to report :)

**Comment by gvde** [comment]
Please, please, please, always first search for existing issues before creating a new one.

This is a duplicate of #986, #1028, #1034, #1036 and has been fixed with #999 and #1032.

**Comment by pacija** [comment]
Sorry, I'm new to both github and owncloud contacts :) And thank you for useful information. I patched and the issue is solved.
