### ISSUE TITLE
Cannot upgrade from 0.4.0.0 to 0.4.0.1

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/contacts#1069]
When I click on "upgrade to new version" in the admin panel, after a few seconds this error pops out in a red box below the buttons:

    Unable to generate a URL for the named route "contacts_index" as such route does not exist.

The app is disabled and hasn't been enabled since the last upgrade of ownCloud version. I am currently on ownCloud 8.1.3 (stable).

**Comment by RealRancor** [comment]
Hi,

thats a long running issue in core (see https://github.com/owncloud/core/issues/19145) so you can close here and watch the linked issue.

**Comment by Pastafarianist** [comment]
Thanks for the link, closing this one.
