### ISSUE TITLE
App store version and requirements mismatch

### ISSUE THREAD

**Issue by PVince81** [owncloud/contacts#1073]
The git version says:
- version: 0.4.0.0
- max OC version is 8.2

The app store says:
- version: 0.4.0.1
- max OC version is 8.1

This causes the following weird bug:
1) Since the requirements are not met, the contacts app is not visible in the apps page in OC 8.2, which is obvious
2) If you install the git version, then suddenly the apps page will suggest to "Update to 0.4.0.1" even though the requirements wouldn't be suitable.

Anyway, I think the way to go for now is:
- adjust git version to 0.4.0.2
- reupload the git version to the app store as 0.4.0.2
- adjust app store requirements to allow 8.2

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
the version on the appstore for 8.1 is 0.4.0.1 - https://github.com/owncloud/contacts/pull/1060
the versopm for 8.2 is to be 0.5.0.0 - https://github.com/owncloud/contacts/pull/1061

**Comment by DeepDiver1975** [comment]
@PVince81 apps have been uploaded for 8.1 and 8.2 - I performed an upgrade test - all green from my pov - THX

**Comment by PVince81** [comment]
I deleted the local git contacts app then installed the one from the app store => works

**Comment by PVince81** [comment]
@DeepDiver1975 backport to the stable8.2 branch ?
@schiesbn just pointed out that the stable8.2 branch still has the old version file

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 backport to the stable8.2 branch ?
> @schiesbn just pointed out that the stable8.2 branch still has the old version file

ah - tagging is missing in stable8.2 - will take care
