### ISSUE TITLE
shared contacts not sending e-tag

### ISSUE THREAD

**Issue by 0-kaladin** [owncloud/contacts#1081]
on owncloud 8.13, dav client no longer able to sync as not getting any e-tag response back from shared contact sync.
Verbose log from the client is here that shows server response:
http://pastebin.com/rPPpBhSp

**Comment by gvde** [comment]
Please use the template from the contribution guidelines.

Make sure you run the latest version of the contacts app.

**Comment by 0-kaladin** [comment]
Updating contacts app to latest fixed it.  thanks.
