### ISSUE TITLE
cannot share LDAP address book

### ISSUE THREAD

**Issue by atroxix** [owncloud/contacts#1089]
When trying to share LDAP address book to a user or a group I get the following error:

```
Error while sharing
Sharing ldap addressbook failed, because the sharing backend for addressbook could not find its source
```

**Comment by babelouest** [comment]
That a known problem unfortunately: #660 
I'm still not able to fix it (shared addressbooks part of contact is still a mystery)
I'm closing this ussue though, feel free to participate on the original one
