### ISSUE TITLE
Autoload problems when enabling plugin with OwnCloud 8.2

### ISSUE THREAD

**Issue by 2easy** [owncloud/contacts#1102]
I am trying to install your app on ubuntu 14.04 with owncloud ver. 8.2.

After enabling the plugin - OwnCloud stops working with 500 error:

{"reqId":"5pU7P\/UxAmWTIV5GADgp","remoteAddr":"172.17.42.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/html\\\/o...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\user_ldap\\\\U...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\user_ldap\\\\U...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(178): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(613): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1061): OC::init()\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":138}","level":3,"time":"2015-11-16T19:38:32+00:00"}

OR MORE USEFUL after another try to enable by OCC:

An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /var/www/html/owncloud/apps/user_ldap/user_ldap.php' in /var/www/html/owncloud/lib/autoloader.php:138
Stack trace:
#0 /var/www/html/owncloud/lib/autoloader.php(158): OC\Autoloader->isValidPath('/var/www/html/o...')
#1 [internal function]: OC\Autoloader->load('OCA\user_ldap\U...')
#2 /var/www/html/owncloud/apps/user_cas/lib/ldap_backend_adapter.php(35): spl_autoload_call('OCA\user_ldap\U...')
#3 /var/www/html/owncloud/apps/user_cas/user_cas.php(25): require_once('/var/www/html/o...')
#4 /var/www/html/owncloud/apps/user_cas/appinfo/app.php(30): require_once('/var/www/html/o...')
#5 /var/www/html/owncloud/lib/private/app.php(160): require_once('/var/www/html/o...')
#6 /var/www/html/owncloud/lib/private/app.php(141): OC_App::requireAppFile('user_cas')
#7 /var/www/html/owncloud/lib/private/app.php(118): OC_App::loadApp('user_cas')
#8 /var/www/html/owncloud/lib/private/user.php(178): OC_App::loadApps(Array)
#9 /var/www/html/owncloud/lib/base.php(613): OC_User::setupBackends()
#10 /var/www/html/owncloud/lib/base.php(1061): OC::init()
#11 /var/www/html/owncloud/console.php(42): require_once('/var/www/html/o...')
#12 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#13 {main}An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /var/www/html/owncloud/apps/user_ldap/user_ldap.php' in /var/www/html/owncloud/lib/autoloader.php:138
Stack trace:
#0 /var/www/html/owncloud/lib/autoloader.php(158): OC\Autoloader->isValidPath('/var/www/html/o...')
#1 [internal function]: OC\Autoloader->load('OCA\user_ldap\U...')
#2 /var/www/html/owncloud/apps/user_cas/lib/ldap_backend_adapter.php(35): spl_autoload_call('OCA\user_ldap\U...')
#3 /var/www/html/owncloud/apps/user_cas/user_cas.php(25): require_once('/var/www/html/o...')
#4 /var/www/html/owncloud/apps/user_cas/appinfo/app.php(30): require_once('/var/www/html/o...')
#5 /var/www/html/owncloud/lib/private/app.php(160): require_once('/var/www/html/o...')
#6 /var/www/html/owncloud/lib/private/app.php(141): OC_App::requireAppFile('user_cas')
#7 /var/www/html/owncloud/lib/private/app.php(118): OC_App::loadApp('user_cas')
#8 /var/www/html/owncloud/lib/private/user.php(178): OC_App::loadApps(Array)
#9 /var/www/html/owncloud/lib/base.php(613): OC_User::setupBackends()
#10 /var/www/html/owncloud/lib/base.php(1061): OC::init()
#11 /var/www/html/owncloud/console.php(42): require_once('/var/www/html/o...')
#12 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')

**Comment by RealRancor** [comment]
@2easy Sure this is caused by the contacts app and not by the user_cas or user_ldap app? Please also fill out the issue template as asked in the guidelines for contributing:

https://github.com/owncloud/contacts/blob/master/CONTRIBUTING.md#short-version

linked in the yellow box when creating a new issue.

**Comment by 2easy** [comment]
I am terribly sory - this issue should go to other repository. I really have no idea why it posted here.
