### ISSUE TITLE
Thunderbird CardBook sync failure OC 8.2.1 Contacts 0.5.0.0

### ISSUE THREAD

**Issue by fonzmike** [owncloud/contacts#1105]
### Steps to reproduce
Sync worked with OC 8.1 and matching Contacts app (version unknown)
1. Update to OC 8.2.1
2. Update to Contacts 0.5.0.0
3. Create a card book in Thunderbird Cardbook plugin using the provided URL by Contacts App
4. Sync the card book

### Expected behaviour
All contacts should be synced

### Actual behaviour
1. List of contacts is fetched
2. Import of every single contact failes with error http 404

### Server configuration
**Operating system
Distributor ID:	Ubuntu
Release:	14.04
Codename:	trusty

**Web server:**
Apache 2

**Database:**
Mysql

**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.2.1

**Updated from an older ownCloud or fresh install:**
Update from 8.1

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_locking: 
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - user_external
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.xxx.de',
  ),
  'datadirectory' => '/var/owncloud/data',
  'overwrite.cli.url' => 'https://xxx.xxx.de',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'oc1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'xxx.xxx.de',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.xxx.de',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'owncloud@xxx.xxx.de',
  'mail_smtppassword' => 'xxx',
  'mail_smtpsecure' => 'ssl',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Thunderbird Cardbook plugin

**Operating system:**
Ubuntu 14.04

#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
Related to carddav several hundred of
--- snip
{"reqId":"0fEfoG4BF0+IR+M26OeN","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Argument 3 passed to OCA\\Contacts\\CardDAV\\Card::__construct() must be of the type array, boolean given, called in \/var\/www\/apps\/oc\/apps\/contacts\/lib\/carddav\/addressbook.php on line 247 and defined at \/var\/www\/apps\/oc\/apps\/contacts\/lib\/carddav\/card.php#47","level":3,"time":"2015-11-21T11:13:36+00:00"}
{"reqId":"0fEfoG4BF0+IR+M26OeN","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Argument 3 passed to Sabre\\CardDAV\\Card::__construct() must be of the type array, boolean given, called in \/var\/www\/apps\/oc\/apps\/contacts\/lib\/carddav\/card.php on line 50 and defined at \/var\/www\/apps\/oc\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Card.php#46","level":3,"time":"2015-11-21T11:13:36+00:00"}
--- snap

#### Client log (Thunderbird Cardbook Plugin)
2015.11.21 13:40:03:065 : ocKontakte : No discovery
2015.11.21 13:40:03:065 : ocKontakte : Searching ctag...
2015.11.21 13:40:03:600 : ocKontakte : Ctag request finished, status : 207
2015.11.21 13:40:03:601 : ocKontakte : Ctag found : 1444145551
2015.11.21 13:40:03:602 : ocKontakte : Searching cards...
2015.11.21 13:40:03:909 : ocKontakte : Cards request finished, status : 207
2015.11.21 13:40:04:480 : ocKontakte : Can not get https://apps.xxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3AAAB.vcf (status : 404)
2015.11.21 13:40:04:587 : ocKontakte : Can not get https://apps.xxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3CwAAAA%3d%3d.vcf (status : 404)
2015.11.21 13:40:04:647 : ocKontakte : Can not get https://apps.xxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3CQAAAA%3d%3d.vcf (status : 404)
.. 130 more
2015.11.21 13:40:09:944 : ocKontakte : Can not get https://apps.xxxx.de/oc/remote.php/carddav/addressbooks/michael/kontakte/6AkRZ89uAACsfAOOAAA%3d.vcf (status : 404)
2015.11.21 13:40:10:441 : ocKontakte : Can not record ctag
2015.11.21 13:40:10:443 : All Synchronizations finished : 131 error, 0 up-to-date, 0 updated, 0 created, 0 deleted

**Comment by fonzmike** [comment]
What i tried so far with no success:

1. Delete all contacts in OC via Web Gui
2. Try to sync from Cardbook again ==> Failure

and:

1. Import vcf contacts list into empty OC contacts space ==> works
2. Try to sync from Cardbook again ==> Failure

**Comment by fonzmike** [comment]
Also Android EasyDav for Owncloud App stopped syncing contacts with http 404.

**Comment by RealRancor** [comment]
Looks to me like a duplicate of https://github.com/owncloud/contacts/issues/1103 as pointed out in your issue created in https://github.com/owncloud/core/issues/20658

**Comment by gvde** [comment]
I agree, it should be a dup of #1103. But omitting the apache logs makes it hard to tell. The apache log must show those accesses with 404 error code. That must show the uri requested. That way we could say what was really asked for.

The owncloud log errors are unrelated. They are almost 4 minutes or maybe even 1h 4m before that client log depending on the time zone of the client log. That problem has been discussed in owncloud/calendar#935. We probably need an issue raised at sabredav...

**Comment by fonzmike** [comment]
Attached pls. find the apache access log and the cardbook client log. This is a test i did today with thunderbird cardbook, times now match. 
[thunderbird_cardbook_client_log.txt](https://github.com/owncloud/contacts/files/41070/thunderbird_cardbook_client_log.txt)


[thunderbird_carddav_access.txt](https://github.com/owncloud/contacts/files/41069/thunderbird_carddav_access.txt)

**Comment by fonzmike** [comment]
Additional testing:

Entering an uri copied from the access log in my browser results in this xml:
<d:error><s:sabredav-version>2.1.7</s:sabredav-version><s:exception>Sabre\DAV\Exception\NotFound</s:exception><s:message>Card not found</s:message></d:error>

**Comment by fonzmike** [comment]
Additional debugging: I fetched the result of the PROPFIND requests with wget, see attachement. Maybe it helps.
[propfind_response.txt](https://github.com/owncloud/contacts/files/41077/propfind_response.txt)

**Comment by gvde** [comment]
This is very much a duplicate of #1103. Check the database table oc_contacts_card, column uri. Compare the uris you find there with the names in the access log. In particular "oCRFnz24AAAI3AQAAAA%3d%3d.vcf" looks ugly. base64 encoded uri oCRFnz24AAAI3AQAAAA== ??

**Comment by fonzmike** [comment]
The entries in table uri all are like 

```
AQMkAGI1OWM1ZmYAOC04ZTc2LTRkZAA0LTk4NjItZDI0ZmUzNzE0ZmVmAEYAAAPGryxXyUOaSL2Kaoax6u5LBwCBjXQARL8oQ7G/6AkRZ89uAAADEAAAAIGNdABEvyhDsb/oCRFnz24AAAI3AQAAAA==.vcf
```

These entries can be found urlencoded in the propfind result. 
```xml
<d:href>/oc/remote.php/carddav/addressbooks/michael/kontakte/AQMkAGI1OWM1ZmYAOC04ZTc2LTRkZAA0LTk4NjItZDI0ZmUzNzE0ZmVmAEYAAAPGryxXyUOaSL2Kaoax6u5LBwCBjXQARL8oQ7G/6AkRZ89uAAADEAAAAIGNdABEvyhDsb/oCRFnz24AAAI3AQAAAA%3d%3d.vcf</d:href>
```

The apache access log only shows requests uris containing the last part starting at the last slash.
`/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3AQAAAA%3d%3d.vcf`

**Comment by gvde** [comment]
That's even worse: a slash in the uri... Who came up with that? I am not sure that is supposed to work. Ever. I have to check the RFC but I guess at least the / needs to be encoded to work. If it's not encoded it should be a separator.

I would highly recommend to clean up those uris...

**Comment by pbek** [comment]
I'm also getting the error: `Argument 3 passed to Sabre\\CardDAV\\Card::__construct() must be of the type array, boolean given, called in \/var\/www\/owncloud\/apps\/contacts\/lib\/carddav\/card.php on line 50 and defined at \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Card.php` on OC 8.2.1 with Contacts 0.5.0.0 when syncing from my iPhone. A lot of contacts went missing on the iPhone since the OC update...

**Comment by pbek** [comment]
Same error messages when syncing with the OS X Contacts app...

**Comment by gvde** [comment]
@pbek as you have read in this is issue, it's a duplicate of #1103 and the solution is here and there. The cards in your database are messed up. Fix them and it works.

**Comment by pbek** [comment]
Thank you, @gvde. I wasn't sure what the "fix" was... Apparently I have hundreds of contacts with a uri like this `a9b767d4-b3fc-4ec1-83ad-57647a165527@my.domain.name.vcf`, but contact sync worked after exporting all contacts, deleting all contacts and importing all contacts again. The URIs are still the same, but it seems to work now. Strange... Nevertheless "someone" seemed to have duplicated a contact 200 times, that was a bit of a mess...

**Comment by fonzmike** [comment]
The solution in #1103 doesn't solve this. The messed up cards in the Database are created by OC / Contacts itself via import of an vcf file in the Browser.

I did some testing: Importet cards cannot be read by any of the used carddav clients: evolution, thunderbird cardbook, Android easy DAV for owncloud and CardDAV sync. The reason are http 404 errors because of the extra slashes in the uri created by the import code. But none of the used (and well established) clients can read cards created by OC/contacts 0.5.0.0.

In my opinion rfc 6352 is violated by this implementation. Chapter 6.3.1 for example says:
>In the event that the DAV:displayname property is not set, the client MAY
>   use the **last part** of the address book collection URI as the name;
>  however, that path segment may be "opaque" and not represent any
>   meaningful human-readable text.

Since Contacts 0.5.0.0 the 'last part' contains slashes and isn't an usable 'filename' (or what else OC expects here).

**Comment by gvde** [comment]
> The solution in #1103 doesn't solve this.

Which solution exactly? It's difficult to track what people have/do and which patches they have applied and which not...

> The messed up cards in the Database are created by OC / Contacts itself via import of an vcf file in the Browser.

Now if you only posted that vcf file so that someone can have an actually look and test what happens and whether one of the outstanding pull requests already fixes it...

> I did some testing: Importet cards cannot be read by any of the used carddav clients: evolution, thunderbird cardbook, Android easy DAV for owncloud and CardDAV sync. The reason are http 404 errors because of the extra slashes in the uri created by the import code. 

I don't know which "extra slashes" you mean. I have never seen "extra slashes" so far.

> But none of the used (and well established) clients can read cards created by OC/contacts 0.5.0.0.

You mean "imported"? Not "created". I haven't seen problems with cards created by the contacts app, in particular with that many clients.

> In my opinion rfc 6352 is violated by this implementation. Chapter 6.3.1 for example says

Chapter 6.3.1 is on MKCOL to create an address book collection. That really has nothing to do with the cards itself and the UIDs in place. If mapped to files/directories 6.3.1 is on the directory while the cards are the files inside the directory. In addition, RFC 6352 is the carddav protocol and not on what the cards look like.

> Since Contacts 0.5.0.0 the 'last part' contains slashes and isn't an usable 'filename' (or what else OC expects here).

It doesn't expect anything to retrieve a card but the UID of the card which needs to be correctly encoded to match what is found in the database...

**Comment by fonzmike** [comment]
Extra slashes: Posted Nov/22:
The entries created by contacts import in table uri all are like 
```
AQMkAGI1OWM1ZmYAOC04ZTc2LTRkZAA0LTk4NjItZDI0ZmUzNzE0ZmVmAEYAAAPGryxXyUOaSL2Kaoax6u5LBwCBjXQARL8oQ7G/6AkRZ89uAAADEAAAAIGNdABEvyhDsb/oCRFnz24AAAI3AQAAAA==.vcf
```
The apache access log only shows requests uris containing the last part starting at the last slash.
`/oc/remote.php/carddav/addressbooks/michael/kontakte/oCRFnz24AAAI3AQAAAA%3d%3d.vcf`

The path part of the uri is deleted by the clients and only the file part is appended to the base url.

And please recall Your answer:
>That's even worse: a slash in the uri... Who came up with that? I am not sure that is supposed to >work. Ever. I have to check the RFC but I guess at least the / needs to be encoded to work. If it's >not encoded it should be a separator.
>
>I would highly recommend to clean up those uris...

I'll post the cvf file soon, need some time to anonymize it.

**Comment by gvde** [comment]
During import it should use the UID in the card for the URI. If the UID contains the slash then it may get into the URI. I don't think UIDs should contain slashes... Ever... That's just ugly.

If you manually check the PROPFIND before you'll probably find that it reports the full URIs but your client strips them... That at least how it looks from the logs posted by others before...

**Comment by fonzmike** [comment]
Man, you are right. Those strange uids are in the vcf file! It is an export from MS Exchange. Its not the import, sorry for that. 

I'll do some testing how to fix them and let you know the results.

Thanks a lot!

**Comment by fonzmike** [comment]
Ok, solved. For all googlies landing here:
I exported my contacts list from MS Outlook as vcf list. After import into Ownclouds Contacts App all WebDav/CardDav Clients failed to sync because Outlook creates uids containing slashes. This leads to garbled URLs resulting in http errors 404 "not found" when a clients tries to retrieve a card.
 
I simple replaced the slashes in vcf field UID by string ABCD. Luckily all the slashes in the uid were prefix with the string "Q7G". A simple "replace all" form "Q7G/" to "ABCD" did it. Any text editor will do, notepad++, leafpad, vi :wink:

**Comment by gvde** [comment]
Could you try to replace the slash with %2F instead and see if that works?

**Comment by fonzmike** [comment]
Nope, doesn't work. HTTP 404
2016.01.13 11:53:15:600 : ocKontakte : Can not get https://apps.imuh.de/oc/remote.php/carddav/addressbooks/michael/kontakte/AAMkAGI1OWM1ZmY4LThlNzYtNGRkNC05ODYyLWQyNGZlMzcxNGZlZgBGAAAAAADGryxXyUOaSL2Kaoax6u5LBwCBjXQARL8oQ7G%2F6AkRZ89uAAAAAAAQAACBjXQARL8oQ7G%2F6AkRZ89uAAHVB0kyAAA=.vcf (status : 404)

**Comment by fonzmike** [comment]
Replace slashes with "_" works.
