### ISSUE TITLE
First and last name fields import wrongly from Thunderbird CSV

### ISSUE THREAD

**Issue by mach-o** [owncloud/contacts#1108]
If you create a simple contact in Thunderbird with first and last name fields specified and export it to csv, and then import it through the OwnCloud GUI specifying "Thunderbird CSV", the first name field in the imported contact will be blank, and the last name will be "{Last Name};{First Name}".

Example two-line csv file generated by Thunderbird that demonstrates the problem:
`First Name,Last Name,Display Name,Nickname,Primary Email,Secondary Email,Screen Name,Work Phone,Home Phone,Fax Number,Pager Number,Mobile Number,Home Address,Home Address 2,Home City,Home State,Home ZipCode,Home Country,Work Address,Work Address 2,Work City,Work State,Work ZipCode,Work Country,Job Title,Department,Organization,Web Page 1,Web Page 2,Birth Year,Birth Month,Birth Day,Custom 1,Custom 2,Custom 3,Custom 4,Notes,`
`First,Last,First Last,Nick,csv@import.com,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

This might seem innocuous, but wreaks a certain amount of havoc with downstream syncing to android, which seems to prefer the last name field to the full name field, oddly.

I rifled through the repository looking for the key section causing this, but I wasn't able to identify the key spot after a quick look. If a patch is posted, can you please post a link to it? I suspect I might find other bugs that it will help me to oorrect myself and submit. Even if someone doesn't have time to come up with a fix but can point me to the key sections, that would be appreciated.

**Comment by gvde** [comment]
Start at the current open pull requests. You should immediately find the right one related to the N property...

**Comment by mach-o** [comment]
Thanks so much! The change in [#1063](https://github.com/owncloud/contacts/pull/1063/) fixes my problem, and now I know where to look for future reference regarding imports.
