### ISSUE TITLE
Import / Export of contacts

### ISSUE THREAD

**Issue by enoch85** [owncloud/contacts#111]
This was in the previous version. What happened to that? Very useful and user friendly.

**Comment by Henni** [comment]
Definitely planned! Maybe it'll make it into 1.0, otherwise it will be implemented shortly after.

**Comment by enoch85** [comment]
@Henni What's your nick on IRC?

**Comment by crazy-max** [comment]
I have tried with Android stock app (+ DavDroid) and Thunderbird but i cannot retrieved categories and phone type changed on ownCloud 9.

So i have used [eM Client](http://www.emclient.com/) to synchronize my contacts.vcf (exported from ownCloud 8.2) with my ownCloud 9 carddav and it worked very well and i have kept categories and phone type (cell, work, etc...).

A contact on my contacts.vcf looks like this (from ownCloud 8.2) :

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.1//EN
UID:458b06c8-70cb-4a18-a8d7-e4cc353ff142
FN:Foo Bar
N:Foo;Bar;;;
TEL;TYPE=cell:+33777777777
REV:2016-01-10T16:57:24+00:00
END:VCARD
```

![contacts](https://cloud.githubusercontent.com/assets/1951866/13715459/22780f2a-e7d5-11e5-9f92-d32e56f96230.jpg)

**Comment by NeilMonday** [comment]
I'll be waiting (im)patiently for this.

Update: The workaround from @crazy-max also works with a vcf generated from gmail and imported with eM Client.

**Comment by DeepDiver1975** [comment]
> I'll be waiting (im)patiently for this.

Waiting time can be shorted by contributing to this open source project! :wink:

**Comment by dniku** [comment]
Has anybody found a way to import GMail contacts into ownCloud using only Linux software?

**Comment by irgendwie** [comment]
@Pastafarianist You can checkout the PR #237 - basic import functionality is worked on there.
It's already possible to import single *.vcf files (with one contact in them).
Feel free to contribute! :blush:

**Comment by dniku** [comment]
@crazy-max @NeilMonday which CardDAV url did you specify in eM Client? For me, the one which worked for DAVDroid (`/owncloud/remote.php/carddav`) fails with "error: method not allowed" in eM.

**Comment by NeilMonday** [comment]
I tried 2 apps like davdroid and neither worked (possibly due to user error). Maybe try em client with wine?

**Comment by NeilMonday** [comment]
Sorry, misread your comment. I think I used this URL https://myurl.com/remote.php/dav/addressbooks/users/myusername/default/. Obviously replace myurl and myusername with what you have.

**Comment by dniku** [comment]
@NeilMonday thanks, it worked, but the groups were not preserved (I imported the contacts through *.vcf exported from Google). Did it work in your case?

**UPD:** I haven't found any reference to my old contact groups in the *.vcf file I exported from Google. Regardless, they are present in the *.csv export. Could someone post an example of a *.vcf entry which uses groups, so that I could merge the two files?

**Comment by NeilMonday** [comment]
I don't use groups unfortunately. You could export/import one group at a time maybe?

**Comment by Henni** [comment]
@Pastafarianist take a look at https://www.w3.org/2002/12/cal/vcard-examples/john-doe.vcf
It contains groups, which are called CATEGORIES in the vCard standard.

**Comment by dniku** [comment]
@Henni will ownCloud recognize **CATEGORIES** as a comma-separated string?

**Comment by Henni** [comment]
@Pastafarianist yes
BTW: you are all welcome in our irc channel #owncloud-contacts

**Comment by Henni** [comment]
Partially fixed by #237 which implemented vCard import.
Closing in favor of a new label [feature:import/export](https://github.com/owncloud/contacts/issues?q=is%3Aissue+is%3Aopen+label%3Afeature%3Aimport%2Fexport)

**Comment by dniku** [comment]
Here is a very dirty example of how to convert a Google CSV to a VCF file: https://gist.github.com/Pastafarianist/6262b184ca3a8c990d4a

**Comment by enoch85** [comment]
@Pastafarianist 

> @crazy-max @NeilMonday which CardDAV url did you specify in eM Client? For me, the one which > worked for DAVDroid (/owncloud/remote.php/carddav) fails with "error: method not allowed" in eM.

The DAVDroid client will be updated, they released 1.0 beta now: https://davdroid.bitfire.at/configuration/owncloud/
https://twitter.com/davdroidapp/status/711675959582334976

**Comment by malfatti** [comment]
Hi!

I installed this app by cloning this repo into apps/ and then enable it on admin apps page. I can see the import button, but when I try to import a vcf with 257 contacts, I got no feedback, no loading, no nothing, and I waited for more than 30'. The same file imported sucessfuly in OC8.2.3, so the file seems to be ok.

Am I doing something wrong?

Thanks!

**Comment by Henni** [comment]
@malfatti In theory it should work. We haven't implemented feedback for the import yet (e.g. progress bar). Please open a separate issue.
