### ISSUE TITLE
[8.2.2] Contacts App Icon Not Loading when hosting ownCloud with a webroot

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/contacts#1122]
My ownCloud site is hosted under a webroot (https://EXAMPLE.com/owncloud) and as you can see in the screenshot, the icons for the Contacts and Calendar app do not load. The contacts app is presenting it's icon at ``/apps/contacts/img/contacts.svg`` when it should be at ``/owncloud/apps/contacts/img/contacts.svg``

![screenshot from 2016-01-07 22-54-39](https://cloud.githubusercontent.com/assets/1018807/12192279/11b837c0-b592-11e5-9f62-e7fda60d40e3.png)

This only affects https://github.com/owncloud/contacts and https://github.com/owncloud/calendar, the other apps all give the correct icon URL.

**Comment by josh4trunks** [comment]
Same issue here https://github.com/owncloud/calendar/issues/1011

**Comment by gvde** [comment]
Don't post duplicates. It's just so annoying and makes any reasonable discussion impossible.

This works fine for me. Clear your browser cache and all cookies. Try another browser. Or remove and reinstall the apps.

Close both issues here and for the calendar app and open - if the problem perists - an issue in the owncloud core as it's a core function which determines the url for the apps. And don't forget to use the template from the contribution guidelines to report the issue...

**Comment by josh4trunks** [comment]
Ok, I've tried with multiple OS's/browsers. I will confirm by removing and reinstalling the apps.

Then I'll close these issues and post in https://github.com/owncloud/core/

**Comment by josh4trunks** [comment]
@gvde to confirm, you are using owncloud 8.2.2 with a webroot and the contacts app icon shows? This only stopped working for me with the update to 8.2.2, so I'm assuming it's a depreciated function somewhere.

**Comment by gvde** [comment]
Yes:
```
<li data-id="contacts">
						<a href="/owncloud/index.php/apps/contacts/" tabindex="3" class="active">
							<img class="app-icon svg" alt="" src="/owncloud/apps/contacts/img/contacts.svg">
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Contacts							</span>
						</a>
					</li>
```

Did you update the contacts app to the latest version?
Did you ever install owncloud in web root before and then migrated or moved it after installation?

**Comment by josh4trunks** [comment]
I don't remember ever updating the contacts app through the Apps page. But ``occ upgrade`` might have done it for me? I'm on version 0.5.0.0 of the contacts app currently.

No, I've been using a webroot since putting this server into production with ownCloud version 7.0.0.
I only recently installed( or enabled?) the contacts app a few months ago on the Apps page. I've been using the calendar app since my initial installation.
