### ISSUE TITLE
Order of detail items

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#118]
Currently the fields are ordered alphabetically in the dropdown, and by i-have-no-idea in the details view.

The order should be like this in both the details view and dropdown (**bold** items are shown by default):
- Organization & title (should be combined

^ we could put that in the header as well, smaller below the name
- **Phone**
- **Email**
- **Address**
- Instant messaging

^ that’s all the contact stuff, which can have home/work/other dropdowns.
- Nickname
- Birthday
- Website
- Notes
- Groups
- Role (let’s remove it …)

^ not entirely set on the order of the stuff in this last part.

**Comment by DeepDiver1975** [comment]
> Organization & title (should be combined
> 
> ^ we could put that in the header as well, smaller below the name

I like this - @tomneedham for #103

**Comment by DeepDiver1975** [comment]
I'll take care about the ordering

**Comment by Henni** [comment]
@DeepDiver1975 my idea would be to create a filter which orders the attributes based on the order in vCardMeta...

**Comment by DeepDiver1975** [comment]
> my idea would be to create a filter which orders the attributes based on the order in vCardMeta...

no need for a custom filter - orderby can be used

**Comment by DeepDiver1975** [comment]
> orderby can be used

grrr .... can NOT be used

**Comment by Henni** [comment]
you probably need to write your own filter because props is an object and not an array

**Comment by DeepDiver1975** [comment]
> you probably need to write your own filter because props is an object and not an array

yes - on it

**Comment by DeepDiver1975** [comment]
giving up on this one ....

**Comment by DeepDiver1975** [comment]
@Henni feel free to take a look :wink:

**Comment by Henni** [comment]
I'm on it

**Comment by DeepDiver1975** [comment]
> I'm on it

thx
