### ISSUE TITLE
Creating new contact and adding additional fields leads to JS error

### ISSUE THREAD

**Issue by irgendwie** [owncloud/contacts#125]
- Create a new contact
- Add an additional Mail field

`Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: propData in prop, Duplicate key: object:147, Duplicate value: {"value":[""],"meta":{"type":["HOME"]}}`

Same error occurs for the other pre present fields.

**Comment by DeepDiver1975** [comment]
caused by #94

**Comment by DeepDiver1975** [comment]
> caused by #94

maybe ...
