### ISSUE TITLE
carddav oc 9.0.0 rc1

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [owncloud/contacts#128]
Any plans on adding it? It seems to just sync to www.myserver.com without anything after .com (before it was remote.php/etc/etc) caldav works that way, but i cant specify to which address book it needs to be synced. great app, thanks!

ezra

**Comment by DeepDiver1975** [comment]
The app will be published to the appstore soon - ready for use as soon as oc9 will be released

**Comment by enoch85** [comment]
@ezraholm50 The latest master is in [our VM](https://www.techandme.se/pre-configured-owncloud-installaton/). Or did I forget to tell you ;) :smile: 

@DeepDiver1975 So in other words, the address will be the same as before - without any need to change?

**Comment by WaaromZoMoeilijk** [comment]
Nice, and how about the carddav options in the testing version? Cause I cant seem to get my contacts to show in the app. Should I specify myserver.com/remote.php/carddav/user/adressbook or something like that? As stated before the caldav only requires the server domain without any extension to the url.
Thanks

**Comment by MeCias** [comment]
Can't get it to work either.

**Comment by DeepDiver1975** [comment]
We need to show the addessbook URLs somewhere.

**Comment by Henni** [comment]
Should be easy enough to add them to the addressbooklist
