### ISSUE TITLE
Last address book, should it be deletable?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#139]
Seems like the last address book should not be possible to delete. Contacts without an address book does not make sense, and this could happen mostly by accident.

You should only be able to delete an address book when there are at least two. When there’s a single address book, the delete icon should not be there.

**Comment by jancborchardt** [comment]
Tried with `ng-if="addressBooks.length > 1"` on the action span, but doesn’t work. :\

**Comment by ghormoon** [comment]
actually I'm glad I can delete them all when I break things when testing because one of my user has way too broken data :)))
I'd prefer only something like alert window that it's not a good idea to delete them all, but actually have the option

**Comment by jancborchardt** [comment]
Sure, but that should never happen in the first place and would be fine to have as a console command only.

It’s way too risky and prone to data loss to have the delete button on the only address book (which is the most common case).

**Comment by ghormoon** [comment]
actually even when having multiple there may be some sort of "are you f**\* sure?" prompt when deleting some to avoid missclick, though that's not top priority imho.

**Comment by jancborchardt** [comment]
Well yeah, there should always be undo. (Not a confirmation dialog, for reasons pointed out in [this blog post](http://alistapart.com/article/neveruseawarning).)

**Comment by ghormoon** [comment]
I think that article misses a sort of BFU. I've actually seen a user complaining that they lost data in system cleanup ... because they were having them in recycle bin "because there I know where to find it" ... so it may happen that someone just bends the undo to something else than it was mean to.
Likely still better than the warning window though. (and tbh, I can't think of better solution, so I should stop complaining :))

**Comment by jancborchardt** [comment]
The comparison is confirmation window vs undo. ;) Anything else is a different discussion. There is not and there will not be a »trash bin« for address books.
