### ISSUE TITLE
Carddav - Adressbook - exception Sabre\DAV\Exception\NotImplemented

### ISSUE THREAD

**Issue by habakuk007** [owncloud/contacts#140]
Hello,

if i try to open the carddav-link that is shown by owncloud in the ontacts app I get his error: 

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no handler found for this "GET" method</s:message>
</d:error>
```

The Url looks like https://example.com/remote.php/carddav/addressbooks/Stefan/kontakte

I use Contacts 0.5.0.0 with ownCloud 8.2.2

Any ideas what is wrong? 

Best regards!  
    Stefan

**Comment by habakuk007** [comment]
If I try the link https://example.com/remote.php/carddav/addressbooks/Stefan/kontakte?export I get this error:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\VObject\ParseException</s:exception>
  <s:message>Invalid Mimedir file. Line starting at 17 did not follow iCalendar/vCard conventions</s:message>
</d:error>
```

**Comment by Henni** [comment]
This contacts app only works with owncloud 9.0, which will be released on Monday.

**Comment by ghost** [comment]
@habakuk007 Issues with the "old" contacts app should be reported to https://github.com/owncloudarchive/contacts/issues.

However this app is deprecated and unsupported so if there is an issue with the old app its very unlikely that it gets fixed.
