### ISSUE TITLE
Birthdays don't get saved

### ISSUE THREAD

**Issue by MeCias** [owncloud/contacts#143]
Hi,

I am using the last master and try to add some sample contacts at the moment I have just issues to get the birthdays in. If I add the field Birthday and hover over it the mouse changes to an hand but nothing else happens even if I click into the field. If I write a birthday manually in like 01.01.1999 it sticks for the moment but disappears as son the page get refreshed.
What should happen as soon I am hovering with the mouse over the field? Would I see an input calendar?
Thanks in advance

**Comment by Henni** [comment]
@MeCias which browser do you use?

**Comment by MeCias** [comment]
I am using Firefox 45

EDIT

I tried now as well the Firefox 44.0.2 Desktop and here it is not working eiher on the 44.0.2 mobile I get the input calendar to see. It works on the mobile version in my case. Even if I switch off all addons on the Desktop version of the Firefox I have still no input calendar.

If I put in the right format (1999-01-01) then it seems to work as well.

**Comment by Henni** [comment]
Seems like Firefox still doesn't support date inputs.

**Comment by MeCias** [comment]
Yes I see, seems to be a 4 year old feature request that still has not made it into Firefox desktop 

https://bugzilla.mozilla.org/show_bug.cgi?id=825294

**Comment by DeepDiver1975** [comment]
Looks like we need to pull in yet another angular module
- https://github.com/g00fy-/angular-datepicker/wiki/Getting-started
- https://material.angularjs.org/latest/demo/datepicker

**Comment by MeCias** [comment]
The date picker in the new calendar app works with firefox

**Comment by Henni** [comment]
https://angular-ui.github.io/bootstrap/, which we already include, contains a date widget.

**Comment by MeCias** [comment]
Hi,

can that be that the date picker disappeared? At least I don't see him no more on my OC 9.0 Final with Contacts 1.0.

**Comment by DeepDiver1975** [comment]
> can that be that the date picker disappeared?

the version with the datepicker is not yet pushed to the appstore - will do asap

**Comment by MeCias** [comment]
Thanks a lot!
