### ISSUE TITLE
Contact images

### ISSUE THREAD

**Issue by MeCias** [owncloud/contacts#144]
Hi,

I can see that there is no functionality for adding contact images like in the old contacts app at the moment and I can not get the synchronisation with cardav to work, so that I can not see if the contact images would get displayed at all. 
To add or edit the images over the web interface would be nice , is it planned to implement?

Thanks again

**Comment by Henni** [comment]
This is a planned feature. Hopefully very soon.

**Comment by skjnldsv** [comment]
Thank you!

**Comment by flo1o1** [comment]
Well if this is a feature, which doesn't exist yet, then probably the [documentation should reflect this](https://doc.owncloud.org/server/9.0/user_manual/pim/contacts.html#defining-a-contact-avatar). Right now, to me it is a bug (see #200 and #364), not an enhancement… :confused:

**Comment by DeepDiver1975** [comment]
documentation issue has been raised in https://github.com/owncloud/documentation/issues/2359

**Comment by flo1o1** [comment]
Thanks @DeepDiver1975! Do you know why this feature was kicked out? Feels like a degradation to me…

**Comment by skjnldsv** [comment]
It's being implemented: #380
