### ISSUE TITLE
Content-Security-Policy error

### ISSUE THREAD

**Issue by tflidd** [owncloud/contacts#151]
### Steps to reproduce
1. Get recent version from github
2. Activate app
3. load app and check error console
### Expected behaviour

no errors
### Actual behaviour

there are some messages:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://myhostname 'unsafe-eval'"). contacts
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create dav.js:3050:415
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf http://oc9/remote.php/dav/addressbooks blockiert ("connect-src https://`myhostname").
```

My owncloud is available via https://myhost/oc9, please note that the last log line shows the url `http://oc9/remote.php/...`.

I have some problems with the interface when adding a new address book. I can add a new name and click on the button but nothing happens. When I reload the whole app, the new address book has been created. I'm not sure if this is related to this problem.

I have set the `overwrite.cli.url` in the config.php, I also tried to set the `overwritewebroot`-variable. It didn't help.
### Server configuration

Debian 8/Apache/mariadb, mod_php7.0.4 (dotdeb)
OC 9.0.0 RC 2
contacts from github, last submit: 82f8501836a94798a54ab6d4bdb4199e6ca92945

**List of activated apps:**

```
  - activity: 2.2.1
  - announcementcenter: true
  - calendar: 0.82
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.8
  - news: 7.1.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'oc3okr27z0v5',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' =>
  array (
    0 => 'myhost',
  ),
  'datadirectory' => '/var/www/oc9/data',
  'overwrite.cli.url' => 'https://myhost/oc9',
  'overwritewebroot' => '/oc9',
  'dbtype' => 'mysql',
  'version' => '9.0.0.17',
  'dbname' => 'oc9',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin3',
  'dbpassword' => 'xxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
    'timeout' => 0,
  ),
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by irgendwie** [comment]
> I have some problems with the interface when adding a new address book. I can add a new name and click on the button but nothing happens. When I reload the whole app, the new address book has been created. I'm not sure if this is related to this problem.

That is a known issue, which will be fixed in the future. It's just a visual thing and shouldn't affect functionality.

To the rest: @DeepDiver1975 @Henni, ideas?

**Comment by DeepDiver1975** [comment]
Which browser? Can you verify this in another browser?

@LukasReschke regarding csp - THX

**Comment by LukasReschke** [comment]
> there are some messages:

Will be fixed once we finally move to jQuery 2. This is a false positive in jQuery 1.x that however has no impact except just being there :wink:

**Comment by DeepDiver1975** [comment]
THX @LukasReschke
