### ISSUE TITLE
When a new contact has no details at all filled in yet, it should not be possible to add another one

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#160]
Right now you can just add empty contacts endlessly, which makes little sense.

When a new contact has no specific info filled in yet, clicking »Add new contact« should just focus the name field of the already added one.

**Comment by skjnldsv** [comment]
I'm willing to take care of this issue.
Small question first. I'm suggesting that adding a new contact should block adding a new one until the first one is valid.
To be valid only the FN field has to be present right?

So as long as our first new contact doesn't have a valid fullName field, we won't add a new one!
Agreed @jancborchardt ?

**Comment by Henni** [comment]
@skjnldsv :+1:

**Comment by jancborchardt** [comment]
Yup, sounds good!
