### ISSUE TITLE
Add groups field to default fields of new contacts

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#163]
The groups field should be a default field for new contacts, and all contacts.

It also doesn’t make a whole lot of sense to be able to remove this, so the deletion functionality should be disabled.
Basically same for the last email, phone, and address – these should always stay there by default. Just as you can not remove the name.

**Comment by DeepDiver1975** [comment]
> Basically same for the last email, phone, and address – these should always stay there by default. Just as you can not remove the name.

new issue please
