### ISSUE TITLE
Empty entry in group select2

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#169]
When you click in the select2, there’s an empty row:
![capture du 2016-03-08 13-46-06](https://cloud.githubusercontent.com/assets/925062/13602012/37eaee66-e534-11e5-9a46-4b27d28e1a9f.png)
When you add it, this is how it looks:
![capture du 2016-03-08 13-46-20](https://cloud.githubusercontent.com/assets/925062/13602013/37eb2c0a-e534-11e5-95bb-f0f9d638dbdc.png)

cc @DeepDiver1975 @Henni

**Comment by jancborchardt** [comment]
The group then also gets shown in the left navigation:
![capture du 2016-03-08 14-04-22](https://cloud.githubusercontent.com/assets/925062/13602514/59eb3b3a-e537-11e5-8289-b740a3184a33.png)

**Comment by jancborchardt** [comment]
(But when clicked, every contact gets shown.)

**Comment by DeepDiver1975** [comment]
I have seen this as well - unclear where this is coming from - maybe some crap living in one of the vcards

**Comment by jancborchardt** [comment]
Happens in a completely fresh addressbook created from the web interface as well.
