### ISSUE TITLE
Label not saved after changing a character from uppercase to lowercase

### ISSUE THREAD

**Issue by blpp** [owncloud/contacts#169]
I have a address with a custom label, e.g. "Home TH". Now I want to change the label to "Home Th". I can enter this but the change from uppercase to lowercase isn't saved at all. If I close the contact and open it again, the label is still "Home TH".

I'm using OC 5.0.9.

**Comment by jancborchardt** [comment]
Closing because I assume this is not an issue anymore. @blpp let us know if it still is.
