### ISSUE TITLE
No immediate feedback on address book deletion

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#171]
When deleting an address book, currently nothing happens.

Instead, the address book should directly vanish from the interface, as should all the contacts and groups inside of it.

**Comment by Henni** [comment]
The addressbook should disappear immediately (which is correct).
Groups, and contacts probably still stay (which is a bug).

**Comment by jancborchardt** [comment]
The addressbook doesn’t disappear immediately for me at least.

**Comment by codethief** [comment]
I'm having the same issue. Neither the addressbook nor the contacts it contains disappear.

**Comment by Henni** [comment]
@jancborchardt we should look into this at the next meetup

**Comment by irgendwie** [comment]
Should be fixed with the last cleanup PRs from @Henni
