### ISSUE TITLE
Field names are broken/not translated ("INTERNET,HOME,pref")

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/contacts#173]
### Steps to reproduce
1. Add ownCloud Contacts to external CardDAV client (for instance, iOS)
2. On the external client, add a new contact, with any E-mail address
3. Open the contact in ownCloud Contacts web frontend
### Expected behaviour

The contact's E-mail address should be labeled as ("E-mail", "E-mail Home", or even "Home")
### Actual behaviour

Instead of any useful field label, the field is called "INTERNET,HOME,pref". Also, other fields are not translated, like "CELL,VOICE,pref" or "HOME,pref".
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11

**Comment by Henni** [comment]
This might be, because we currently don't handle the `pref` property.

**Comment by nicokaiser** [comment]
Ok, I see. However this might be confusing, as many popular CardDAV clients (iOS?) do set this property for default fields.

**Comment by Henni** [comment]
@nicokaiser this is definitely a bug, that should and will be fixed.

**Comment by nicokaiser** [comment]
This is even worse than expected: when edited, the entry is saved as "INTERNET\,WORK\,pref" and thus displayed as such in other clients.

**Comment by DeepDiver1975** [comment]
> This is even worse than expected: when edited, the entry is saved as "INTERNET\,WORK\,pref" and thus displayed as such in other clients.

as far as I can tell this is an issue in the vcard.js library
