### ISSUE TITLE
Contact app tries to connect to broken URL

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/contacts#174]
### Steps to reproduce
1. Open Contacts app
### Expected behaviour

No error messages in the console
### Actual behaviour

The JavaScript console complains about an access violation for "http://remote.php/dav/addressbooks":

```
Refused to connect to 'http://remote.php/dav/addressbooks' because it violates the following Content Security Policy directive: "connect-src 'self'". dav.js?v=55c6a8a8d8646507dfaad3c62d22aac0:3669
```

There seems to be a broken URL generation function which does not consider the host, and even forgets about the protocol (the site is served as HTTPS, which is known to ownCloud) and adds the default "http".
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11
#### Browser log

```
Refused to connect to 'http://remote.php/dav/addressbooks' because it violates the following Content Security Policy directive: "connect-src 'self'". dav.js?v=55c6a8a8d8646507dfaad3c62d22aac0:3669
```

**Comment by DeepDiver1975** [comment]
> Content Security Policy

afaik this is related to the fact that we use an old jquery version - right @LukasReschke

**Comment by nicokaiser** [comment]
I'm pretty sure the URL is built wrong, as the string "http://remote.php/dav/addressbooks" is passed through several instances. I was not able to completely trace it, but I can try again.

**Comment by LukasReschke** [comment]
> Refused to connect to 'http://remote.php/dav/addressbooks' because it violates the following Content Security Policy directive: "connect-src 'self'". dav.js?v=55c6a8a8d8646507dfaad3c62d22aac0:3669

Yep. In this case the CSP error is legit here. ownClouds AppFramework CSP does not allow JS connections to external resources if they are not whitelisted. And `http://remote.php` is considered an untrusted endpoint, which it also is :)

**Comment by DeepDiver1975** [comment]
I cannot reproduce this - no idea where that call is coming from - sorry

**Comment by tsumi** [comment]
Hi,
same happen to me on a fresh install of OC9.

Environment details:
Operating system: CentOS 7
Web server: Apache 2.4
Database: MySQL 5.5
PHP version: PHP 5.6
ownCloud version: 9.0.0
Contacts version: 1.0.0.0
Browser: Firefox 45.0

**Comment by Rello** [comment]
+1
clean install from zip archive
