### ISSUE TITLE
Organization entry gets an additional comma

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/contacts#177]
### Steps to reproduce
1. Create a contact in any CardDAV client, with the "Organization" field set to anything
2. Open Contacts app
3. View this contact
### Expected behaviour

The "Organization" entry should be like saved in the client
### Actual behaviour

An additional comma is added to the "Organiziation" entry. See screenshot, instead of "BörseGo AG" the input field says "BörseGo AG,". I did not dare to remove the comma, maybe it breaks the whole card...

The VCARD says correctly

```
ORG:BörseGo AG;
```
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11

**Comment by nicokaiser** [comment]
![screen shot 2016-03-08 at 22 41 06](https://cloud.githubusercontent.com/assets/238631/13618084/74725f42-e582-11e5-80c3-3e26d810aa9d.png)

**Comment by DeepDiver1975** [comment]
So - the organization attribute can be a semi-colon separated string. https://tools.ietf.org/html/rfc6350#section-6.6.4

I suggest to display only the first element which is the true orga - other elements of the array will be kept as is so that we do not kill data
