### ISSUE TITLE
app.ownCloud.org - wrong link for ownCloud9

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/contacts#181]
As a user, when I go to the download page
https://apps.owncloud.com/content/show.php/Contacts?content=168708

and I click on download for version 9
https://apps.owncloud.com/content/download.php?content=168708&id=1&tan=15892076

The version I get is 0.0.0.4

It should be 1.0.0.0

**Comment by DeepDiver1975** [comment]
The next tag will be in sync with the version in the appstore
