### ISSUE TITLE
Documentation issue for owncloud 9.0 carddav sync

### ISSUE THREAD

**Issue by joswart** [owncloud/contacts#182]
For setting up carddav the documentation listed here: https://doc.owncloud.org/server/9.0/user_manual/pim/sync_ios.html reports entering the following string:

`example.com/remote.php/dav/principals/username`

This will result into a validation error. The owncloud 9 contacts app actually reports another string, which seems to work:

`/owncloud/remote.php/dav/addressbooks/users/[username]/contacts/`

Could you please update the documentation with the correct string?

**Comment by ghost** [comment]
@joswart Thanks for your report. The documentation is done in https://github.com/owncloud/documentation/issues where this seems that a review of the docs is already tracked: https://github.com/owncloud/documentation/issues/2074

**Comment by DeepDiver1975** [comment]
tracked in https://github.com/owncloud/documentation/issues/2074
