### ISSUE TITLE
Contact name does not fit

### ISSUE THREAD

**Issue by oljask** [owncloud/contacts#184]
Name field is to small. My address book entries dont fit in it.
![image of contacts](http://i63.tinypic.com/1695a2a.png)
The Name on green background missing last characters.

**Comment by DeepDiver1975** [comment]
@jancborchardt to some extend we need to respect longer names in organization and title as well ....

**Comment by tomneedham** [comment]
Noticed this myself earlier and submitted https://github.com/owncloud/contacts/pull/187 (adds ellipses so its clearer for the users and extends the title field slightly)

I'd suggest once we know the mobile styling arrangements a bit better we can extend the fields depending on the device.

**Comment by DeepDiver1975** [comment]
fixed with #187
