### ISSUE TITLE
Phone number type option shows strangely when created in OSX

### ISSUE THREAD

**Issue by tomneedham** [owncloud/contacts#188]
Stepss to reproduce
1. Create contact on OSX
2. View in browser
### Expected behaviour
- Should show 'Mobile'
### Actual behaviour

![screen shot 2016-03-10 at 15 15 42](https://cloud.githubusercontent.com/assets/660805/13673879/005c909e-e6d3-11e5-82a3-c8135835363a.png)

**Comment by nicokaiser** [comment]
See #173

**Comment by DeepDiver1975** [comment]
close because of being a duplicate
