### ISSUE TITLE
Contact photos are always displayed with square aspect ratio, and without crop

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/contacts#193]
### Steps to reproduce
1. Create a contact with Mac OS X Contacts app
2. Add a non-square picture and crop it, save the contact
3. Open the contact in ownCloud
### Expected behaviour

The picture should be displayed correctly cropped
### Actual behaviour

Seems like OS X saves the un-cropped image along with cropping information, which ownCloud cannot apply. So the images is displayed uncropped yet with a square aspect ratio, which may both be problematic. See screenshot.

<img width="430" alt="screen shot 2016-03-11 at 15 03 31" src="https://cloud.githubusercontent.com/assets/238631/13704201/f34cfd4e-e79a-11e5-85ee-2c4930f5ffae.png">
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11

**Comment by nicokaiser** [comment]
Here is the original vCard: https://gist.github.com/nicokaiser/31256b16535bb4854342

**Comment by DeepDiver1975** [comment]
We need to understand how this cropping works

```
X-ABCROP-RECTANGLE=ABClipRect_1&28&173&279&279&ALVBCRfbhyfEy666aaC3yg==
```

**Comment by v1r0x** [comment]
How does it look in OS X?

**Comment by nicokaiser** [comment]
<img width="383" alt="screen shot 2016-03-11 at 16 09 19" src="https://cloud.githubusercontent.com/assets/238631/13706005/a18aea8a-e7a3-11e5-8610-3343994cb009.png">

**Comment by nicokaiser** [comment]
There is some code on cropping here: https://github.com/blind-coder/rcmcarddav/pull/15/files

**Comment by v1r0x** [comment]
Ok, looks like the one I cropped in GIMP.
So the values are: `X-ABCROP-RECTANGLE=ABClipRect_1&<x>&imgHeight - cropHeight - <y>&<cropWidth>&<cropHeight>&`

**Comment by DeepDiver1975** [comment]
> There is some code on cropping here: https://github.com/blind-coder/rcmcarddav/pull/15/files

nice - THX - would be great to have that code in javascript ....

**Comment by nicokaiser** [comment]
Apart from the mentioned PR not having any consistency checks (so page could be crashed if there were too few "&", etc.), the main problem would be solving this in CSS (not sure if there currently is an elegant way to resize and crop image using only CSS)...

**Comment by Henni** [comment]
There are possibilities in CSS to get close to what we want (using `object-fit` or `background-size`) but they are neither well supported nor solving it perfectly.
We have to fix this in JS.

**Comment by v1r0x** [comment]
I'd fix this, but had no time to have a closer look at the app. The JS-Code for it shouldn't be that hard

**Comment by DeepDiver1975** [comment]
maybe this is of help: https://github.com/alexisnomine/ngCropper

**Comment by DeepDiver1975** [comment]
@nicokaiser please retest the latest version - we do not yet fully process X-ABCROP-RECTANGLE - but at least the aspect is preserved - for now this fullfills the needs from my pov.

I'd like to close this issue once you agree on - THX

**Comment by nicokaiser** [comment]
This looks good in the latest version! Thanks!
