### ISSUE TITLE
Maintenance and Release Schedule for contacts

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#194]
Like calendar has already: 
https://github.com/owncloud/calendar/wiki/Maintenance-and-Release-Schedule

**Comment by DeepDiver1975** [comment]
TBH: in the current development state and given the rather variable time contributors can spend I suggest to do this more in a dynamic way.

**Comment by aspdye** [comment]
Question: Is this different to the calendar guys?

**Comment by DeepDiver1975** [comment]
Ask the calendar guys :Wink:
