### ISSUE TITLE
Make Telephone Numbers, Mails and Locations clickable

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#198]
- [ ] Telephone Numbers (could be realized with tel:)
- [ ] Mails (could be realized with a direct link to the Mails-App or by opening Local Mail Client)
- [ ] Locations (could be realized with a direct link to the Maps-App or by opening another Client)

**Comment by plastikschnitzer** [comment]
Great idea! This would be a breakthrough feature for me to use the contacts app!
