### ISSUE TITLE
Owncloud Upgrade 8.2.2 to 9.0 - Major Contact Issues

### ISSUE THREAD

**Issue by fracture-point** [owncloud/contacts#199]
### Steps to reproduce

9.0 Upgrade from 8.2.2:
1. apt-get update, apt-get upgrade, apt-get dist-upgrade
2. sudo -u www-data php occ upgrade
3. sudo -u www-data php occ maintenance:mode --off
4. log in as administrator and re-enable contact and calendar apps.
5. log in as normal user, navigate to contacts, and gasp at new issues.
### Expected behaviour

Data should be identical to values in 8.2.2
### Actual behaviour

Lots of data issues, and functionality missing or not working properly:

**Phone Type Changes (8.2.2 value --> 9.0 value):**
UK (Orange) --> [blank]
Google Biz # --> [blank]
T-mobile --> PREF,T-Mobile
Outgoing Voip --> [blank]
_Note that this does not appear to be an issue with special characters.  For instance the value "Canada (Telus)" appears identically after the upgrade_

**Email Type Changes (8.2.2 value --> 9.0 value):**
Home --> INTERNET,HOME

**Address Type Changes (8.2.2 value --> 9.0 value):**
Home --> HOME,pref

**General Issues:**
1. Contacts take minutes to appear (434 contacts in 16 groups, takes 7 seconds in v8.2.2)
2. No button to create a new Contact Group
3. Contact groups do not show up at all until I click on an individual contact
4. Starred contacts group does not exist anymore
5. "Not Grouped" group does not exist anymore
6. No longer able to add custom phone types (dropdown list with no "other" option available in the type dropdowns).
7. At least one contact that had a picture pre-upgrade now shows a ? in the picture box.

Let me know if you want me to open individual tickets for these or if you need additional information.  With the volume of issues I've experienced I cannot upgrade to 9.0.
### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
MariaDB 10.0.24
**PHP version:**
php 5.5.9
**ownCloud version:** (see ownCloud admin page)
9.0
**Contacts version:** (see ownCloud apps page)
1.0.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2
**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- updatenotification: 0.1.0
  Disabled:
- bookmarks
- encryption
- external
- files_external
- firstrunwizard
- notes
- tasks
- templateeditor
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocerysw1jz4b",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "\/data\/owncloud",
        "overwrite.cli.url": "https:\/\/**_REMOVED SENSITIVE VALUE**_\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "OwnCloud",
        "mail_domain": "**_REMOVED SENSITIVE VALUE**_",
        "appstore.experimental.enabled": true,
        "memcache.local": "\OC\Memcache\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "trashbin_retention_obligation": "30",
        "maintenance": false,
        "loglevel": 2,
        "updatechecker": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.6",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.0",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.0.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1449253052.1423",
            "lastcron": "1457794802",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "fbsync": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "ocsid": "174311",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "6": "1452026815.8172",
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "cronjob_user_offset": "1000",
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration

**Browser:** Safari Version 9.0.3

**Operating system:** Ubuntu 14.04
**CardDAV-clients:** Haven't tested yet due to massive UI issues
#### Web server error log

Nothing related to OC
#### ownCloud log (data/owncloud.log)

Given the amount of sensitive (and unrelated Calendar data), I search for rows with contact references:

{"reqId":"JDCv1gT8BnS9aWqc9Te3","remoteAddr":"MASKED","app":"PHP","message":"Undefined index: addressBookId at \/var\/www\/owncloud\/apps\/contacts\/lib\/hooks.php#109","level":3,"time":"2016-02-10T17:17:37+00:00"}
#### Browser log

N/A

**Comment by gvde** [comment]
> Lots of data issues, and functionality missing or not working properly.

Well I did basically the same update on the ubuntu 14.04 platform and it works good with some minor, known issues. No "lots". So I guess you should be more specific in the issues you have, what's missing and what's not working properly... From that one sentence noone will know...

**Comment by fracture-point** [comment]
Sorry!  @gvde - I was copy-pasting because the ticket was so long, and forgot to add the important part (the issues!).  I updated the ticket above.

**Comment by DeepDiver1975** [comment]
> Email Type Changes (8.2.2 value --> 9.0 value):
> Home --> INTERNET,HOME
> 
> Address Type Changes (8.2.2 value --> 9.0 value):
> Home --> HOME,pref

should work better with #195 - please test - THX

**Comment by DeepDiver1975** [comment]
> Phone Type Changes (8.2.2 value --> 9.0 value):
> UK (Orange) --> [blank]
> Google Biz # --> [blank]
> T-mobile --> PREF,T-Mobile
> Outgoing Voip --> [blank]
> Note that this does not appear to be an issue with special characters. For instance the value "Canada (Telus)" appears identically after the upgrade

Can I ask you for an example vcard for testing? THX

**Comment by DeepDiver1975** [comment]
> Contacts take minutes to appear (434 contacts in 16 groups, takes 7 seconds in v8.2.2)

we know this - we will improve on this for sure - it was important for us to have somehting useful for oc9

**Comment by DeepDiver1975** [comment]
> No button to create a new Contact Group

we generate the list of groups from the categories entries of all contacts - I'm not sure if we need to explicit generate a group

> Contact groups do not show up at all until I click on an individual contact

Can explain this more in detail - I dont get it - THX

> Starred contacts group does not exist anymore

Planned for the next releases.

> "Not Grouped" group does not exist anymore

True - @jancborchardt we need that?

> No longer able to add custom phone types (dropdown list with no "other" option available in the type dropdowns).

Planned

> At least one contact that had a picture pre-upgrade now shows a ? in the picture box.

Can you paste a screenshot? THX

**Comment by DeepDiver1975** [comment]
we might want to split this up into individual issues .....

**Comment by fracture-point** [comment]
> we generate the list of groups from the categories entries of all contacts - I'm not sure if we need to explicit generate a group

_Yes, users need to be able to create new groups._

> Contact groups do not show up at all until I click on an individual contact

_I navigate to contacts, and wait a few minutes until the list of contacts shows up (middle pane).  At this time, the left pane (groups) is still completely blank - which makes me think that I have lost all my groups.  If I click in the right pane (details), or left pane (groups), nothing changes.  If, however, I click on an individual contact (middle pane), now all my groups show in the left pane._

> "Not Grouped" group does not exist anymore
> True  - @jancborchardt we need that?

_This is a big feature for me to manage new contacts (who was that important person I met yesterday that I promised to follow up with??)_

> Contacts take minutes to appear (434 contacts in 16 groups, takes 7 seconds in v8.2.2)
> we know this - we will improve on this for sure - it was important for us to have somehting useful for oc9

_Currently the screen sits with "No contacts in here" displayed, and no indication of progress or background activity.  The old contacts app had spinners in both panes (groups and contacts).  We need something visual here so that people don't give up or freak out._

> should work better with #195 - please test - THX

_I pulled from origin master and then cherry-picked commit 668b4de622737dbbeed6a2c325c62be2c91c7865.  No changes to the UI issue with PREF and INTERNET.  Let me know if you'd like me to test differently._

Screenshot of contact with missing photo after upgrade:
![image](https://cloud.githubusercontent.com/assets/410707/13746922/12c01d9a-e9cc-11e5-8610-18301ebc8733.png)

Vcard of contact with many of the issues mentioned (numbers, name, etc. sanitized, renamed from .vcf to .txt):
[problematic_contact.txt](https://github.com/owncloud/contacts/files/172068/problematic_contact.txt)

As I browse through other issues, it looks like there is a significant amount of planned (temporary) regression in functionality.  I think this needs to be very clearly expressed on the docs pages so that people have this expectation coming in.

**Comment by DeepDiver1975** [comment]
> Screenshot of contact with missing photo after upgrade:
> image

Can I have that vcard as well? THX

**Comment by DeepDiver1975** [comment]
Any may I ask how many contacts you have in total? Just to have a realistic test number? ;-)

**Comment by fracture-point** [comment]
[contact-photo-missing.txt](https://github.com/owncloud/contacts/files/172130/contact-photo-missing.txt)

There are two things that make this different from some other contact photos:
1. The photo was added using the (now old) contacts interface, by clicking Upload new Photo.
2. The source image is larger than most (close to 1MB).  It appears that cropping in the old UI did not remove the rest of the image - it's more of a "focus frame"...so the image size was not reduced.

**Comment by fracture-point** [comment]
sure - it's at the top - 

> Contacts take minutes to appear (434 contacts in 16 groups, takes 7 seconds in v8.2.2)

**Comment by DeepDiver1975** [comment]
> sure - it's at the top -

thx - sorry - to many issues processing all day long :wink:

**Comment by fracture-point** [comment]
No prob!  Thanks for the help!

**Comment by DeepDiver1975** [comment]
@> Vcard of contact with many of the issues mentioned (numbers, name, etc. sanitized, renamed from .vcf to .txt):

Okay - the issue i related to the way the phone numbers are stored in the vcard

The label is store in a property of it's own and two properties are linked to each other - I'll create a new issue for this - https://github.com/owncloud/contacts/issues/204

```
ITEM2.TEL:+44 0-666-666-6666
ITEM2.X-ABLABEL:UK (Orange)
ITEM3.TEL;TYPE=PREF,T-Mobile:(222) 222-2222
ITEM3.X-ABLABEL:T-Mobile
ITEM4.TEL:(444) 444-4444
ITEM4.X-ABLABEL:Google Biz #
```

**Comment by DeepDiver1975** [comment]
> contact-photo-missing.txt

this is related to the X-ABCROP-RECTANGLE stuff - we fixed this a few days back ....

**Comment by fracture-point** [comment]
re: linked properties: 

I'm not sure which application stored it that way, but I suspect it was Google.

This contact was exported from Google, imported into OC, and then maintained (a few updates here and there) using OSX Contacts.  I don't think the attributes you reference have been changed since Google.

**Comment by DeepDiver1975** [comment]
> I'm not sure which application stored it that way, but I suspect it was Google.

afaik apple is doing this

**Comment by DeepDiver1975** [comment]
Current master and changes as of https://github.com/owncloud/contacts/pull/195 all together:

![bildschirmfoto von 2016-03-14 15-38-45](https://cloud.githubusercontent.com/assets/1005065/13747929/eaeca160-e9fa-11e5-8437-bce4da1a9ede.png)

**Comment by DeepDiver1975** [comment]
sorry for the German localization :wink:

**Comment by fracture-point** [comment]
ah, that is better

**Comment by DeepDiver1975** [comment]
> No button to create a new Contact Group

https://github.com/owncloud/contacts/issues/205

**Comment by DeepDiver1975** [comment]
> Starred contacts group does not exist anymore

#119

**Comment by DeepDiver1975** [comment]
> "Not Grouped" group does not exist anymore

https://github.com/owncloud/contacts/issues/206

**Comment by DeepDiver1975** [comment]
> No longer able to add custom phone types (dropdown list with no "other" option available in the type dropdowns).

https://github.com/owncloud/contacts/issues/207

**Comment by DeepDiver1975** [comment]
Anything related to initial loading performance is handled in https://github.com/owncloud/contacts/issues/176

**Comment by DeepDiver1975** [comment]
@fracture-point please double check if all your issues got addressed - I'd like to close this issue then an proceed in the individual issues - THX

**Comment by fracture-point** [comment]
@DeepDiver1975 this covers everything (ability to add custom types is in #207 ).

You may close this issue.  Thanks.
