### ISSUE TITLE
Link to addressbook partially inaccessible behind tool bar

### ISSUE THREAD

**Issue by skjnldsv** [owncloud/contacts#202]
The "link-share-delete icon" span is over the input when open. So half of the html element is unselectable.  

A very minor issue, but hey, that's the little things that matter :)
![capture d ecran_2016-03-14_13-27-08](https://cloud.githubusercontent.com/assets/14975046/13744593/133d7e8a-e9e9-11e5-8c54-be39a913dbeb.png)

Ps: congrats on the new app, good job, a lot remains to do, but looking great!

**Comment by Henni** [comment]
@jancborchardt can you take a look?

**Comment by jancborchardt** [comment]
Thanks a lot @skjnldsv! :) Great contribution, you are very welcome in our IRC channel #owncloud-contacts as well!

Also consider joining #owncloud-design as we always need more folks proficient with CSS and design. :)

**Comment by skjnldsv** [comment]
Thank you for the kind words! :)

**Comment by jancborchardt** [comment]
Of course! I’m always excited if there’s some other CSS/design folks around. :)
