### ISSUE TITLE
Type handling: allow the user to enter a custom type

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#207]
We can basically use select2 here as well.
But we need to think about multiple selection and the repesentation.

It should be possible to select HOME, VOICE, CELL, IPHONE from the dropdown - but how to display this nicely?

@jancborchardt

**Comment by DeepDiver1975** [comment]
maybe we start without multiple select and go for single selection and custom input

**Comment by gvde** [comment]
Maybe it helps to see a list of what various clients came up with:

https://github.com/owncloudarchive/contacts/issues/1044#issuecomment-141421267

and the following comments...

**Comment by DeepDiver1975** [comment]
> Maybe it helps to see a list of what various clients came up with:

nice - THX a lot!

**Comment by jancborchardt** [comment]
What do you mean by multiple selection? You can use multiple attributes for a phone number?

I thought this is only about adding a custom value. And that can be done with either select2 or our multiselect.js library.

**Comment by DeepDiver1975** [comment]
> What do you mean by multiple selection? You can use multiple attributes for a phone number?

there are combinations possible like HOME and CELL and IPHONE and TEXT and VOICE - which means: 'this is my private iphone used for text messaging and calls'

crazy - but this is all possible - some even add the carrier to the phone number like 'Vodaphone'

**Comment by jancborchardt** [comment]
Ok, while I know it’s cool to be tecnically correct and all – how about we look at how big players like Google Contacts, iCloud contacts and the Contacts apps on iOS and Android do it and model it after that? Otherwise we just implement lots of complicated logic for stuff people are neither used to nor will ever use.

**Comment by jancborchardt** [comment]
(Cause also here – I see plenty of other more important things than this. It will cost us lots of time and be a pain just for the questionably good feeling of being 100% compliant to a theoretical dreamworld spec.)

**Comment by DeepDiver1975** [comment]
> Ok, while I know it’s cool to be tecnically correct and all – how

Well - writing data into wrong field is simply a bug :wink: 

Android Contacts - has 4 fields in edit mode street, city, state, postal code - no idea where they put the others ....

**Comment by spoorun** [comment]
@jancborchardt I appreciate priorities. Though it must be said, the spec is not all dream world. It provides room for more advanced contact management (like for business vibrates). But just as importantly, specifying multiple types such as home & mobile or work & mobile, for example, is a very common use case. People with hearing challenges will also appreciate being able to specify phone types home & texttalk, or types pager & texttalk. Anyone who uses a fax<> email service would appreciate being able to direct email type work and fax. Anyone who uses SMS, or OwnCloud SMS would appreciate being able to specify which numbers (other than mobiles) can receive SMS ( e.g. Types Home & sms, or pager & sms). It helps users as described so they don't have to guess which number or email is which. but also it will enable other apps to make sensible use of the dates (like fax and texttalk apps) - only if we follow the spec. Another example is address, user wants to store two addresses for a contact, home and work, but also specify which one their mailmerge software should use for mailing...

**Comment by overlind** [comment]
I appreciated the ability to customize the type fields in past releases of Owncloud.  It has be quite an inconvenience to manually edit the VCARD info in the database each time I want to customize a field.  My use case is that use Owncloud as a contact directory.  Each card represents a family, so I need the ability to store multiple phone numbers and to identify whose cellphone some of the numbers are.  I use a customized Excel macro to convert the exported VCF file to an XLSX spreadsheet and perform a saved mail merge in Word to generate a printable directory.  Some Android phones display the customized type labels correctly while others do not.  I can't remember if iPhones do or not.  If the ability to customize the type fields could be restored (I really liked how easy it used to be to edit in the drop-down list), I would really appreciate that.
