### ISSUE TITLE
Contact sort/display order missing

### ISSUE THREAD

**Issue by ghost** [owncloud/contacts#208]
### Expected behaviour

There should be a way to sort the contact list/change the display order (like it was on oc 8.2 contacts app).

![kontakte_owncloud2](https://cloud.githubusercontent.com/assets/6527854/13748912/48c4cb56-e9ff-11e5-8710-101cbcbbcb73.png)

I was told this wasn't implemented yet, so no further information, I just created this ticket as a backlog.

**Comment by DeepDiver1975** [comment]
Thanks a lot!

**Comment by jancborchardt** [comment]
If we add it, let’s put that in the bottom left settings area though. And sorting by first name should be default.

**Comment by palegrand** [comment]
*_Please add this feature again! *_ In business last name is what I and most others are looking for.  
Would be a nice extra if the sorting order default could even  be saved per user...

**Comment by snaiperskaya96** [comment]
Implemented! Have a look at the referenced PR 😄
