### ISSUE TITLE
Multiple escaping in addresses

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/contacts#220]
### Steps to reproduce
1. Open ownCloud Contacts
2. Add new contact
3. Enter an address field (e.g. street) with commas
### Expected behaviour

The address should not break
### Actual behaviour

Any comma in an address field is escaped multiple times, so upon save (i.e. focus blur) "Main Street, 1st floor" is changed to "Main Street\, 1st floor". When the field is focused and blurred again, it changes to "Main Street\, 1st floor" and so on. There is some escaping going wild here.
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx

**Database:** MySQL 5.5

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "512fdebce061d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloud....\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_domain": "cloud.....",
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_domains": [
            "cloud....."
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome 48

**Operating system:** OS X 10.11

**CardDAV-clients:** iOS 9.2, OS X 10.11

**Comment by DeepDiver1975** [comment]
> Any comma in an address field is escaped multiple times, so upon save (i.e. focus blur) "Main Street, 1st floor" is changed to "Main Street\, 1st floor". When the field is focused and blurred again, it changes to "Main Street\, 1st floor" and so on. There is some escaping going wild here.

I have seen this on e.g. tel type as well - I suspect the vcard lib going wild :angry:

**Comment by skjnldsv** [comment]
The vcard vendor is good.
When loaded, the data is ok: https://github.com/Heymdall/vcard/blob/master/src/vcard.js#L56

We need to do the same replace in the model I think, so that we don't display the backslash on the view.

EDIT: it seems to only happen in the address fields.
![dsq](https://cloud.githubusercontent.com/assets/14975046/14072315/7ae697e8-f4bf-11e5-9a00-8c87ce122d46.png)

**Comment by skjnldsv** [comment]
Adding this to /js/components/detailsItem/detailsItem_controller.js seems to do the trick, but I'm not sure that is the best way.
It just correct a previous change made god knows where. So when you write a comma, the input still gets updated and your cursor still goes back at the end. Not really great!
However, this issue seems to only affect the Arrays data (like the address), the simple fields aren't affected.

```
$scope.$watch(function () {
        return ctrl.data;
    },
    function(newData, oldData) {
        if(Array.isArray(newData.value)) {
            for(var i in newData.value) {
                ctrl.data.value[i] = ctrl.data.value[i].replace(/\\,/, ',');
            }
        }
    }, true);
```

PS: I don't want to do a PR yet, I need some advice/reviews, I'm not used to angular.

**Comment by DeepDiver1975** [comment]
fix is here - https://github.com/Heymdall/vcard/pull/4

**Comment by skjnldsv** [comment]
Good job! :+1:
