### ISSUE TITLE
JS error when deleting group from contact

### ISSUE THREAD

**Issue by irgendwie** [owncloud/contacts#222]
Deleting a group out of a contact leads to a JS error:

`Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

![bug](https://cloud.githubusercontent.com/assets/8360698/13848401/e4103e7a-ec51-11e5-9425-715cdc25934a.png)

**Comment by DeepDiver1975** [comment]
@irgendwie still an issue?

**Comment by irgendwie** [comment]
Nope, seems to be fixed :+1:
