### ISSUE TITLE
Search matches wrong stuff

### ISSUE THREAD

**Issue by irgendwie** [owncloud/contacts#224]
![search_bug](https://cloud.githubusercontent.com/assets/8360698/13849895/3b026e46-ec58-11e5-8344-a72e03a8d46a.png)

**VCARD ist not the only wrong stuff, the search matches.**

**Comment by DeepDiver1975** [comment]
Okay - maybe matching the full vcard was a bit toooooooo radical

https://github.com/owncloud/contacts/blob/master/js/models/contact_model.js#L155
