### ISSUE TITLE
Contacts not showing after upgrade

### ISSUE THREAD

**Issue by matyas1995** [owncloud/contacts#225]
I upgraded my oc from 8.2.2 to 9 and the contacts app to 1.0.0.

Now none of the contacts can be seen in the contacts app, even though they are still in the database. CardDav clients can still sync, create and edit contacts. If I create a new contact in the contacts app, it only shows up in the list but cannot be edited in the app because no details are shown. When the page is reloaded it is not shown any more as well.

**Comment by DeepDiver1975** [comment]
Migration issues have to be reported in core - please use the issue template - THX
