### ISSUE TITLE
[Enhancement] contact folders

### ISSUE THREAD

**Issue by ITwrx** [owncloud/contacts#235]
It would be nice if users could create folders for contacts in the Contacts dialogue. Contacts could use the Files app in the background to do all the work, i would guess. This would just be a way for users to organize by contact/link contacts with folders without having to do it manually/directly in Files app. They should also be able to view the contacts' folders inside the profile for a contact even though Contacts is just pulling in the linked Files folders. 

In addition to custom fileds(#234) this would make contacts fairly flexible/powerful.

Thanks

**Comment by Henni** [comment]
@ITwrx vCards offer groups which we support and have a similar functionality to folders.
Contacts aren't stored as files on the server and thus cannot be managed by the files app.
