### ISSUE TITLE
Show first contact by default

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#24]
The content-detail view should always display a contact. On start, simply the first one in the list.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @Henni can you take care of this? I assume this is a quick fix, but it improves the UX sooo much. Otherwise always when you fire up the app the first thing you see is »No contacts in here« – which is simply wrong and also disconcerting, leading you to believe the data is gone …

**Comment by Henni** [comment]
fixed by #64

**Comment by jancborchardt** [comment]
@Henni doesn’t work on initial load or refresh yet. Related: https://github.com/owncloud/contacts/issues/72
