### ISSUE TITLE
owncloud contact as an libre office data source

### ISSUE THREAD

**Issue by janrudolf** [owncloud/contacts#240]
Guten Morgen, ;-)

I thought about the possibility to get the owncloud contacts get connected as a data source in libreoffice. Has anybody thought about this yet? But I guess, its more a question for libreoffice, isn't it?

I am excited about your ideas!

**Comment by gvde** [comment]
That's up to libreoffice and seems to be for a long time: https://bugs.freedesktop.org/show_bug.cgi?id=51969

**Comment by Henni** [comment]
This looks like it has to be fixed by libreoffice.
Thank you @gvde for referencing the bug.
