### ISSUE TITLE
Birthdays from shared addressbook not visible 

### ISSUE THREAD

**Issue by heikojansen** [owncloud/contacts#242]
I run an owncloud instance for my family. My wife and I both have a personal calendar and address book and in my account there is an additional calendar and an address book which I share with my wife.

In my contact app I have two address books ("Private" and "Shared").
In my calendar app I have three calendars; two ("Private" and "Shared") were created by me; one ("contact_birthdays") was apparently added by owncload automatically and is populated with the birthdays from the "Shared" address book (the "Private" address book is currently empty).

The contact app of my wife shows two address books ("Private" and "Shared(heiko)") and she can see and edit the contact data from "Shared(heiko)".
Her calendar app also shows two calendars ("Private" and "Shared(heiko)") and the appointments from the shared calendar are shown just fine.
There is, however, no separate birthday calendar and the birthday dates are not shown in her calendar view.

Note that I did run both "./occ dav:sync-birthday-calendar <me>" and "./occ dav:sync-birthday-calendar <wife>" but to no avail.

Since the calendars are shared I expect the birthdays to also show up in her calendar view.

I could not identify any possibly related error messages in the log so I tend to assume it´s not a problem but just unimplemented functionality?

I understand that both the calendar and contact apps are in really early stages of development feature- and ui-wise right now and that this might seem like a minor feature...

**Comment by heikojansen** [comment]
Just realized that this might not be the right place to report this issue, since it could also be an issue for the calendar app (or perhaps for the dav component in core). Feel free to close it and point me to the right place to open a new report...

**Comment by DeepDiver1975** [comment]
There is already an open issue in the core repo.
Thanks for reporting.
