### ISSUE TITLE
Export Addressbook

### ISSUE THREAD

**Issue by Henni** [owncloud/contacts#248]
Add option to export an addressbook with all its contacts.

**Comment by jancborchardt** [comment]
Yes! This is quite important regarding our principle of data portability.

**Comment by DeepDiver1975** [comment]
The Backend is already providing this feature.
We need to trigger the download only in the web ui.

**Comment by skjnldsv** [comment]
@DeepDiver1975 do you know how the backend is providing this? What is the url for the download?
The contacts are https://domain.ext/remote.php/dav/addressbooks/users/USER/ADDRESSBOOK/UID.vcf, but can't figure out for addressbooks :)

**Comment by DeepDiver1975** [comment]
the correct url is  https://domain.ext/remote.php/dav/addressbooks/users/USER/ADDRESSBOOK?export - but we need to fix core first - https://github.com/owncloud/core/pull/23893

**Comment by skjnldsv** [comment]
You're awesome! :)
:+1:

**Comment by DeepDiver1975** [comment]
addressbook export will be part of 9.0.2 - https://github.com/owncloud/core/pull/23897

@skjnldsv we better have a version check to see if addressbook export is enabled or not

**Comment by skjnldsv** [comment]
Okay! 
On it!

**Comment by captainwasabi** [comment]
I need this too!!! I have applied owncloud/core#23897 by hand.  Waiting for client side.

Oops, never mind.  Clicked the wrong button and deleted the whole address book! :(  Might I suggest perhaps a confirmation dialog before two days work of hand entering addresses is destroyed?  Oops, too late it's gone. ;)

**Comment by skjnldsv** [comment]
It's planned  too!
