### ISSUE TITLE
[Feature request] An option to add notes

### ISSUE THREAD

**Issue by dniku** [owncloud/contacts#249]
Currently, the contact notes exported from Google are displayed, but new ones cannot be added.

![image](https://cloud.githubusercontent.com/assets/1315874/13906316/6e5e060e-eee4-11e5-81a5-354ac4f52fde.png)

Please add "notes" as an option to the list of contact fields.

**ownCloud version:** 9.0.0

**Contacts version:** 1.0.0.0

**Updated from an older ownCloud or fresh install:** updated from 8.2.2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.
### Client configuration

**Browser:** Chrome 49.0.2623.87 (64-bit)

**Operating system:** Gentoo Linux

**Comment by Henni** [comment]
I cannot reproduce this.
For me there is an entry "Notes" in the "Add field" dropdown.

**Comment by irgendwie** [comment]
Can't reproduce this either.

**Comment by dniku** [comment]
I must have only taken a look at this dropdown list in a contact which already had a note added. Sorry for the disturbance.

**Comment by irgendwie** [comment]
@Pastafarianist Don't worry, thanks for reporting the issues! They are very helpful!
