### ISSUE TITLE
OC9 - total number of records in address book missing

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#252]
## Expected behavior

When opening the contacts app the total number of records in an address book should
be shown as it has been done in the OC8 Contacts app.
## Current behavior

When opening the contacts app the total number of records in an address book is missing.

![2016-03-21 09_19_35-kontakte - owncloud](https://cloud.githubusercontent.com/assets/2572764/13913448/0be707d8-ef47-11e5-98bc-5c54576d4089.jpg)
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.0.0 (20160320)
Updated from OC8.2.2
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
I'd like to postpone this until we have restructured the client-server interaction - we need to move away from the load-all-contacts concept first - then we can see how to collect such information

**Comment by irgendwie** [comment]
Fixed by #453.
