### ISSUE TITLE
OC9 - field labels in address record missing or overlapped

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#254]
## Expected behavior

All fields of an address book entry should be labled with a label and a separate type selection. 
## Current behavior

When selecting an address book entry several field labels are missing or maybe overlapped
by a type drop-down, which unfortunately couldn't handle multiple types too.

![2016-03-21 09_19_35-kontakte - owncloud](https://cloud.githubusercontent.com/assets/2572764/13913646/25b1aed2-ef49-11e5-92e7-e838cab6dab8.jpg)
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.0.0 (20160320)
Updated from OC8.2.2
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by gvde** [comment]
This is a dup of #173...

**Comment by irgendwie** [comment]
This issue was fixed with with PR #195.
@Henni We need nightly builds or a new version in the app store. :rocket:
