### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by Henni** [owncloud/contacts#256]
We need nightly builds!
They would enable testing of new features without having to set up npm, bower, etc.

**Comment by irgendwie** [comment]
@enoch85 You are doing nightly builds for owncloud/mail or not? Are you interested in also providing nightly builds for owncloud/contacts? :blush:

**Comment by DeepDiver1975** [comment]
We can create a nightly tag which will trigger releasing to github

**Comment by tsumi** [comment]
Hi, just for information, is there a manual about how build the package?
Thanks

**Comment by enoch85** [comment]
@irgendwie I could provide for contacts as well, but it seems like @DeepDiver1975 have a better soulution.

**Comment by DeepDiver1975** [comment]
the first automated tag - https://github.com/owncloud/contacts/releases/tag/v0.0.0.7
