### ISSUE TITLE
Can't select an adress book

### ISSUE THREAD

**Issue by etiennerunge** [owncloud/contacts#264]
Hi there, 

So, problem is in Contacts App, when I create an adressbook. I can't select an adressbook, it doesn't appear in adressbooks column. I can find it in settings, but can't see it and can't add addresses in it.
This issue is repported  by _onecloud_ on: Mar 14 2016 at https://apps.owncloud.com/content/show.php/Contacts?content=168708 too.

Thanks
### Server configuration

**Operating system**:
Debian 8 Jessie
**Web server:**
nginx/1.6.2

**Database:**
mysql  Ver 14.14 Distrib 5.5.47

**PHP version:**
PHP 5.6.17

**ownCloud version:** (see ownCloud admin page)
OwnCloud v9
**Contacts version:** (see ownCloud apps page)
v1.0.0.0
**Updated from an older ownCloud or fresh install:**
fresh install
**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
- activity: 2.2.1
- announcementcenter: 1.1.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.0.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- music: 0.3.10
- notifications: 0.2.3
- ownnote: 1.07
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- news
- user_external
- user_ldap

**Comment by irgendwie** [comment]
Duplicate of #178

Currently it is not possible to select which addressbook is to be shown. (Still, this is a planned feature)
But you can change in which addressbook a contact is saved by looking into the details of a contact and changing the value of the addressbook.
When only one addressbook is available, that option is not changeable as it doesn't make much sense. :wink:

**Comment by etiennerunge** [comment]
Oh ok, thanks ! 
The field used to save a contact in address book is the field named "Groups" ? (in french : "Groupes"). Is it correct ? Because it doesn't autocomplete the field.
Thanks ;)
