### ISSUE TITLE
[Enhancement] Separate fields for first name, last name lost in new GUI

### ISSUE THREAD

**Issue by nWRqenkF** [owncloud/contacts#265]
### Steps to reproduce
1. Open new contacts gui
2. Open any contact
### Expected behaviour

In the old contacts gui (and in most contact clients I know, e.g. android contacts app, thunderbird, outlook) there are separate fields for first name and last name. at least as a detail dialogue 
### Actual behaviour

Only a single input field for name exists
### Server configuration

**Operating system**: Debian Wheezy

**Web server:** nginx

**Database:** MySql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Contacts version:** (see ownCloud apps page) 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2 from official apt-repositories
### Client configuration

**Browser:** Firefox 44.0

**Operating system:** Windows 7

**CardDAV-clients:** DavDroid

**Comment by hubgitti** [comment]
An option to sort the contacts by last name would be nice also. Currently my contacts are sorted by first name. (OC 9.0.1, Contacts 1.1.0.0)

**Comment by aspdye** [comment]
https://github.com/owncloud/contacts/issues/324

**Comment by phsc84** [comment]
Shouldn't this issue be fixed with #437?
