### ISSUE TITLE
Enhancement: Link Facebook or other Profiles with Contacts

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#270]
- Profile Pictures (Import and Sync with Facebook, Twitter, Google+, Diaspora, ...)
- Links to Profiles 
- Import Contact Details (Birthdays, ...) from Profiles like Facebook, Twitter, ...
- Import whole Contacts

**Comment by skjnldsv** [comment]
For the profile pic & birthdays, there is an app available: https://apps.owncloud.com/content/show.php/FbSync?content=174311

**Comment by DeepDiver1975** [comment]
We should add this to the Import issue and close this one
