### ISSUE TITLE
[Enhancement] Provide date picker for birthday

### ISSUE THREAD

**Issue by nWRqenkF** [owncloud/contacts#273]
### Expected behaviour

The birthday field should provide a date picker
### Actual behaviour

Simple text input field
### Server configuration

**Operating system**: Debian Wheezy

**Web server:** nginx

**Database:** MySql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Contacts version:** (see ownCloud apps page) 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2 from official apt-repositories
### Client configuration

**Browser:** Firefox 44.0

**Operating system:** Windows 7

**CardDAV-clients:** DavDroid

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2016-03-24 14-10-45](https://cloud.githubusercontent.com/assets/1005065/14017793/3a061296-f1ca-11e5-83a1-cb898aaa32d7.png)

**Comment by DeepDiver1975** [comment]
Already there - will soon be published
