### ISSUE TITLE
Birthday field should provide error message for illegal formats

### ISSUE THREAD

**Issue by nWRqenkF** [owncloud/contacts#274]
### Steps to reproduce
1. Create a new contact
2. Add field "Birthday"
3. Enter "31.01.2001"
4. Focus on any other contact field
5. Select any other contact and then the newly created contact
### Expected behaviour

At least after step 4 the ui should provide an error message, that the entered format is illegal and/or that the expected format ist 2001-01-31
### Actual behaviour

After step 4 nothing happens.
After step 5 the entered birthday is lost silently.
### Server configuration

**Operating system**: Debian Wheezy

**Web server:** nginx

**Database:** MySql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Contacts version:** (see ownCloud apps page) 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2 from official apt-repositories
### Client configuration

**Browser:** Firefox 44.0

**Operating system:** Windows 7

**CardDAV-clients:** DavDroid

**Comment by DeepDiver1975** [comment]
there is a date picker in place already
