### ISSUE TITLE
Birthday dates reduced by one day

### ISSUE THREAD

**Issue by robertwenner** [owncloud/contacts#277]
### Steps to reproduce
1. Add a new contact, enter a name
2. Add birthday field, enter e.g., 2000-01-01
3. Click on another contact, then go back to the new contact

This also seemed to happen with all my exiting contacts. Maybe it's a matter of displaying the date vs actually storing the wrong date?
### Expected behaviour

Birthday should be 2000-01-01
### Actual behaviour

Birthday is 1999-12-31
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic i686)

**Web server:**
Apache2

**Database:**
mysql Ver 14.14 Distrib 5.5.37, for debian-linux-gnu (i686) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4 (cli) (built: Apr 9 2014 17:08:27)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Contacts version:** (see ownCloud apps page)
 Contacts 1.0.0.0

**Updated from an older ownCloud or fresh install:**
Upgrade from latest 8

**Signing status (ownCloud 9.0 and above):**

```
Not Found

The requested URL /index.php/settings/integrity/failed was not found on this server.
Apache/2.4.7 (Ubuntu) Server at media.olalmaro Port 80
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - bookmarks
  - encryption
  - external
  - files_external
  - search_lucene
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc62a90a0174",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "media",
            "media.local",
            "media.olalmaro"
        ],
        "datadirectory": "\/home\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "forceSSLforSubdomains": true,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
none
### Client configuration

**Browser:**
Firefox 46 or Ubuntu 14.04.4 LTS

**Operating system:**
Ubuntu

**CardDAV-clients:**
Browser only

**Comment by DeepDiver1975** [comment]
we have a datepicker in place meanwhile which should help to prevent incorrect data entry

![bildschirmfoto von 2016-03-24 14-10-45](https://cloud.githubusercontent.com/assets/1005065/14031945/b84e702c-f20f-11e5-96c9-6ae41e83c8c1.png)

**Comment by robertwenner** [comment]
> we have a datepicker in place meanwhile which should help to prevent incorrect data entry

I don't understand what you are trying to say here. Looks like ISO 8601 format is accepted, from both what your picture show and what I tried. (At least I did not get an error message.) So I am not sure how a date picker would make a difference here.

That said, my owncloud does not offer a date picker. Did you mean that the date picker will be available in a future version?

Also note that existing birthdays (from Owncloud 8) have also been modified by one day.

**Comment by DeepDiver1975** [comment]
oh - sorry - I missinterpreted your report.

**Comment by DeepDiver1975** [comment]
The Datepicker is part of 1.1.0.0 which was pushed to the appstore yesterday

**Comment by irgendwie** [comment]
Not reproducible for me. :-1:

**Comment by robertwenner** [comment]
Would a short screencast help? I guess you still wouldn't be able to reproduce it, but at least it would show that I am not totally crazy ;-)

**Comment by robertwenner** [comment]
Problem went away after upgrading to 9.0.1

**Comment by aspdye** [comment]
...the question is: why 💭
