### ISSUE TITLE
contacts v1.1.0.0 - contact groups are not displayed anymore

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#281]
## Expected behavior

When opening the contacts app the available contact groups should be shown in the left
column.
## Current behavior

After upgrading the contacts app from v1.0.0.0 to v1.1.0.0 no contact groups at all are
displayed anymore when opening the contacts app.

![20160325_contact_groups_missing](https://cloud.githubusercontent.com/assets/2572764/14044403/8de66d7c-f290-11e5-9e24-831b404b4cd1.jpg)
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.1.0.0
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by irgendwie** [comment]
Thanks @j-ed for reporting - are there any errors in the console?

**Comment by skjnldsv** [comment]
Can't reproduce here. Strange.

**Comment by j-ed** [comment]
I've enable the debug logging but nothing is logged when I open the contacts app.

**Comment by irgendwie** [comment]
The app is just a javascript frontend - maybe something in the Javascript console?
(https://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers/77337#77337)

**Comment by j-ed** [comment]
I've now tested it with a brand new FF profile and the contact groups are displayed properly, although starting FF with my usual profile didn't show it. I've then cleared the temporary file cache and restarted the browser and now the categories are shown again.
Sorry for having rung the bell on this but in the past it had worked without clearing the local FF file cache.

**Comment by irgendwie** [comment]
Np mate, nonetheless a weird issue :smile:
