### ISSUE TITLE
contacts v1.1.0.0 - impossible to assign name details to the right fields

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#283]
## Expected behavior

When editing a contact it should be possible to edit the name details, like title, first, middle
and last name of a contact as in the previous contact app to make sure that the information
is assigned to the right fields.
## Current behavior

It isn't possible to edit the name details separately anymore, instead only one single name line
is shown in the contact header record. This makes it impossible to assign the entered information
to the right fields.

| title | First name | Middle name | last name |
| --- | --- | --- | --- |
| Herr | Hans |  | Schmid |
| Herr | Hans Werner |  | Schmidt |
| Mr. | Bob |  | Jones |
| Mr. | Bob | John | Jones |
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.1.0.0
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
Known issue. Thx

**Comment by b3** [comment]
Why is this issue closed, since it is not fixed yet?

**Comment by b3** [comment]
OK found an open bug #324.
