### ISSUE TITLE
contacts v1.1.0.0 - company and job role information almost impossible to read

### ISSUE THREAD

**Issue by j-ed** [owncloud/contacts#286]
## Expected behavior

When editing and/or displaying the contact details, the company and job role information should
be shown in full length, one per line.
## Current behavior

The company and job role information is cropped and displayed in a single line which makes it
almost impossible to read it correctly. There is sufficient space on a desktop PC or tablet PC screen
and no need to crop the information.

Current layout:
![20160325_contact_details_cropped](https://cloud.githubusercontent.com/assets/2572764/14045794/5cdaa89e-f29d-11e5-9d5c-0550e125aff8.jpg)

Desired layout:
![20160325_contact_details_cropped-2](https://cloud.githubusercontent.com/assets/2572764/14045803/6aec86be-f29d-11e5-9219-f3450d15d8d5.jpg)
#### Server Configuration

OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.1.0.0
#### Client Configuration

Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
Nice idea. @jancborchardt

**Comment by jancborchardt** [comment]
Sorry, but no. This takes way too much focus away from the name and clutters everything up visually.

I would be fine with making the fields wider, yes. But not a line for each. No other field is soo wide.

**Comment by sorglos** [comment]
Please leave enough space for department and group.

RFC: ORG
> To specify the organizational name and units associated with the vCard.
> …
> A single structured text value consisting of components separated by the SEMICOLON character.

`ORG:ABC\, Inc.;North American Division;Marketing`

(It's separate issue but please don't escape the semicolons between the organizational units!)
