### ISSUE TITLE
No coverage displayed on codecov.io

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#288]
https://codecov.io/github/owncloud/contacts

**Comment by Henni** [comment]
This might be because we test `public/script.js` which isn't part of the repository.
We could change it to test the source files instead of the concatenated file.

**Comment by DeepDiver1975** [comment]
Nice idea. Are you preparing a PR?

**Comment by Henni** [comment]
I'm on it

**Comment by DeepDiver1975** [comment]
:+1:
