### ISSUE TITLE
Import of vcf file incl. multiple contacts does not work

### ISSUE THREAD

**Issue by rakekniven** [owncloud/contacts#291]
### Steps to reproduce
1. Open my productive ownCloud v8.2.3 and export all my contacts (about 400) to vcf file. 
2. Opem my testing ownCloud v9.0.1 beta 1 with contacts app v1.1.0.0
3. Open import dialog and select vcf file
4. Nothing happens
### Expected behaviour

Contact should be imported
### Actual behaviour

Nothing happens. No spinning wheel, no dialog, no log entries
### Server configuration

**Operating system**: Ubuntu 14.04.4 LTS

**Web server:**
Apache 2.4.7

**Database:**
MySQL 5.6.28

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.0.1 beta 1

**Contacts version:** (see ownCloud apps page)
1.1.0.0

**Updated from an older ownCloud or fresh install:**
fresh install using vm of tech and me

**Signing status (ownCloud 9.0 and above):**
no result. Header says "notification failed"

**List of activated apps:**
![bildschirmfoto 2016-03-25 um 17 42 47](https://cloud.githubusercontent.com/assets/2069590/14048814/0b2d9722-f2b1-11e5-9b06-3f191a903e11.png)

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
firefox 45
**Operating system:**
os x 
**CardDAV-clients:**
#### Web server error log

nothing
#### ownCloud log (data/owncloud.log)

nothing

**Comment by tomneedham** [comment]
Anything in the web browser console?

**Comment by tomneedham** [comment]
Are you able to check with another .vcf file to check that import is working on your install. I can import from OSX Contact. Just exporting from OC like you and will try import.

**Comment by rakekniven** [comment]
Web browser console does not contain any entry. Cleared after loading page. 
Started import action and nothing is in.
Also tried to import another vcf. Small one containing just one single contact. Same behaviour.

Just did same action for some of my calendars and that worked pretty well.

What else can I provide?

**Comment by tomneedham** [comment]
Ah I can now reproduce this in Chrome - however it is working in Safari for me.

**Comment by ghost** [comment]
Failed for me too. I made a fresh installation based on ubuntu 14.04 lts, php 5.6, mysql and ownCloud9.
Neither a new created single-vcf nor my exported multi-vcf (271 items from ownCloud 8.2.3) will be imported. The Import-Dialouge disappeard after selecting the file without any errors. As well no error- or log-entries can be found. May i assist you with reproducing this behaviour or anything else? ...carsten
Browsers: Firefox 45.0.1 Windows 10 Pro x64, Microsoft Edge

**Comment by Henni** [comment]
@criegerde Can you share the vcf files with us?

**Comment by ghost** [comment]
for sure...please find attached the single vcf
appologize, i made an incorrect information:about my php
my correct PHP Version: 5.5.9-1ubuntu4.14
[criegerde.zip](https://github.com/owncloud/contacts/files/190072/criegerde.zip)
i could also provide an account and login to my environment?

**Comment by TecJon** [comment]
I experienced the same error. 
However, when reloading now I get this Browser error log and a never ending spinning wheel. 

```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.0/$rootScope/inprog?p0=%24digest
https://example.com/apps/contacts/js/vendor/angular/angular.js?v=1267b7c6317f61b272e7e1ca22ea87e8
Line 68
```

### Steps to reproduce
1. Select .vcf file created by an Android 5 device in the contacts import window
2. Hit Open

### Expected behaviour

See progress of upload and import process.
List of imported contacts.

### Actual behaviour

Nothing. No Spinning wheel, empty contacts as if the import button was never hit.
Page reload nothing happens.
Firefox:
Now, when reloading, spinning wheel is shown and the browser error below.
Chrome:
Just empty contacts page and error in browser log

### Server configuration

**Operating system**:
Ubuntu 14.04 
**Web server:**
nginx
**Database:**
MySQL
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (fpm-fcgi) (built: Oct 28 2015 01:38:24)
**ownCloud version:** (see ownCloud admin page)
9.0.0.19
**Contacts version:** (see ownCloud apps page)
1.1.0
**Updated from an older ownCloud or fresh install:**
upgrade
**Signing status (ownCloud 9.0 and above):**
good

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc8ab27a8968",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "example.com",
        "maintenance": false,
        "theme": "",
        "forceSSLforSubdomains": true,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached"
    }
}
```

**Are you using external storage, if yes which one:** 
no
**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** 
no

### Client configuration

**Browser:**
Firefox 45
**Operating system:**
Windows 10 64Bit
**CardDAV-clients:**
none

### Logs

#### Browser log

Firefox:

```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.0/$rootScope/inprog?p0=%24digest
https://example.com/apps/contacts/js/vendor/angular/angular.js?v=1267b7c6317f61b272e7e1ca22ea87e8
Line 68
```

Chrome:

```
Failed to parse SourceMap:
https://example.com/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js.map
```

**Comment by urbenlegend** [comment]
I have the same issue with owncloud 9 and Contacts 1.1.0.0. Chrome and Firefox can't import a VCF file, but Safari can.

**Comment by DarkSteve** [comment]
I'm having the same issue with a fresh install of ownCloud 9, Contacts 1.1.0.0, MySQL 5.6, PHP5.6, and Apache2.4. After choosing the VCF file, nothing happens, no response, no errors, no importing.

On Win 10 I can't import via IE11, Edge, Seamonkey, or Pale Moon. On Win7 I can't import via IE11 or FF38. On Cyanogenmod11 I can't import via Pale Moon, Fennec, or the built-in browser.

I'm guessing the devs all use Macs ;-)

**Comment by TecJon** [comment]
@DarkSteve I've been wondering the same thing as I can't get the import feature working at all. Not on production cloud not on testing cloud with multiple browsers and file types (.vcf, .csv, .ldif). I even went ahead and tried the iOS Safari browser on my phone, wouldn't work there either.

**Comment by DarkSteve** [comment]
Has this bug been assigned to anybody? Is it planned to be patched for the 1.2 milestone? Any feedback on timeframes?

I can't code to save my life, otherwise I'd volunteer. But this bug is extremely inconvenient. I'll either have to re-type ~100 contacts (then wait until I can add photos) or wait until I can import my old vcf. Either way I have to wait to get back to what I had in previous ownCloud versions.

**Comment by DeepDiver1975** [comment]
The next Version will have a better importer.
Until then: connect any carddav client and import from there.

**Comment by DarkSteve** [comment]
Thanks DeepDiver, I will try another carddav importer.

I mainly use contacts via the ownCloud web interface or on my phone. While the contacts are currently in my phone, Carddav Sync Free won't allow me to edit the URL to reconnect to ownCloud 9.0 ("Failed to launch Activity" when I hit edit) and any new account won't contain the contacts.

I'll have to find a desktop carddav client and go from there.

**Comment by ghost** [comment]
I'm on OS X and I can't either upload my vcf file to OC9.0.1 it always creates {{ as Names and does not save the contacts. I'll lose them overtime when I change the site.
I tried to reproduce it with 8.2.3 and there, exactly the same vcf file works and the contact will be imported.

**Comment by DeepDiver1975** [comment]
> I'm on OS X and I can't either upload my vcf file to OC9.0.1 it always creates {{ as Names and does not save the contacts. I'll lose them overtime when I change the site.
> I tried to reproduce it with 8.2.3 and there, exactly the same vcf file works and the contact will be imported.

please open a new issue in here - sounds like a real issue we need to work on - THX

**Comment by eppfel** [comment]
I can confirm the issue for Chrome.

No reaction in Chrome after .vcf import with 400 cards (nothing in the console either), but worked out in Safari 9.1.
Mac OSX 10.10.5
ownCloud 9.0.1
Contacts 1.1.0.0

**Comment by sectorchan** [comment]
I tried over TOR, nothing happen, but the "import" if you would like to call it gets performed, only with the "restriction" of the names and not saving.

**Comment by bobblkabb** [comment]
Same here (Firefox 45 ).

**Operating system:**
Ubuntu 14.04.4 LTS
**Web server:**
Apache 2.4.7
**Database:**
MySQL 5.5.47
**PHP version:**
5.5.9
**ownCloud version:**
9.0.1
**Contacts version:**
1.1.0.0

Updated from an older ownCloud version (8.2.3). Contacts were exported from contactplus

**Comment by DeepDiver1975** [comment]
1.2.0.0 will be much better with this respect - I successfully imported a vcard with 2000 contacts.
