### ISSUE TITLE
contacts 1.1.0.0 import button

### ISSUE THREAD

**Issue by gpgmailencrypt** [owncloud/contacts#292]
should the newly introduced import button work in 1.1.0.0 under owncloud 9?
In my case it opens a file window to select the import file (a former  oc 8.2 exported addressbook) but then nothing happens. Neither the contacts will be imported nor any message in owncloud.log will be displayed.

**Comment by tomneedham** [comment]
Duplicate of https://github.com/owncloud/contacts/issues/291 please continue discussion there.
