### ISSUE TITLE
Provide a uniform way to build the app (fetch libraries and compile assets)

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/contacts#296]
Since most apps now don't bundle compiled JavaScript/CSS and vendor libraries (bower/npm/composer), it got a lot harder to update and develop on a version from git.

What I'm proposing is to provide a uniform interface for all apps (will later also add this to ocdev templates) which follows the very well known Makefiles from other projects:

Building the whole project (fetching 3rdparty libs, minifying JavaScript and CSS):

```
make
```

Running all tests:

```
make test
```

Creating appstore and source packages:

```
make dist
```

Deleting build directories:

```
make clean
```

Deleting build directories and vendor libraries:

```
make distclean
```

Everything related to JavaScript should be [done via npm scripts](https://docs.npmjs.com/misc/scripts). I don't want to read up which test and build tools are used (grunt, gulp, broccoli? dont care) and neither which package managers (bower, npm, jspm, ied? dont care).

Fortunately you can encapsulate that pretty well with npm scripts:

The following command should fetch all JavaScript libraries and build the minified JavaScript:

```
npm run build
```

The following command should run all JavaScript tests:

```
npm run test
```

Ideally no node packages need to be installed globally since this can be a pain, especially on servers. Just use the relative path to your locally installed node_modules. Here's an example how this should be carried out: https://github.com/owncloud/news/blob/master/js/package.json#L6

I've written a generic Makefile which should be reusable for every app (with maybe very minor adjustements): https://github.com/owncloud/news/blob/master/Makefile

Let me know if you are interested and how your build process looks like, then I can prepare a PR

**Comment by DeepDiver1975** [comment]
I honestly think that the way apps are developed is individual to each project and developer.

All which we need to take care of - from a developer perspective - is that the development process is described somehow - ideal in the readme.

I really don't want to force any methodology upon anybody.

**Comment by BernhardPosselt** [comment]
Sure but this becomes quite a pain when you want to update/build more than one app ;)

I'm running git versions of multiple apps on my own server and reading into all readmes and creating separate build scripts seems a waste of time. 

The most important thing for me is a uniform way to build it, the rest is just stuff that can be free (if generated by ocdev)

**Comment by BernhardPosselt** [comment]
Uniform entry point would probably be a better wording. You can run any package managers and build tools you want, as long as the package can get built by simply running make ;)
