### ISSUE TITLE
German translation for Home should be changed to Privat

### ISSUE THREAD

**Issue by thorsten19** [owncloud/contacts#302]
**Expected behaviour**
German translation for 'Home' should be 'Privat' 
Privat is used for other systems allowing CardDav sync (i.e. Android, iOS).
Tried to find/fix this on transifex but there translation for Home is shown as Home. Could not find how to fix it there.

**Actual behaviour**
German translation for 'Home' is 'Zuhause' (same was the case for Contacts used in Owncloud 8.2).
Besides the strange translation the current word is not displayed in full next to the fields (i.e. Address – there 'Zuhaus' is displayed).

**Server configuration**
Operating system: Raspbian GNU/Linux 8 (jessie)
Web server: Apache
Database: MySql
PHP version: 5.5.44
ownCloud version: (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** Fresh install
Client configuration
Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by skjnldsv** [comment]
I think the translation is only done via transifex :)

**Comment by DeepDiver1975** [comment]
Yes - change it on transifex

**Comment by thorsten19** [comment]
Thanks. Requested to be added to the owncloud translation group for German and once I get approved I'll change it there.

**Comment by skjnldsv** [comment]
Can we close the issue then?

**Comment by DeepDiver1975** [comment]
> Requested to be added to the owncloud translation group for German and once I get approved I'll change it there.

accepted - thanks a lot!

**Comment by thorsten19** [comment]
Thank you @DeepDiver1975. Translation has been updated
