### ISSUE TITLE
Enhancement: Delete Addressbook should display confirmation dialog

### ISSUE THREAD

**Issue by thorsten19** [owncloud/contacts#303]
**Steps to reproduce**
1. Open Contacts and click on Settings
2. A click on the trash bin icon deletes the addressbook right away

**Expected behaviour**
Deleting the addressbook should display a confirmation dialog. Else the addressbook is gone without a way to undo this significant action.

**Actual behaviour**
Deliting the addressbook deleted the same right away.

**Server configuration**
Operating system: Raspbian GNU/Linux 8 (jessie)
Web server: Apache
Database: MySql
PHP version: 5.5.44
ownCloud version: (see ownCloud admin page) 9.0.0
Contacts version: (see ownCloud apps page) 1.1.0.0 

**Updated from an older ownCloud or fresh install:** Fresh install
**Client configuration**
Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
We better go for the undo feature

**Comment by DeepDiver1975** [comment]
See #201
