### ISSUE TITLE
[Design] Add Letter in contact header too

### ISSUE THREAD

**Issue by skjnldsv** [owncloud/contacts#307]
I find the header incredibly empty, especially without picture.
Do you think this is a good Idea?

![alice](https://cloud.githubusercontent.com/assets/14975046/14064301/be900b62-f3fe-11e5-95d9-18482034f502.png)

**Comment by skjnldsv** [comment]
@Henni @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
I like that

**Comment by jancborchardt** [comment]
I see some problems with this:
- It duplicates a meaningless placeholder which already is in the Contact list itself.
- The color of the top bar should be the same as the background color of the avatar circle. So there would need to be 2 colors to even have the circle show up. That’s too much.
- Since the name is aligned with the fields below, I don’t find it much of an issue.

I would say that when there’s no profile picture set we don’t show anything for now. As soon as we implement the functionality, an upload icon.

**Comment by skjnldsv** [comment]
The colors don't seems to be an issue for me as it is just a simple design, and having a darker tone doesn't really make it that different.
But I agree with you for the image uploader. When the uploader will be operational, we would have to remove the first letter and replace it by an upload icon.

**Comment by Henni** [comment]
@jancborchardt what should this upload icon look like?
It would be great if you or @skjnldsv could implement it, so that I have a starting point to implement the image upload.

**Comment by jancborchardt** [comment]
The upload icon would simply be the icon `.icon-upload` in a white lined circle. (`border: 1px solid #fff; border-radius: 50%;`)

**Comment by jancborchardt** [comment]
Oh and btw, my vision for the header bar for the future is that when there is a profile picture, a blurry bigger version of it could show as background in that bar. Do you know what I mean? (Lotsa profile pages do that.)

**Comment by skjnldsv** [comment]
I know perfectly, the idea is good, we'll see what we can do :)

For the upload button: (?)
![feds156](https://cloud.githubusercontent.com/assets/14975046/14111034/5ea90466-f5c9-11e5-89e0-e1efa43d8160.png)

**Comment by jancborchardt** [comment]
Yeaah, nice! I just realized though that I need to update the upload-white icon in core because this is still the old version. :D

**Comment by skjnldsv** [comment]
@Henni should we start a branch for the image uploader? And then I could add the missing-avatar-upload div so you could start working on it?

**Comment by Henni** [comment]
@skjnldsv :+1:

**Comment by jancborchardt** [comment]
Yeah, go for it!

**Comment by skjnldsv** [comment]
@Henni https://github.com/owncloud/contacts/tree/avatar-upload-form
Here you go! \o/
![contacts owncloud](https://cloud.githubusercontent.com/assets/14975046/14148014/1f728d8c-f69e-11e5-85c6-c061d8868a4b.png)

**Comment by Henni** [comment]
@skjnldsv nice thanks!

**Comment by jancborchardt** [comment]
@skjnldsv can you open a work-in-progress pull request with the upload icon so it's more visible than a branch? Then @Henni can continue work in there.

**Comment by skjnldsv** [comment]
Of course, in return, please review my last pr! ;)
