### ISSUE TITLE
Some characters make contacts load forever

### ISSUE THREAD

**Issue by ghormoon** [owncloud/contacts#311]
Some characters (like 0x0c) make contacts load forever (spinning wheel).
The same contacts were working in 8.2.2, after upgrade to 9.0.0 (and later to 9.0.1 beta), contacts of one user stopped working - I've managed to export them using seamonkey and pinned down one of the broken ones. Except that, there are still some I can't even export and some of these are broken too.
Best I got after fixing the 0x0c is that I reimport the working ones (962/1024) to another user and they display (with broken diacritics etc. but that might be my export problem)

[example.vcf.txt](https://github.com/owncloud/contacts/files/193120/example.vcf.txt)
### Steps to reproduce
1. import user with 0x0c in description (example vcf attached)
2. user displays
3. reload page - spinning wheel forever
### Expected behaviour

User displayed correctly
### Actual behaviour

Loading forever
### Server configuration

**Operating system**: Debian jessie

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.1 beta

**Contacts version:** (see ownCloud apps page) 1.1.0.0

**Updated from an older ownCloud or fresh install:** upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** enabled, no errors
### Logs

nothing showing up when loading forever

**Comment by DeepDiver1975** [comment]
Looks like a parsing issue in the vcard.js library

**Comment by DeepDiver1975** [comment]
... no .. its the dav library

@irgendwie have fun :wink:

**Comment by ghormoon** [comment]
I may try to pin down other corrupted entries too, but I'm not sure if I can safely delete/insert in oc_card or if I'll break things that way. If you're interested in more, I may try it out in cloned database.

**Comment by ghormoon** [comment]
I've just tested it, it helped on the example I've given, but my user still has some broken contacts in his database :( too bad those didn't appear when I've exported that, so I'll have to mess in with the database tables to pin that down :(

**Comment by DeepDiver1975** [comment]
@ghormoon I'm happy to debug deeper into this issue - but I need example vcards which are falling apart - please open a new issue - THX

**Comment by ghormoon** [comment]
Just to confirm, is it safe to select the cardbook and insert it into another (with different PKeys) and then  delete cards until I manage to find out which was the bad one? I ddin't manage to find other that this one with exporting and importing back :(

**Comment by DeepDiver1975** [comment]
> Just to confirm, is it safe to select the cardbook and insert it into another (with different PKeys) and then delete cards until I manage to find out which was the bad one?

Should work - yes. But please do this on some test server and do backups before killing data :wink:

**Comment by ghormoon** [comment]
I have only "prod" server (~5users), but I do it at least on other user and have snapshot of whole VM just in case :)
