### ISSUE TITLE
Import JS issue

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#313]
On trying to import my production vcf (3.7 MB), I get this in the JS error console:

```
angular.js?v=47e1a99…:13236 TypeError: Cannot read property 'displayName' of undefined
    at new Contact (contact_model.js:9)
    at import (contact_service.js:112)
    at contactImport_directive.js:15
    at Scope.$eval (angular.js?v=47e1a99…:16820)
    at Scope.$apply (angular.js?v=47e1a99…:16920)
    at FileReader.<anonymous> (contactImport_directive.js:14)
```

@Henni let me know if I need to send you the vcf file, or preferably which part of it. :)

**Comment by jancborchardt** [comment]
This is because there is no address book initially. There should be a default address book called »Contacts« always. :)

When there is no address book, this also happens when you click on »Add new contact«.

**Comment by jancborchardt** [comment]
(Cause when I now just added an address book, import worked.)

cc @jospoortvliet for that blog post.

**Comment by DeepDiver1975** [comment]
@jancborchardt please retest with latest master an let me know if issues still arise - THX

**Comment by DeepDiver1975** [comment]
Please supply example vcard for testing

**Comment by jancborchardt** [comment]
Well, it still occurs when there’s no address book and you click on the »Add new contact« button. No specific vcard needed.

But I guess since we force an address book to exist and prevent the last one to be deleted, this can be closed?
