### ISSUE TITLE
[Enhancement] Link to specific contact

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#318]
Give Apps (like Calendar) the possibility to link e.g. Birthday Events to specific contacts 

https://github.com/owncloud/calendar/issues/383

cc @DeepDiver1975 @Henni @georgehrke @skjnldsv

**Comment by skjnldsv** [comment]
I'm planning on fixing #312, which means modifying the base url loading.
So I should allow the direct uid link and fix the contact load :)

**Comment by Henni** [comment]
It should be possible via:
http://localhost:8080/index.php/apps/contacts/#/All%20contacts/87119bde-04fd-4926-aa84-21ddd88de7ea
But there is currently a bug which discards the uid and instead opens the first contact.

@DeepDiver1975 maybe we should remove the localization from the URL to allow generic links from outside the app.

**Comment by skjnldsv** [comment]
@Henni Yep, we should allow direct uid access without group.
I don't think the localization would be a problem, we could do like that:
- group & uid set and uid in group -> display contact
- uid set -> display All contact group + contact
- group set -> display group and first contact
- group & uid set but uid not in group -> change to the correct group and display contact
- group & uid set but uid unknown -> display message saying that the contact is unknown

**Comment by Henni** [comment]
i think we should always have a group.
If you don't want a specific group you should set it to 'all'
So the path should look like:
`/apps/contacts/#/all/87119bde-04fd-4926-aa84-21ddd88de7ea`

**Comment by DeepDiver1975** [comment]
The uid is not enough the address book is has to be encoded in there as well - remember we want to build the app to load data as lazy as possible.

**Comment by DeepDiver1975** [comment]
In other words: the group has no meaning in this case.

**Comment by skjnldsv** [comment]
Should be fixed in #323 !
Please review.

Url will be https://localhost/index.php/apps/contacts/#/all/2cbf6908-4a5b-403f-8e68-77165679b3bb for a direct access to a contact

**Comment by DeepDiver1975** [comment]
> Url will be https://localhost/index.php/apps/contacts/#/all/2cbf6908-4a5b-403f-8e68-77165679b3bb for a direct access to a contact

This will not work once we have a different model in terms of loading contacts - see https://github.com/owncloud/contacts/issues/318#issuecomment-203671768

**Comment by skjnldsv** [comment]
We will edit the code when necessary then no?
Or will those change be in the 1.2?

Can you take a look at the PR?
