### ISSUE TITLE
Don’t create »default« address book if another one already exists

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#320]
Besides, the »default« address book should be called »Contacts«, a less technical name.

**Comment by skjnldsv** [comment]
This come from dav :)
https://github.com/owncloud/core/blob/master/apps/dav/lib/hookmanager.php#L114

**Comment by DeepDiver1975** [comment]
Please reopen in core

**Comment by jancborchardt** [comment]
Reopened at https://github.com/owncloud/core/issues/23720
