### ISSUE TITLE
Addressbook entry's not shown, but synchronized

### ISSUE THREAD

**Issue by ufgum** [owncloud/contacts#322]
I have a lot vcard entry's, which contain only the "N" line, the "FN" line is missing. I don't know, where they are coming from, maybe from an old "kaddressbook" app or from older owncloud version, or from android before, no way to find out anymore. If I actually add an address, the "FN" is there.
Anyway on owncloud prior version 9, this entry's was shown. On android this vcard entry's are shown, on "kaddressbook" this entry's are shown, on owncloud 9 this entry are not show up anymore.
### Steps to reproduce
1. create a vcard, open in text editor and delete "FN" line
2. import to owncloud
3. look in the db, the vcard is there, even updates over carddav are working, but not shown in contacts app
### Server configuration

**ownCloud version:**
9.0.0.19
**Contacts version:**
1.1.0.0
**Updated from an older ownCloud or fresh install:**
update

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

```

```

**Comment by Henni** [comment]
The dav library we use only loads vcards which contain the FN attribute.
This decision was probably made because all vCard have to contain a FN based on the [RFC](https://tools.ietf.org/html/rfc6350#section-6.2.1)

We have to wait for #216 to fix this, I think.

**Comment by ufgum** [comment]
I'm wonder, because if no FN is in "oc_cards_properties" the contact does load, but if no FN in "oc_cards.carddata" the contact does not load.

**Comment by ufgum** [comment]
Ok. I found the source of this issue: My Jolla phone does not create the `FN` and on some contacts it just deletes the existing `FN`
Should be fixed soon: [merproject](https://git.merproject.org/mer-core/buteo-sync-plugin-carddav/commit/9c7d183efb7524158599118e6c3a4fd340a0a8d9)
But anyway, it would be nice for the contacts app, to show all the contacts, which are in the DB!
