### ISSUE TITLE
Error in single vcard stalls app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#328]
JS console:

```
localhorst/:96 GET http://localhorst/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js?v=47e1a995c8c88b83a1ade723d427ac51 
vCard2JSON_filter.js:4 Uncaught (in promise) ReferenceError: vCard is not defined(…)(anonymous function) @ vCard2JSON_filter.js:4Contact @ contact_model.js:177(anonymous function) @ contact_service.js:35
vCard2JSON_filter.js:4 Uncaught (in promise) ReferenceError: vCard is not defined(…)(anonymous function) @ vCard2JSON_filter.js:4Contact @ contact_model.js:177(anonymous function) @ contact_service.js:35
```

owncloud.log:

```
Could not find resource file \"\/owncloud\/apps\/contacts\/js\/vendor\/vcard\/src\/vcard.js\
```

The vcard should be skipped and the contact/field marked as erroneous in the list. @Henni @irgendwie @skjnldsv 
(I have no idea which parameter I changed and why it’s broken now.)

**Comment by jancborchardt** [comment]
cc @tomneedham @DeepDiver1975 as well

**Comment by skjnldsv** [comment]
A little more details pls? 
This is related to the import issue with corrupted vcard right?

What exactly were you trying to do?
All I can see now is that you're missing the vcard dependencies.

**Comment by jancborchardt** [comment]
No clue … it just was broken at some point. How can I supply more details? I don’t have more info than the js log and owncloud.log, but am happy to provide more if you let me know what you need. ;)

**Comment by skjnldsv** [comment]
Ahah, well, Can't tell what i need, not sure what I'm looking at! :/

**Comment by tomneedham** [comment]
I think you have to run `bower install` now as vCard is in the `bower.json` file. If someone else can confirm this is correct then we should stick this in the readme for how to contribute.

**Comment by tomneedham** [comment]
(It isn't an error with a vcard, you're missing the dependancy)

**Comment by jancborchardt** [comment]
Eh … can we please put this in the makefile as well? I hope you know that keeping the compile process simple is very important to get more contributors onboarded. cc @Henni @BernhardPosselt sure it’s fun to play with all these tools but at the end of the day it needs to work. ;)

**Comment by tomneedham** [comment]
Yeah 100%. @Henni can help here - since I'm not sure when the vendor folder got removed and can't figure out how to trace that back in github history.

**Comment by jancborchardt** [comment]
After a `bower install --force` it works a gain, for the record.

**Comment by BernhardPosselt** [comment]
bower install && bower update should be in the makefile already

**Comment by BernhardPosselt** [comment]
So running make should fix it ;)

**Comment by tomneedham** [comment]
Ahh I've got it now. `npm` installs bower and runs `bower install` as part of the build command which is in the Makefile. @jancborchardt did `make` not work for you originally?

**Comment by jancborchardt** [comment]
No, make did not work for me originally, as said. I was running make every pull.

**Comment by BernhardPosselt** [comment]
http://bower.io/docs/api/#force

"It also forces installation even when there are non-bower directories with the same name in the components directory"

Edge case issue? I'd rather not add force to the build command since its very expensive

**Comment by jancborchardt** [comment]
Not sure if it’s an edge case since it just happened out of the blue without any specific setup. No idea what build tool sorcery this is, but it should not take precedence over it simply working.

**Comment by DeepDiver1975** [comment]
Obviously a faulty build on @jancborchardt 's environment - I had the same once - having a closer look at the output of bower install reviles that vcard could not be installed because teh vcard folder already existed - removing that folder and rerun bower install fixes this.
