### ISSUE TITLE
Import some Mail-Stuff

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#334]
If the Mail-App is enabled, contacts could: 
- Automaticly find new Mail-Adresses and add them to already existing contacts (with giving users the chance to review)
- Automaticly find new Mail-Adesses and add them together with Name (and maybe Adresses from Signatures) to contacts (with giving users the chance to review)

Inspired by Apple Mail and Apple Contacts (OS X; iOS)

**Comment by DeepDiver1975** [comment]
I see this more as a feature of the mail app to detect the required information and push this into the system using carddav - nothing to do in the contacts app.

@aspdye please open this in the mail repo - THX
