### ISSUE TITLE
Background of Header must no be white

### ISSUE THREAD

**Issue by ionum** [owncloud/contacts#337]
### Expected behaviour

Background of VCARD-Header must not be white
### Actual behaviour

If UID (which seems to be used for calculating the background color) contains an mail-like value (eg 20140426T014914.e765f629e7@domainname.net) background-color is white, which is bad for readability...
### Server configuration

ownCloud version:9.0.0
Contacts version: 1.1.0.0

**Comment by skjnldsv** [comment]
Duplicate  #300
See #306

We're waiting for https://github.com/owncloud/core/pull/23768 to be merged so we can use the core function and fix this issue.
