### ISSUE TITLE
Test the new Contacts app and contribute!

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#34]
We are working on the Contacts rework for 9.0: https://github.com/owncloud/contactsrework
The CardDAV syncing was moved into core, and this is the repo for the new Contacts app frontend.

I’m using this issue to cc everyone who worked on Contacts in the past:
@babelouest, @jbtbnl, @ockham, @derkostka, @jakobsack, @schuemann, @tribut, @mroi, @lupusmeatus, @BernhardPosselt, @AdamWill, @LEDfan, @vgezer, @rehrumesh, @DavidPrevot, @martin-rueegg
You can easily help in several ways:
- test everything and open issues!
- have a look at issues and contribute (or ask developer friends to help): https://github.com/owncloud/contactsrework/issues
- review pull requests https://github.com/owncloud/contactsrework/pulls
- join the #owncloud-contacts IRC channel

Thanks a lot! :)

**Comment by enoch85** [comment]
The Contacts app (master) are now included in the ownCloud beta VM: https://twitter.com/techandme_se/status/705619820960620544

**Comment by DeepDiver1975** [comment]
the app is in the appstore - i guess we can close this
