### ISSUE TITLE
Can't find some functions or doesn't work correctly - export function, CalDav link, upload contact photo, share adressbook, share about federed-cloud-id

### ISSUE THREAD

**Issue by volker-raschek** [owncloud/contacts#344]
Hey together, 
I wondered, because I don't find some important functions in the new Concact App in owncloud 9.
1. I don't know how I can change the contact photo from a contact. I can't find the upload button -.-'
2. In the old Contact Version under owncloud 8 I could copy the CalDav link over an icon. Now I can only copy it about the source code from the delivered page. Now I must hold the mouse cursor over the address book name to see the CalDav link. It's not very user friendly.
3. I shared a address book with a friend and I don't want that he could edit some entries.  So I don't check the check-box "can edit" but he can edit the entries. 
4. In my address book have some contacts more than one federed-cloud-id's. When I want to share it with the contact I get only the first federed-cloud-id about the auto-complete function. 

So apologise for my bad English

regards
Volker

**Comment by Henni** [comment]
1. not implemented yet (#342)
2. take a look in the settings, there is an icon for every addressbook to show its CardDAV url
3. known issue. Will be fixed for 9.0.1
4. Please open an issue for this. We might have to fix this.
