### ISSUE TITLE
Redesign of contact properties and display order of corresponding label and actions

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/contacts#345]
The current design of contact properties in https://github.com/jbtbnl/contacts is as follows:

![untitled](https://f.cloud.github.com/assets/639688/1869849/92353a26-787f-11e3-9691-5005bf54e245.png)

Quote from @jancborchardt:
> The inputs and labels should really not be in the same column – this creates a mix of labels and actual information. Inputs should be to the right and the labels on the left – right-aligned though so they are better associated with the input.

Considering that there can be 3 or 4 elements surrounding a property, a mock-up is preferred to discuss a new design before an implementation is realized.

**Comment by jancborchardt** [comment]
It turns out it’s fine like it is now, with the labels above the fields. Makes for a pretty readable and nice layout. :)
