### ISSUE TITLE
Blank Page 

### ISSUE THREAD

**Issue by octacian** [owncloud/contacts#351]
### Steps to reproduce
1. Download and Install Newest Version
2. Open with Firefox
### Expected behaviour

Contacts should load allowing me to add new contacts, and all the other normal contacts things.
### Actual behaviour

A blank page is shown with the Settings menu also shown, but non responsive on click.
### Server configuration

**Operating system**: Ubuntu Server 15.10

**Web server:** Apache v2.4.12

**Database:** MySQL v5.6.28

**PHP version:** v5.6.11

**ownCloud version:** 9.0.1 (stable)

**Contacts version:** 1.1.0.0

**Updated from an older ownCloud or fresh install:** Updated from v9.0.0

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**
- Activity
- Collaborative tags
- Comments
- Deleted Files
- Federation
- First Run Wizard
- Gallery
- Mail Template Editor
- Notifications
- PDF Viewer
- Provisioning API
- Share Files
- Text Editor
- Update Notification
- Versions 
- Video Player
- Calendar
- QOwnNotesAPI
- Tasks

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - qownnotesapi: 0.4.3
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ochsd1rrd16d',
  'passwordsalt' => '*** removed for security reasons',
  'secret' => '*** removed for security reasons',
  'trusted_domains' => 
  array (
    0 => 'myIP',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://myIP/link/cloud.local',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '*** removed for security reasons',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
```

```
{
    "system": {
        "instanceid": "ochsd1rrd16d",
        "passwordsalt": "*** removed for security reasons",
        "secret": "*** removed for security reasons",
        "trusted_domains": [
            "myIP"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/myIP\/link\/cloud.local",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "*** removed for security reasons",
        "dbpassword": "*** removed for security reasons",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Firefox

**Operating system:** Ubuntu 15.10

**CardDAV-clients:** GNOME Contacts
#### ownCloud log (data/owncloud.log)

```
Error   contacts    Could not find resource file "/link/cloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js"    2016-04-10T19:20:52+00:00
Error   contacts    Could not find resource file "/link/cloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"   2016-04-10T19:20:52+00:00
Error   contacts    Could not find resource file "/link/cloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js"    2016-04-10T19:20:52+00:00
```
#### Browser log

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://myIP 'unsafe-eval'"). contacts
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create dav.js:3072:415
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

```

There are also a lot of 404 errors in the Network tab, but to many to copy.

**Comment by octacian** [comment]
To summarize all of that, whenever I load Contacts, a blank unresponsive page is shown. From the Network log, many 404 errors are shown, and the ownCloud log shows that some resources could not be found.

**Comment by DeepDiver1975** [comment]
> Error contacts Could not find resource file "/link/cloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js" 2016-04-10T19:20:52+00:00 Error contacts Could not find resource file "/link/cloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js" 2016-04-10T19:20:52+00:00 Error contacts Could not find resource file "/link/cloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js" 2016-04-10T19:20:52+00:00

you have to run make - the app is not usable after a simple close from the repo

**Comment by octacian** [comment]
How do I run make @DeepDiver1975? I have used make before but am not very familiar, so thanks for your help. A list of the commands I need to run would be useful, as I am especially unfamiliar with using a Makefile that is already included.

I do not believe I have CMake installed on my server, so am running `sudo apt-get install cmake`.

**Comment by octacian** [comment]
I now have CMake installed, but of course simply running `make` does not work, so I would really appreciate help on this.

Thanks again.

**Comment by DeepDiver1975** [comment]
make not cmake :wink:

**Comment by DeepDiver1975** [comment]
In case you don't want to build the app yourself you can use the official release from the appstore or use your nightlies - https://github.com/owncloud/contacts/releases

**Comment by octacian** [comment]
OK, I've got make. But how do I make Contacts with make? @DeepDiver1975 I could use the latest release, but since there has been some commits since, I might as well make it myself if it is simple enough you can tell me how.

**Comment by octacian** [comment]
Also, I had previously installed the latest release but opted to go right off the source code as whenever I opened the app, it would just say it was loading endlessly. The screen on the right would say **No Contacts Yet** or whatever, but the middle contacts list would just sit and load, load, load.

**Comment by DeepDiver1975** [comment]
> Also, I had previously installed the latest release but opted to go right off the source code as whenever I opened the app, it would just say it was loading endlessly. The screen on the right would say No Contacts Yet or whatever, but the middle contacts list would just sit and load, load, load.

this was fix a few minutes ago ...

**Comment by DeepDiver1975** [comment]
> OK, I've got make. But how do I make Contacts with make?

https://github.com/owncloud/contacts#building-the-app

**Comment by octacian** [comment]
Oh OK, thanks! Can't believe I didn't notice there were instructions before. I will make sure I have the newest version and make it myself since I would guess the release won't be updated till tomorrow. 

Thanks again for your patience in helping me!

**Comment by octacian** [comment]
@DeepDiver1975, upon trying to build Contacts (I just got to it), I get the following error with npm:

```
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! contacts@0.1.0 prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contacts@0.1.0 prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contacts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contacts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contacts
npm ERR! There is likely additional logging output above.
```

I have updated nodejs to the latest version as it had an errors previously, and I tried to update bower with `npm install -g bower` but that does not seem to work or bower is not the problem. I have also used `bower-update` and `npm-check-updates`

Thanks.

**Comment by octacian** [comment]
I will create a new issue on this.
