### ISSUE TITLE
Error When Building

### ISSUE THREAD

**Issue by octacian** [owncloud/contacts#352]
Upon trying to build Contacts, I get the following error with npm:

```
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! contacts@0.1.0 prebuild: `npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contacts@0.1.0 prebuild script 'npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contacts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node_modules/bower/bin/bower install && node_modules/bower/bin/bower update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contacts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contacts
npm ERR! There is likely additional logging output above.
```

I have updated nodejs to the latest version as it had an errors previously, and I tried to update bower with `npm install -g bower` but that does not seem to work or bower is not the problem. I have also used bower-update and `npm-check-updates`

Any help appreciated. Thanks.

**Comment by DeepDiver1975** [comment]
Are you running make as root or with sudo?
You should not according to the error message

**Comment by octacian** [comment]
I have been running make with sudo (`sudo make`), as when I run make by itself without sudo, I am presenting with another error saying that sudo is required. 

The Contacts directory I am running make in is located within `/var/www/owncloud/apps/contacts` and chown ownership is set to `www-data:www-data`. I wonder if I should try running make with Contacts owned by the user (`server:server`)? 

I will try this tomorrow, unless there is something I should try first.

Thanks!‎

**Comment by DeepDiver1975** [comment]
I really advise to not build the app on the server - unless you really know what you are doing.

Please use the nightly releases - will be much more convenient for you.

**Comment by octacian** [comment]
Yes, I can use the nightly releases and will do so for now. However, if for some reason I needed to go straight of the source code, that would create a problem as I am still being given an error. Would you be willing to explain this error to me? 

I am running `make` in the home directory of my server (`/home/server`) after running `chown -R server:server ~/contacts-master` to be sure the folder is owned by the user. I have also run `chmod -R 0755 ~/contacts-master`. However, whenever I run make I am given the following error:

```
Error: EACCES: permission denied, open '/home/server/.config/configstore/bower-github.json'
You don't have access to this file.
```

More lines follow saying `at Object`, or `readCachedConfig`, etc...This would tell me that somehow I don't have something setup right, in that the folder is either missing or I have configured the permissions improperly.

Thanks. Will use the nightly for now, but as I said I would really appreciate being able to also build from the source in case the need ever arises.

**Comment by DeepDiver1975** [comment]
I suggest to Google for the error message and see what is causing this. I never experienced this - sorry.

**Comment by octacian** [comment]
OK. Thanks @DeepDiver1975. BTW, I am really liking the contacts app, great work!
