### ISSUE TITLE
Importingg VCF  file leads to Strange Names.

### ISSUE THREAD

**Issue by ghost** [owncloud/contacts#355]
### Steps to reproduce
1. download and installed fresh 9.0.1
   2.installed contacts app from owncloed store"
2. import attaached vcf file
### Expected behaviour

import the VCF correctly like it does on OwnCloud 8.2.3 (Same Server, same environment, just another folder on the Webspace
### Actual behaviour

![bildschirmfoto 2016-04-12 um 16 11 56](https://cloud.githubusercontent.com/assets/3584431/14463235/8d3c2e82-00ca-11e6-846e-bf4dc6066d15.png)
### Server configuration

**Operating system**: Sinology DSM6 

**Web server:** Apache 2.6

**Database:** myphpadmin

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Contacts version:** (see ownCloud apps page) 1.1.0.0

**Updated from an older ownCloud or fresh install:** fresh inst

**Signing status (ownCloud 9.0 and above):**all no error shown in the admin page

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**
Only the contact app

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

sudo -u http php occ app:list
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /volume1/web/oc1/lib/private/db/connection.php:54
Stack trace:
#0 /volume1/web/oc1/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /volume1/web/oc1/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /volume1/web/oc1/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /volume1/web/oc1/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /volume1/web/oc1/lib/private/db/connection.php(137): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /volume1/web/oc1/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /volume1/web/oc1/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /volume1/web/oc1/lib/private/server.php(366): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /volume1/web/oc1/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC{closure}(Object(OC\Server))
#9 /volume1/web/oc1/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /volume1/web/oc1/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /volume1/web/oc1/lib/private/server.php(886): OC\ServerContainer->query('DatabaseConnect...')
#12 /volume1/web/oc1/lib/private/server.php(260): OC\Server->getDatabaseConnection()
#13 /volume1/web/oc1/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC{closure}(Object(OC\Server))
#14 /volume1/web/oc1/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppConfig')
#15 /volume1/web/oc1/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /volume1/web/oc1/lib/private/server.php(825): OC\ServerContainer->query('AppConfig')
#17 /volume1/web/oc1/lib/private/server.php(411): OC\Server->getAppConfig()
#18 /volume1/web/oc1/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC{closure}(Object(OC\Server))
#19 /volume1/web/oc1/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('AppManager')
#20 /volume1/web/oc1/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#21 /volume1/web/oc1/lib/private/server.php(1063): OC\ServerContainer->query('AppManager')
#22 /volume1/web/oc1/lib/private/app.php(254): OC\Server->getAppManager()
#23 /volume1/web/oc1/lib/private/app.php(103): OC_App::getEnabledApps()
#24 /volume1/web/oc1/lib/base.php(577): OC_App::loadApps(Array)
#25 /volume1/web/oc1/lib/base.php(1112): OC::init()
#26 /volume1/web/oc1/console.php(46): require_once('/volume1/web/oc...')
#27 /volume1/web/oc1/occ(11): require_once('/volume1/web/oc...')

**The content of config/config.php:**
?php
$CONFIG = array (
  'instanceid' => '_securityremove_',
  'passwordsalt' => '_securityremove_',
  'secret' => '_securityremove_',
  'trusted_domains' =>
  array (
    0 => 'TDL_DOMAIN',
    1 => '192.168.178.62',
  ),
  'datadirectory' => '/volume1/web/oc1/data',
  'overwrite.cli.url' => 'http://TDL_DOMAIN/oc1',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'oc2',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '_securityremove_',
  'dbpassword' => '_securityremove_',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/... = no

**Are you using encryption:** yes/no = no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... = no

```

### Client configuration
**Browser:** Safari 9.1

**Operating system:** Yoemite,  but happen on El Captitan swell.

**CardDAV-clients:** None

### Logs
#### Web server error log
```

Insert your webserver log here
I don't have one from the DS

```



#### ownCloud log (data/owncloud.log)
```

Insert your ownCloud log here

```
Currently the Owncloud.log has no entry after I imported the VCF file.
Is there anything how to improve the debug logging?

#### Browser log
```

Insert your browser log here, this could for example include:

see attachment network_Capture_from_safari
![networkcapture_from_safari](https://cloud.githubusercontent.com/assets/3584431/14463197/62f7c4f6-00ca-11e6-9b2f-3b17b9977fb2.png)

```
```

**Comment by DeepDiver1975** [comment]
Can we have the vcard for testing please? THX

**Comment by ghost** [comment]
Of Course, But I guess it works with everyone :)
I couldnt upload it here because the file was not supported, so I just waited if someone would request it. 
https://karinundpatrick.de/oc1/index.php/s/aqjMK1AqNd28oKf

I tried to import this vcf also on OS X Contacts, and there, its working aswell like on OC 8.2.3

**Comment by DeepDiver1975** [comment]
Oh - yes and org only vcard - duplicate

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/contacts/issues/335

**Comment by ghost** [comment]
what does org only vcard means?
Vcards with organisation only?
I have also my full vcard with all contacts, those contains also contacts with a fullname and without a company name.
Those contacts will also not be imported. May I send you this vcard in private? dont want to offer all such informations

**Comment by aspdye** [comment]
org only does mean, that the contact has no name (like John Doe) - it is only an organization (like Doe Inc.) 

You can see an example in the screenshot of this issue 😉

**Comment by ghost** [comment]
Then its a quite bad example.
Please check this vCard, it contains a surname and a name, without any company name. The behaviour is exactly the same. 
Would you please so kind to confirm that with this vCard aswell?
http://karinundpatrick.de/oc1/index.php/s/5uKkZ9guWF1dh4c

**Comment by aspdye** [comment]
Please don't change parts of your questions and comments, or add other aspects to them 😁 THX 😄
My answer was only to the following question:

> what does org only vcard means?

**Comment by ghost** [comment]
Sorry, some ppls doesn't like it to add another post if there is no reply.
Then  I add it as a new information now :D
I get the same behavior by adding the vCard (a spam phone number, without any company name) http://karinundpatrick.de/oc1/index.php/s/5uKkZ9guWF1dh4c
And I get the behaviour when I add a mix, like the company name only and the spam phone vCard as one vCard.
behavior: 
Spam phone (w/o comp) = NOK
comp only = NOK
mix of both = NOK

**Comment by DeepDiver1975** [comment]
> Would you please so kind to confirm that with this vCard aswell?
> http://karinundpatrick.de/oc1/index.php/s/5uKkZ9guWF1dh4c

this has no FN - known issue as well

![bildschirmfoto von 2016-04-15 10-53-48](https://cloud.githubusercontent.com/assets/1005065/14556398/63cb548a-02f8-11e6-91d8-8ce22fd1bf10.png)

**Comment by ghost** [comment]
Thats quite interesting, because I can see on my iphone that I entered a surname and the name itself.
When I add FN instead of N, my OSX contacts looks different, and it only appears as Spam and no more as Spam Phone.
