### ISSUE TITLE
Backslashes (lots of !) added before coma into address field

### ISSUE THREAD

**Issue by gazbarg** [owncloud/contacts#358]
### Steps to reproduce
1. Edit (or define, for a new contact) the address field with a  comma in it
2. Comma gets backslashed when editing another field of the address (city, country)
3. Backslash gets backslased when editing another field of the address (city, country)
4. And so on.
5. Seems to stop at 6 backslashes
### Expected behaviour

No extraneous backslashes displayed
### Actual behaviour

Six backslashes too many
### Server configuration

GNU/Linux Gentoo 3.10.69-gentoo-LTS

**Web server:**
Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.2g PHP/5.6.20-pl0-gentoo

**Database:**
mysql 5.6.27

**PHP version:**
5.6.20

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Contacts version:** (see ownCloud apps page)
1.1.0.0

**Updated from an older ownCloud or fresh install:**
Update from 8.2.2 (with all in-between updates done)

**Signing status (ownCloud 9.0 and above):**
(Gentoo/webapp-config adds some ancilary file in the web application directory)
- core
  - EXTRA_FILE
    - .webapp-owncloud-9.0.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox 45.0.1

**Operating system:**
Linux 4.1.12-gentoo

**I tried to insert an image showing the problem, but "Something went really wrong"**

**Comment by gazbarg** [comment]
Small correction : there does **not** seem to be an obvious limit to the number of backslashes added.

**Comment by DeepDiver1975** [comment]
Fixed with the next release

**Comment by gazbarg** [comment]
Great ! Any idea when this release will come out ?

**Comment by DeepDiver1975** [comment]
I guess after the next meetup in Munich - April 21st
