### ISSUE TITLE
Unable to customize the avatar

### ISSUE THREAD

**Issue by flo1o1** [owncloud/contacts#364]
### Steps to reproduce
1. Create a new contact
2. Hover over the default (dynamic) avatar
### Expected behaviour

According to the [official documentation](https://doc.owncloud.org/server/9.0/user_manual/pim/contacts.html#customizing-an-avatar), there should be two options how to change the avatar. This can be done by clicking one of the icons which are above the current avatar:

![Contact Picture](https://doc.owncloud.org/server/9.0/user_manual/_images/contact_picture.png)
## Actual behaviour

I do not see any buttons or icons which would allow me to change the avatar. I also do not see a hint if I might be missing a library (gdlib or imagemagic). It is not possible for me to change the avatar from the web interface.
### Server configuration

**Operating system**: Debian GNU/Linux 8.4 (jessie)

**Web server:** Nginx

**Database:** MySQL

**PHP version:**

**ownCloud version:** 9.0.1 (stable) from Debian packages

**Contacts version:** 1.1.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.x

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

Enabled:
- activity: 2.2.1
- calendar: 1.1
- comments: 0.2
- contacts: 1.1.0.0
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- mail: 0.4.1
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9r1nwyuilp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updatechecker": false,
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome Version 47.0.2526.73 (64-bit)

**Operating system:** (K)Ubuntu Linux Ubuntu 15.10

**CardDAV-clients:** None

**Comment by DeepDiver1975** [comment]
we are working on that - https://github.com/owncloud/contacts/pull/342

**Comment by aspdye** [comment]
Dup of #144 isn't it :grin:
