### ISSUE TITLE
Cannot log-in after enabling the App

### ISSUE THREAD

**Issue by derkostka** [owncloud/contacts#37]
Maybe something is missing, but i cannot get into my owncloud after enabling the contactsrework.

a) Do i have to disable the "deprecated" contacts app ?
b) Do i need to rename this new app to "contacts" ?

Log is:
{"reqId":"4vhxURWv5wF2+UtkmEqB","remoteAddr":"192.168.6.1","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:app.svg webroot: serverroot:\\/var\\/www\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/apps\\/contactsrework-master\\/appinfo\\/app.php(35): OC\\URLGenerator->imagePath('contactsrework', 'app.svg')\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/navigationmanager.php(63): OC_App::OCA\\ContactsRework\\AppInfo\\{closure}()\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(645): OC\\NavigationManager->getAll()\n#3 \\/var\\/www\\/owncloud\\/lib\\/private\\/templatelayout.php(82): OC_App::getNavigation()\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/template.php(225): OC\\TemplateLayout->__construct('user', 'files')\n#5 \\/var\\/www\\/owncloud\\/lib\\/public\\/appframework\\/http\\/templateresponse.php(156): OC_Template->fetchPage()\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#7 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/routing\\/routeactionhandler.php(45): OC\\AppFramework\\App::main('OCA\\\\Files\\\\Contr...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/router.php(273): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#11 \\/var\\/www\\/owncloud\\/lib\\/base.php(856): OC\\Route\\Router->match('\\/apps\\/files\\/')\n#12 \\/var\\/www\\/owncloud\\/index.php(39): OC::handleRequest()\n#13 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/urlgenerator.php\",\"Line\":190}","level":3,"time":"February 17, 2016 21:10:30","method":"GET","url":"\/apps\/files\/"}

**Comment by LukasReschke** [comment]
>a) Do i have to disable the "deprecated" contacts app ?

Yes. And delete it. (or rename it to contacts_old)

> b) Do i need to rename this new app to "contacts" ?

Yes.

**Comment by derkostka** [comment]
Thanks ! 
The app name has to be "contactsrework", no bug just misunderstanding !
