### ISSUE TITLE
Most clicks take 80 s for 6,000 contacts

### ISSUE THREAD

**Issue by rob9** [owncloud/contacts#372]
For large address books, the Contacts app is unusable due to its extensive slowness.
- the old Contacts app had same problem, but worked somewhat after the initial timeout

In the new app, practically every mouse click is 80 s.
- All server requests must be paginated
- Do NOT store all contact info in a memory structure. It will become too large, slow and unreliable
- Either paginate from the server or use some client storage option
- Angular 2, for example, is a good example of LRU strategies

ownCloud 9.0.1
contacts 1.0.0.0
niginx/cached php5-fpm

**Comment by DeepDiver1975** [comment]
We are pretty much aware of this - will be taken care of - refs https://github.com/owncloud/contacts/issues/176
