### ISSUE TITLE
Support custom vCard type values

### ISSUE THREAD

**Issue by rob9** [owncloud/contacts#373]
According to rfc, type values (the descriptor like home, work other) supports lists of values and in particular custom values prefixed by x-

It is beneficial to further describe phone numbers, addresses, and emails using a custom free-form type value.

Contacts version 1.0.0.0 does not support custom type values.
Ensure inter-operability with Android that does support this feature
Refer to Google Contacts for how Google implemented custom type values

vCard 4.0 https://tools.ietf.org/html/rfc6350#section-5.6
5.6 TYPE
Section 3.3 x-name

vCard 3.0 https://tools.ietf.org/html/rfc2426#section-3.8
X- value

Contacts 1.0.0.0

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/contacts/issues/207
refs https://github.com/owncloud/contacts/issues/234
