### ISSUE TITLE
Highlight currently open contact in list (also groups in sidebar)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#38]
The currently open contact should get a class `active` added to its `app-content-list-item` in the list of people for proper highlighting.

**Comment by jancborchardt** [comment]
This also goes for groups in the sidebar.

**Comment by DeepDiver1975** [comment]
highlighting groups is in https://github.com/owncloud/contactsrework/pull/39

**Comment by DeepDiver1975** [comment]
> The currently open contact should get a class active added to its app-content-list-item in the list of people for proper highlighting.

I see no difference as soon as that class is applied

**Comment by DeepDiver1975** [comment]
oh - the background changes - my old :eyes:

**Comment by jancborchardt** [comment]
This is done thx to @DeepDiver1975 :)
