### ISSUE TITLE
Sorting issues after import

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#382]
On a recent import, this happened:
![capture du 2016-04-21 13-35-31](https://cloud.githubusercontent.com/assets/925062/14707640/fe8c5290-07c5-11e6-8d29-64505592a410.png) ![capture du 2016-04-21 13-27-27](https://cloud.githubusercontent.com/assets/925062/14707639/fe8bfd2c-07c5-11e6-89d0-ec442d4abc65.png)
Obviously there’s something wrong here … random contacts which start with »J« are sorted first in list, then someone with »Ar« who should be lower than someone with »An« and »Al«. The screenshots are from 2 different imports and persist after refresh.

**Comment by DeepDiver1975** [comment]
Please retest with https://github.com/owncloud/contacts/pull/378 being reverted

**Comment by DeepDiver1975** [comment]
Which browser?

**Comment by jancborchardt** [comment]
Ah, Chrome only (also incognito window). Firefox is ok.

**Comment by jancborchardt** [comment]
And with the commit before https://github.com/owncloud/contacts/pull/378 it works ok!

**Comment by DeepDiver1975** [comment]
Seems to be a Chrome bug related to the function localeCompare
