### ISSUE TITLE
Add possibility to rename and or disable adressbooks

### ISSUE THREAD

**Issue by hasselk** [owncloud/contacts#386]
that would be nice, if i remember correctly it was possible sometime

**Comment by irgendwie** [comment]
jfr  #409 #406

**Comment by snaiperskaya96** [comment]
Hiya, it's annoying me again.
I'm implementing this, just wondering about two points:
  - Which icon should I use to unlock/lock an address book? Cannot find any suitable one, should I add my own icon?
  - There's a visual bug when trying to add more than 4 action icons to an address book (icons go straight below the address book's name - see screenshot). What's the best thing to do in this case?

@DeepDiver1975 Any idea?

![screen shot 2017-02-15 at 1 16 03 pm](https://cloud.githubusercontent.com/assets/5279281/22976079/1675c236-f381-11e6-966a-6373d8260605.png)

**Comment by DeepDiver1975** [comment]
> Which icon should I use to unlock/lock an address book?

For enable/disable I assume? What about using a checkbox?



> What's the best thing to do in this case?

well there was the idea to move all these action into a popover menu
This is how it looks like in the calendar app

![bildschirmfoto von 2017-02-15 15-30-42](https://cloud.githubusercontent.com/assets/1005065/22978628/c5d67448-f393-11e6-8135-1357405d6020.png)

**Comment by snaiperskaya96** [comment]
>For enable/disable I assume? What about using a checkbox?

Whoops, ya, that's what i meant. A checkbox should do the trick!

>well there was the idea to move all these action into a popover menu
This is how it looks like in the calendar app

Cool, will do it in that way

**Comment by william-weber** [comment]
There's a bounty on this & I'd like to start but I see a couple of unmerged PRs that could be related. Is this claimable?

**Comment by DeepDiver1975** [comment]
> Is this claimable?

absolutly - got for it!

**Comment by rupertdev** [comment]
Is there any more work to be done on this?

**Comment by Julian1998** [comment]
@MichaelRupertDev  I don't think so.... so let's close this
