### ISSUE TITLE
contact sharing: Shared contacts as optional replacement for private contacts

### ISSUE THREAD

**Issue by thommierother** [owncloud/contacts#394]
I want to share a contacts list (and also a calendar) between all newly created members of an OC user group.

There should be a configuration option to replace the default (private) contacts, which are  automatically created upon account creation, with a shared contact list. This could be achieved through something similar like the 'skeletondirectory' directive for the files application. A second option could define the OC user group for which the contact list is shared.

**Comment by mr-gosh** [comment]
this is allready possible, if you share an addressbook to an group - every user of that group will see this addressbook - right?
and i don't think its a good idea to take away the "private" addressbook...

**Comment by thommierother** [comment]
It is only possible if you share the addressbook manually through the UI, but not automatically upon creation of a new account. My use case is an addressbook shared between a group of persons. And I also said this should be "optional" - nobody requested a replacement of the private address book in general.
