### ISSUE TITLE
cannot download/export contacts, no button

### ISSUE THREAD

**Issue by susca** [owncloud/contacts#395]
### Steps to reproduce
1. open contacts app
2. look for download/export button
### Expected behaviour

There should be a possibility to download/export contacts, e.g. as .vcs
### Actual behaviour

In the recent version (1.2 with OC 9.0.1) there is no such button (or it is very well hidden.
### Server configuration

**Operating system**: Debian 8 (Jessie)

**Web server:** apache 2.4.10

**Database:** mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 5.6.20-0+deb8u1

**ownCloud version:** 9.0.1 (beta)

**Contacts version:** 1.2

**Updated from an older ownCloud or fresh install:** continuous updates

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:** 
Enabled:
- activity: 2.2.1
- calendar: 1.1
- comments: 0.2
- contacts: 1.2.0.0
- dav: 0.1.6
- direct_menu: 0.7.1
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- gallery: 14.5.0
- mail: 0.4.2
- music: 0.3.11
- notes: 2.0.1
- systemtags: 0.2
- tasks: 0.9.0
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- firstrunwizard
- notifications
- provisioning_api
- templateeditor
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocbomtoct25f",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "www.anonimops.de",
            "anonimops.de"
        ],
        "datadirectory": "\/var\/www\/owncloud_data",
        "overwrite.cli.url": "https:\/\/www.anonimops.de\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.1.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox 46

**Operating system:** Win7 and Linux

**CardDAV-clients:** -
#### Web server error log

nothing relevant
#### ownCloud log (data/owncloud.log)

nothing relevant
#### Browser log

nothing relevant

**Comment by Henni** [comment]
This should work with contacts 1.2:
![image](https://cloud.githubusercontent.com/assets/1267827/14883396/4072f98e-0d3e-11e6-8d86-95d9d66d95d2.png)

**Comment by DeepDiver1975** [comment]
> ownCloud version: 9.0.1 (beta)

9.0.2 will fix this

**Comment by susca** [comment]
@Henni : 1.2 is installed, screenshot looks different (attached)
![occontacts](https://cloud.githubusercontent.com/assets/5244779/14883740/32ca466e-0d40-11e6-900c-648249c16885.png)

@DeepDiver1975 : when will 9.0.2 be out? And why does it work when @Henni does it?

**Comment by Henni** [comment]
@susca I'm running owncloud's master branch.
Take a look at https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by susca** [comment]
@Henni Thank you, I'll be patient for a few more days ;)
