### ISSUE TITLE
android how to sync by carddav?

### ISSUE THREAD

**Issue by Ucun** [owncloud/contacts#397]
thinks all owncloud dev. it's amazing!!!

i'm use android phone.how to sync by carddav APP?

**Comment by Ucun** [comment]
I did by this guide:
http://www.slsmk.com/sync-android-contacts-calendar-and-files-to-owncloud/

It's not work.

**Comment by DeepDiver1975** [comment]
Which app are you using?

**Comment by polkillas** [comment]
I personally used DAVdroid in previous Owncloud versions, but it doesn't seem to work with this new app.

**Comment by DeepDiver1975** [comment]
I know many people using davdroid. I did not try davdroid myself yet, but lets see ...

Which URL did you enter?

**Comment by Ucun** [comment]
@DeepDiver1975  thinks for you patient.

 I davdroid url  use owncloud contacts app default url like:http://myowncloud/owncloud/remote.php/dav/addressbooks/users/myname/default/

**Comment by aspdye** [comment]
Can you give us some Information about the device and the Android version?

**Comment by Ucun** [comment]
# @aspdye 

SOFTWARE INFORMATION
DAVdroid version: 1.0.8 (99) Wed Apr 27 15:44:38 GMT+08:00 2016
Installed from: APK (directly)
JB Workaround installed: no

CONFIGURATION
System-wide synchronization: automatically
Account: *******
  Address book sync. interval: 1440 min
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: —

SQLITE DUMP
android_metadata
    |  locale |

##     |  zh_CN |

settings
    |  setting | value |

##     |  hint_OpenTasksNotInstalled | 0 |

services
    |  _id | accountName | service | principal |
    |  1 | ******\* | carddav | http://******_/owncloud/remote.php/dav/principals/users/**_****/ |

##     |  2 | ******\* | caldav | http://******_/owncloud/remote.php/dav/principals/users/**_****/ |

sqlite_sequence
    |  name | seq |
    |  services | 2 |
    |  collections | 9 |

##     |  homesets | 5 |

homesets
    |  _id | serviceID | url |
    |  2 | 2 | http://******_/owncloud/remote.php/dav/calendars/**_****/ |

##     |  5 | 1 | http://******_/owncloud/remote.php/dav/addressbooks/users/**_****/ |

collections
    |  _id | serviceID | url | readOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | sync |
    |  3 | 2 | http://******_/owncloud/remote.php/dav/calendars/**_***_/contact_birthdays/ | 0 | Contact birthdays | <null> | -54 | <null> | 1 | 1 | 0 |
    |  8 | 1 | http://**_***_/owncloud/remote.php/dav/addressbooks/users/**_****/1c3fb2d3-6d99-4310-97df-61440dabef39/ | 0 | ben | <null> | <null> | <null> | <null> | <null> | 1 |

##     |  9 | 1 | http://******_/owncloud/remote.php/dav/addressbooks/users/**_****/default/ | 0 | default | <null> | <null> | <null> | <null> | <null> | 0 |

SYSTEM INFORMATION
Android version: 4.3 (9.2.A.1.215)
Device: Sony LT29i (LT29i)

#

**Comment by ralin3** [comment]
https://davdroid.bitfire.at/configuration/owncloud/

**Comment by skjnldsv** [comment]
@Ucun can we close this?

**Comment by Ucun** [comment]
@skjnldsv  OK.
