### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#4]
Since we’re now reworking the whole architecture based on the movement of dav into core, it’s a good point to revisit the design as well. Generally we should continue where we left off with the design of the current Contacts app because we put a lot of thought and work into it. cc @babelouest @jbtbnl
- app-sidebar is for displaying groups, adding and editing them
- app-content is for showing the actual contact list and showing/editing the details
- addressbooks go into the settings area because the majority only has one addressbook (also similar as we do for mail accounts in the Mail app)

The main question here is how we do the display of the contact list and the details. There are a few options:
1. Do it like in the current Contacts app, with the row expanding to reveal the full details.
2. Do it similar to the Mail app with a split content view, left column has the list of the contacts, and right area has the details. (We could use the sidebar for core from that, but it would be kind of a hack since then we would need to make sure it always is displayed, has a wider width, and it would conflict with sharing contacts, groups or address books since that’s what the sidebar is for.)
3. Use a completely new layout like bigger avatars and several columns. Similar to Facebook friends view on one’s profile. But then we still need a way to display and edit the details.
4. … ?

I’d say best is number 2. What do you think @MorrisJobke @raghunayyar @DeepDiver1975 @Henni @irgendwie @ChristophWurst @schiesbn @jbtbnl @babelouest?

**Comment by raghunayyar** [comment]
@jancborchardt if we are moving in the DAV direction, I would also like you to give a direction to both contacts and calendar.

**Comment by schiesbn** [comment]
I would also vote for option 2. I like the split view a lot and many desktop apps like Gnome Contacts look similar.

**Comment by Henni** [comment]
Option 2 sounds good, but we should probably move the code for the split view to core.

**Comment by jancborchardt** [comment]
@Henni yep, definitely as soon as at least 2 apps use it we should move it into core. Let’s take what we use in the Mail app and apply it for the Contacts rework, and as soon as it all works for both apps we can move it to core.

**Comment by babelouest** [comment]
I think too that the 2nd options is better, especially if another owncloud app uses this layout, I like consistency in different parts of the same system.

**Comment by jancborchardt** [comment]
@babelouest cool! It would be great if you’re in for collaborating on this app as well, as we aim to make it the main Contacts app. Hopefully with 9.0 as CardDAV should be moved into core by then. See https://github.com/owncloud/core/pull/20184 (and maybe help to review :)

**Comment by marneu** [comment]
Option 2 would also be my choice.

**Comment by jancborchardt** [comment]
@marneu yeah, we’re working on that in https://github.com/Henni/contactsrework/tree/contactlist-design (branch `contactlist-design`) – any help welcome.

**Comment by jancborchardt** [comment]
@marneu just saw you’re based in Munich: Come join us at our next ownCloud meetup: http://www.meetup.com/owncloud-munich – @Henni, @DeepDiver1975, me and more are always there to hack on apps.

**Comment by marneu** [comment]
@jancborchardt: see you there ;)

**Comment by jancborchardt** [comment]
@marneu cool! Bring your laptop and ideally already look into the code beforehand. :)

**Comment by marneu** [comment]
@jancborchardt: laptop ok, code noop (helping on a different project in the moment). Coming as tourist for future tasks on oc. Maybe as helper on less time consumptive ops for the moment. ;)

**Comment by jancborchardt** [comment]
@marneu cool! Yeah, just keep in mind it’s a hands-on meetup, no presentations or anything like that. :)

**Comment by marneu** [comment]
@jancborchardt: Is ok, just give me time for snooping around - then we will see ;)

Just a reminder for myself: vcard export should have an etag within header not only within vcard (ref https://tools.ietf.org/html/rfc6352#section-6.3.2.3)

**Comment by jancborchardt** [comment]
Closing because we solved it. Please help testing the Contacts app now!
