### ISSUE TITLE
Contacts gone after update

### ISSUE THREAD

**Issue by conan0276** [owncloud/contacts#404]
### Steps to reproduce

Upgraded from newest 8.x version to 9.0 to 9.0.1 to 9.0.2

Behaviour is every time the same (with owncloud 9.0, 9.0.1 and 9.0.2). THE CONTACTS DO NOT SHOW UP. 

Even after creating a new address book, deleting the old one, creating a new one and importing my contacts again from a vcf file. The contacts initially show up directly after the import, but they are gone as soon as I log out and come back later again. I only see an never-ending "loading"-indicator.
### Expected behaviour

Contacts show up
### Actual behaviour

Contacts do not show up in the browser. Sync error on Android (DavDroid 1.0.8)
### Server configuration

Ubuntu Xenial
Apache 2.4.18
MySql 5.7.12
PhP 7.0.4
OwnCloud 9.0.2
Contacts 1.2.0.0

```
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

Enabled:
- activity: 2.2.1
- calendar: 1.1
- comments: 0.2
- contacts: true
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- user_external
- user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'debug' => true,
  'instanceid' => 'oc15tqyi92ep',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '192.168.1.1',
  ),
  'datadirectory' => '/var/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.1.1/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_conan1',
  'dbpassword' => 'xxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'conan.de',
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => '30, auto',
  'loglevel' => 1,
);

no external storage
no encryption
### Client configuration

Firefox 46.0
Ubuntu Xenial

Chrome
Android 5.1
Davdroid 1.0.8
##### error.log

[Sun May 08 06:25:03.483799 2016] [mpm_prefork:notice] [pid 23315] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun May 08 06:25:03.483819 2016] [core:notice] [pid 23315] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 08 10:28:52.295026 2016] [mpm_prefork:notice] [pid 23315] AH00169: caught SIGTERM, shutting down
[Sun May 08 10:33:02.514106 2016] [mpm_prefork:notice] [pid 6840] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun May 08 10:33:02.514139 2016] [core:notice] [pid 6840] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 08 11:12:06.785888 2016] [mpm_prefork:notice] [pid 6840] AH00169: caught SIGTERM, shutting down
[Sun May 08 11:12:35.491040 2016] [mpm_prefork:notice] [pid 1858] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun May 08 11:12:35.737518 2016] [core:notice] [pid 1858] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 08 11:35:00.520548 2016] [mpm_prefork:notice] [pid 1858] AH00169: caught SIGTERM, shutting down
[Sun May 08 11:35:01.588164 2016] [mpm_prefork:notice] [pid 3089] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun May 08 11:35:01.588192 2016] [core:notice] [pid 3089] AH00094: Command line: '/usr/sbin/apache2'
~
#### ownCloud log (data/owncloud.log)

owncloud.log is empty

**Comment by ghost** [comment]
I have a similar problem with mine, I had contacts and just realized that they're not showing up, settings seems broken as well.  I'm on a ubuntu 14.04 machine using the packages from the owncloud repos.

A difference is that I Do have things in my logs:

Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js"  2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"     2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js"  2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/public/script.js"  2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js" 2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/ui-select/dist/select.js"   2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.js"   2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js"    2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-uuid4/angular-uuid4.js" 2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-route/angular-route.js" 2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular/angular.js" 2016-05-13T12:21:14-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js"  2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js" 2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js"  2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/public/script.js"  2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js" 2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/ui-select/dist/select.js"   2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.js"   2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js"    2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-uuid4/angular-uuid4.js" 2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-route/angular-route.js" 2016-05-13T12:20:18-04:00
Error   contacts    Could not find resource file "/owncloud/apps/contacts/js/vendor/angular/angular.js" 2016-05-13T12:20:18-04:00

EDIT: After upgrading to latest, https://github.com/owncloud/contacts/releases/tag/v0.0.0.59 , everything worked.

**Comment by skjnldsv** [comment]
@conan0276 @SchroSct 
Is it fixed then?

**Comment by thopiekar** [comment]
@skjnldsv: I've got the same here and my setup is the same like @conan0276 's.
So I guess upgrading does the trick here? When will be the latest changes released as stable?

Regards

**Comment by skjnldsv** [comment]
Upgrading the contacts app?
The next update is planned for the 30 May (1.3) :)

**Comment by thopiekar** [comment]
Nice, I guess I can wait for that :wink:

**Comment by skjnldsv** [comment]
Thank you :)
