### ISSUE TITLE
.vcf card import - Unknown Filetype error

### ISSUE THREAD

**Issue by arjunsarin** [owncloud/contacts#405]
### Steps to reproduce
1. Create an .vcf contacts file (for example with another ownCloud instance)
2. Try to import this file into a new empty addressbook
### Expected behaviour

All contact cards from the .vcf file should be added to a new addressbook.
### Actual behaviour

It appears an yellow message box "Unknown filetype." and nothing else happens
### Server configuration

**Operating system**: CentOS 6.7 (final)

**Web server:** Apache 2.2

**Database:** MySQL 5.1

**PHP version:** PHP 5.6

**ownCloud version:** ownCloud 9.0.1 (stable)

**Contacts version:** 1.2.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
collaborative tags 0.2
comments 0.2
deleted files 0.8.0
federation 0.0.4
first run wizard 1.1
gallery 14.5.0
mail template editor 0.1
notifications 0.2.3
pdf viewer 0.8
provisioning api 0.4.1
share files 0.9.1
text editor 2.1
update notification 0.1.0
versions 1.2.0
video player 0.9.8
calendar 1.1
contacts 1.2.0.0
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'ocfx9imw4hn6',
  'passwordsalt' => '######',
  'secret' => '######,
  'trusted_domains' =>
  array (
    0 => '####',
    1 => '####',
    2 => '####',
  ),
  'datadirectory' => '####',
  'overwrite.cli.url' => '####',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => '####',
  'dbhost' => '####',
  'dbtableprefix' => '####',
  'dbuser' => '####',
  'dbpassword' => '#####',
  'logtimezone' => 'UTC',
  'installed' => true,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/home/###/.redis/sock',
    'port' => 0,
    'timeout' => 0,
  ),
  'loglevel' => 0,
  'maintenance' => false,
);


```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome Version 50.0.2661.94

**Operating system:** Windows 10

**CardDAV-clients:** DavDroid
### Logs

```
My ownCloud log is too big for an upload.
```

**Comment by DeepDiver1975** [comment]
Already fixed with 1.3

**Comment by arjunsarin** [comment]
Ok, sorry. But what is the best way to get this new version as soon as possible? The current version is still 1.2 so I cannot update the app with the ownCloud updater app.

**Comment by DeepDiver1975** [comment]
> Ok, sorry. But what is the best way to get this new version as soon as possible? The current version is still 1.2 so I cannot update the app with the ownCloud updater app.

1.3 is not yet released

**Comment by sreutter** [comment]
Hello, great that a fix is already there.
when will that be released?

thank you
