### ISSUE TITLE
Provide Release as zip

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#408]
Because Contacts Source Code is not builded if you download it (calendar is) it would be nice if you could provide the releases not only as .tar.gz and also as .zip :wink: THX

**Comment by skjnldsv** [comment]
Why? Can't you untar instead of unzip? ^^

@aspdye bump!

**Comment by aspdye** [comment]
For the Users without technical knowledge (and for users of Shared Hosting Plattforms) it would be easier, because they are only unzipping in their webinterface :grin:

**Comment by skjnldsv** [comment]
But they're supposed to install it trough the oc app manager!
If they're smart enough to go and take the release from github, they should be smart enough to untar themselves! :p

**Comment by aspdye** [comment]
Not only GitHub ... Also at "apps.owncloud.com" which is downloading from GitHub :wink:

**Comment by skjnldsv** [comment]
Hum, indeed! :p 
@DeepDiver1975 you're the one building the releases, do whatever you want :D

**Comment by aspdye** [comment]
Closing after discussion in the IRC with @BernhardPosselt 😉
