### ISSUE TITLE
Do not use .well-known/carddav url

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/contacts#41]
For me there is a 404 request to the .well-known/carddav url in the network log:
`http://localhost/.well-known/carddav`

**Comment by DeepDiver1975** [comment]
further details:
we should not rely on welknow because it could be possible that there are multiple owncloud instances running and the contacts app should always connect to its own instance.

**Comment by Henni** [comment]
This is part of the dav lib. We might have to hack in and disable the well-known-request.

**Comment by nickvergessen** [comment]
```diff
diff --git a/js/public/script.js b/js/public/script.js
index 6035cec..771e10b 100644
--- a/js/public/script.js
+++ b/js/public/script.js
@@ -468,6 +468,7 @@ app.service('DavClient', function() {
 app.service('DavService', ['DavClient', function(client) {
 	return client.createAccount({
 		server: OC.linkToRemoteBase('dav/addressbooks'),
+		useProvidedPath: true,
 		accountType: 'carddav'
 	});
 }]);
diff --git a/js/services/dav_service.js b/js/services/dav_service.js
index 0606584..9981d37 100644
--- a/js/services/dav_service.js
+++ b/js/services/dav_service.js
@@ -1,6 +1,7 @@
 app.service('DavService', ['DavClient', function(client) {
 	return client.createAccount({
 		server: OC.linkToRemoteBase('dav/addressbooks'),
-		accountType: 'carddav'
+		accountType: 'carddav',
+		useProvidedPath: true
 	});
 }]);
diff --git a/js/vendor/dav/dav.js b/js/vendor/dav/dav.js
index 4844c34..a961ed4 100644
--- a/js/vendor/dav/dav.js
+++ b/js/vendor/dav/dav.js
@@ -683,7 +683,7 @@ var serviceDiscovery = _co2['default'].wrap(regeneratorRuntime.mark(function cal
         uri = _url2['default'].format({
           protocol: endpoint.protocol,
           host: endpoint.host,
-          pathname: '/.well-known/' + options.accountType
+          pathname: (!options.useProvidedPath ? '/.well-known/' + options.accountType : endpoint.pathname)
         });
         req = request.basic({ method: 'GET' });
         context$1$0.prev = 5;
```

This worked, but I don't feel very comfortable patching a JS lib. Also there is now a GET and a PROPFIND on the same URL, not sure if this is intended?

**Comment by Henni** [comment]
@nickvergessen thanks for looking into this.
It seems like the dav library was the wrong choice. Therefore we will probably exchange the library for davclient.js in version 2.0 which is already used by core (files) and calendar.
But for version 1.0 we should keep it. So let's fix this as hacky as we want for now.

@DeepDiver1975 do you agree on this?

**Comment by DeepDiver1975** [comment]
> But for version 1.0 we should keep it. So let's fix this as hacky as we want for now.

what about sucking in the dav client lib so that we can for now easier adjust it?

**Comment by Henni** [comment]
@DeepDiver1975 you mean instead of importing it via bower?
If so, yes let's do that.

**Comment by DeepDiver1975** [comment]
> you mean instead of importing it via bower?

yes - just copy and paste
