### ISSUE TITLE
Can't import contacts from vcard-file (.vcf)

### ISSUE THREAD

**Issue by lukasmalkmus** [owncloud/contacts#412]
### Steps to reproduce
1. Go into the contacts app
2. Click "Settings -> Import" and select a vcard-file
### Expected behaviour

Contacts app should import the uploaded file.
### Actual behaviour

ownCloud throws an error: "Invalid file type."
### Server configuration

**Operating system**: CentOS 7.2

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5

**PHP version:** 7.0.6

**ownCloud version:** 9.0.2

**Contacts version:** 1.2.0.0

**Updated from an older ownCloud or fresh install:** Fresh installation

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "check_for_working_htaccess": true,
        "instanceid": "ocrxw8shl9x5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "info",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "theme": "personal",
        "default_language": "de",
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 14",
        "activity_expire_days": 365,
        "htaccess.RewriteBase": "\/",
        "asset-pipeline.enabled": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        }
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Firefox 46.0.1

**Operating system:** Windows 10 64bit

**CardDAV-clients:** Thunderbird
### Logs

I found nothing important in the logs
### Additional information

I just started setting up my new server. Since I also changed the OS I decided to set up all my applications from scratch instead of trying to migrate everything. I downloaded the vcard-file from my old ownCloud 8.x instance and tried to import it into my new 9.x instance.

**Comment by parshikov** [comment]
@LukasMa see #398

**Comment by lukasmalkmus** [comment]
@parshikov Ah thanks. Haven't seen these reports. #392 looks good, but has it been released yet? It is merged into master, but I don't know the release strategy.

**Comment by aspdye** [comment]
@LukasMa You can find informations about the release strategy of the contacts-app on the milestone page: 

https://github.com/owncloud/contacts/milestones :wink:

**Comment by lukasmalkmus** [comment]
@aspdye Exactly what I've been looking for, thanks :)
