### ISSUE TITLE
Colours in headings and unwanted avatars

### ISSUE THREAD

**Issue by chrisisbd** [owncloud/contacts#413]
There is no way to configure the colours in the contacts list.  This gives me two problems:-

The round letter 'avatars' are just a distraction, especially as they are in a jumble of different colours,

The header backgrounds (in the same colours as the avatars) often make the white text illegible, in particular white on yellow isn't a good combination.

**Comment by rakekniven** [comment]
Personally I do not have any problems with the round letters.
But the colors are really a pain. Some contacts are not readable. For one group it shows white chars on white. 
Would be nice to have some config options to disable coloring.
Or make it stylable.

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by DeepDiver1975** [comment]
Hell no! No config Option for colors!
Keep it simple!

We better fix the color range.

**Comment by chrisisbd** [comment]
Personally I don';t think the colours add anything, they're just a mess down the side of the screen where the (not) avatars are.  I'd prefer to only show the avatar when there's a real one and to have a single colour for the header background.  The colours are just confusing, they look as if they mean something but they don't.

A contacts list is a _utility_ that one refers to for information, anything that makes it more difficult to see that information is bad.

**Comment by aspdye** [comment]
We can talk about **what** colors we want to use - **that** we use them is right, IMHO :wink: 
I think it will look nicer with the avatars, and maybe we can integrate an feature that takes a color which matches a bit with the avatar :grin: I think this is how Google Contatcs (and the Android app) does.

**Comment by skjnldsv** [comment]
Are we talking about the new or the old color generator?
If this is the new, then we should be discussing this in core. :)

The new algo has a brightness calculator and lower its config for better readability.

**Comment by chrisisbd** [comment]
But why have a 'random' colour generator, it's seems obtusely complex.  Surely it's should be a user preference. Apart from anything else there are _no_ colours that will always work for everyone, they need to be able to be set by the user.  Maybe the choice could be between a single colour (for those who prefer legibility and practicality) and the existing random colours (for those who want gaudiness).

**Comment by skjnldsv** [comment]
In android you can't change a color contact, and the color is defined on the uid too, not on the avatar (at least on my stock android 4.4 and 5.0.1)
I'm with Deep and Asp too, you should not change the color yourself, too many options are not a great idea. :/

**Comment by chrisisbd** [comment]
Yes, and I dislike Android too for that very reason!  Surely you can leave the multi-coloured default and allow the user to set a _single_ colour instead if they need to for legibility or whatever.  It's hardly a complex configuration choice.

**Comment by skjnldsv** [comment]
Well, in fact this is. Vcard don't have (to my knowledge) a color field to be set. That would require us to create a new value in the database to just store the colors?
It's a lot of work for an option hardly few people will use! :)

**Comment by chrisisbd** [comment]
It's only one value, a single item that says 'dark blue' or some such and, if it isn't set, then you get the default rainbow of colours.  Anyway there's loads of CSS in the contacts app that seems to set colours for most of it.  Are you overriding the colours in the CSS?

**Comment by skjnldsv** [comment]
Well, we won't add this feature. Feel free to do a pull request for a better readability on the font color here or the core generator in owncloud/core, but we won't add the option.
