### ISSUE TITLE
Three input fields all named email

### ISSUE THREAD

**Issue by dpavlotzky** [owncloud/contacts#415]
Hi,

The file [templates/contactDetails.html](https://github.com/owncloud/contacts/blob/0be9900fe3be99ba9dc7f0824ce7337319160a61/templates/contactDetails.html) contains three input fields. The names of all three input fields is "email".

The fields work as expected so it is mostly an aesthetic issue, but it looks wrong.

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Contacts version:** (see ownCloud apps page)
1.2.0.0

Kind regards,

David

**Comment by skjnldsv** [comment]
God, I should be ashamed... How did I get this merged without noticing!
Thanks @dpavlotzky. It's indeed not really an issue, but still...
