### ISSUE TITLE
How Can I Recover Contacts from my Database for the Same ownCloud Version?

### ISSUE THREAD

**Issue by raaomoka** [owncloud/contacts#416]
### Steps to reproduce
1. I wanted to rebuild my QNAP Server's storage to support the new Snapshot feature
2. I read that I should backup my ownCloud config and data folders + database
3. I manually backed-up the database via phpMyAdmin
4. I attempted using QNAP's Backup software backup my entire NAS folders (which I thought included the ownCloud folder) to my external 2TB SSD. I double checked before wiping out, and it showed that the folders were where I wanted them on my external SSD.
5. When it's time to restore, I find out some permission issue blocked the backup process of the ownCloud folder to my SSD (the files in the SSD were just somehow ghost copies), so, I don't have the config nor data folder backed-up but I have the Database containing my contacts
### Expected behaviour

There should be way to recover my contacts from the database
### Actual behaviour

I have no idea how to proceed, please could any of you great experts kindly guide me on how to proceed? Thank you very much in advance. I posted the same topic in the forums, but it just seems like a ghost town in there last time I had an issue, all the experts seem to be here on GitHub.
### Server configuration

**Operating system**: QTS 4.2.1

**Web server:** QNAP TS-470 Pro, 10GB RAM, 4x4TB Seagate ST4000VN000-1H4168 SC46 NAS Storgage, RAID 10 (8TB Total Volume, 15% reserves for Snapshots), FW QTS v4.2.1 Build 20160419

**Database:** MySQL Database

**PHP version:** 5.5.31 via phpMyAdmin v4.6.1 Git QPKG

**ownCloud version:** v8.0.4

**Contacts version:** v0.3.0.19

**Updated from an older ownCloud or fresh install:** Fresh install

**Signing status (ownCloud 9.0 and above):** Please consider making ownCloud v9.0 available on the QNAP App Center, pretty please :pray:.

**List of activated apps:**

```
If you have access to your command line run e.g.:
1. Activity v1.2.0
2. Contacts v0.3.0.19
3. Deleted files v0.6.2
4. External Sites v1.2
5. First Run Wizard v1.1
6. Mail Template Editor v0.1
7. PDF Viewer v0.7
8. Pictures v0.6.0
9. Provisioning API v0.2
10. Share Files v0.6.1
11. Text Editor v0.4
12. Updater v0.4
13. Versions v1.0.5
14. Video Viewer v0.1.3
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc0tk43cay26',
  'passwordsalt' => '**SALTY**',
  'secret' => **SECRET**,
  'trusted_domains' => 
  array (
    0 => '192.168.0.180',
  ),
  'datadirectory' => 'ownCloud',
  'overwrite.cli.url' => 'https://192.168.0.180:8081/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'ownCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '*** removed for security reasons',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
);
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** Yes, both via SSL and storage encryption on my QNAP NAS.

**Are you using an external user-backend, if yes which one:** I'm not sure of what this is, I just use ownCloud on a QNAP TS-470 Pro :tongue:
### Client configuration

**Browser:** Edge/Chrome

**Operating system:** Windows 10 Pro

**CardDAV-clients:** ContactSycn on Android and cFos Outlook Dav on Windows
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
N\A in this case
```

**Comment by irgendwie** [comment]
ownCloud < 9.0
https://github.com/owncloudarchive/contacts/blob/master/appinfo/database.xml

ownCloud / Nextcloud >= 9.0
https://github.com/owncloud/core/blob/master/apps/dav/appinfo/database.xml
