### ISSUE TITLE
update Contact 1.3 and 1.3.1. IOS can not synchronize with owncloud

### ISSUE THREAD

**Issue by Tuaneric** [owncloud/contacts#426]
Hello
After doing the update Contact 1.3 and 1.3.1. I can not synchronize with owncloud.

My Iphone with IOS 9.3.2, 
I added: https: //website/owncloud/remote.php/dav/addressbooks/users/my/default/

After validation: it changes: https: //website/owncloud/remote.php/dav/principals/users/my/default/

It is not normal.

thank you before

### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Contacts version:** (see ownCloud apps page)

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**

**CardDAV-clients:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Rello** [comment]
Hello,
you will need to post more info on "does not work".
Can you check from desktop e.g. Mac OS Addressbook?

try the URL
/owncloud/remote.php/carddav/principals/**_USER**_/

what Server are you using? nginx or apache?
Please post your redirects if they are correct

**Comment by Tuaneric** [comment]
Hello
I used apache2 Raspberry 2.

My link https://pi.xxx.fr/owncloud/remote.php/dav/addressbooks/users/eric/default/

Iphone detects the correct information but the contacts are not displayed

Thank

**Comment by benedikt-buchert** [comment]
I'm having the same issue it works on my mac but not on the iphone..

I'm using https://xxx.xxx.xx/remote.php/dav/principals/users/admin/

I added the the dav succesfully but no contacts seem to appear in the app. It works with iOs though.

**Comment by benedikt-buchert** [comment]
I also noticed that adress changes automatically
https://xxx.xxx.xx/remote.php/dav/principals/users/user/my-calendar/ 
to https://xxx.xxx.xx/remote.php/dav/principals/users/user/

**Comment by Tuaneric** [comment]
Hello
 
I installed Owncloud 9.0.2, plug-in contact on my raspberry 2
I can not add new contact. There really new version of the problem.

Thank you

**Comment by enoch85** [comment]
Correct me if I'm wrong here, but isn't the app just a GUI? The backend is done in DAV.

**Comment by irgendwie** [comment]
Since ownCloud 9.0 the dav backend was moved into core and the contacts app is just a dav-client itself, so if the contacts app is not working - this repository is the correct place to report issues. :+1: Otherwise if the backend is not working (external clients not working), please report issues in  [owncloud/core](https://github.com/owncloud/core).

CardDAV links < 9.0:

> http://example.org/remote.php/carddav/[...]

CardDAV links >= 9.0:

> http://example.org/remote.php/dav/[...]
