### ISSUE TITLE
In web uploaded photos are not synchronized to iPhone

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/contacts#429]
I have connected ownCloud via CardDav to my iPhone SE.

When I add photos on the phone to contacts, they are displayed properly in ownCloud web some time later. But when I add them in the web, they are not shown on the iPhone - not even much time later.

**Comment by scriptPilot** [comment]
Should be fixed with #425

**Comment by lo-man** [comment]
I've the same problem with my android. @scriptPilot  Where is the fix in #425 ? I can't find a solution.

**Comment by scriptPilot** [comment]
If they implement fix #425, the sync Problem should be fixed as well. The data is synced, but not interpreted well by the phone. Workaround: Read contact data, Change invalid code, update contact data in oc - could be automized.

**Comment by irgendwie** [comment]
Is this problem still occurring or can we close this issue? @scriptPilot @lo-man

**Comment by scriptPilot** [comment]
Unfortunately not, photos are still saved not correctly: PHOTO;TYPE=image/jpeg:/9j/4AAQ...

**Comment by scriptPilot** [comment]
I tried to install the newest release, but I didn't work for me. How could I install the newest release to the server, is there any documentation?

**Comment by scriptPilot** [comment]
Fixed with release 1.4.0 - Thanks a lot!
