### ISSUE TITLE
CardDAV URL for default address book contains unexpected suffix

### ISSUE THREAD

**Issue by Pazu** [owncloud/contacts#431]
The CardDAV URL shown by the Contacts app for my default address book contains, after upgrading to owncloud 9.0.2 (and, indeed, before that upgrade) has long included an unexpected suffix.

https://example.com/remote.php/dav/addressbooks/users/my_username/family/

Where does the Contacts app get this URL? Does it come from core? Why does the default address book include that "family/" suffix?

**Comment by Pazu** [comment]
(Once I know whether this belongs here or in core, I'll of course supply more detailed config information per the template.)

**Comment by DeepDiver1975** [comment]
family is the name you gave the addressbook some time ago - right?

> Where does the Contacts app get this URL?

CardDAV defines lookup mechanisms to request the list of addressbooks for a given user.

**Comment by Pazu** [comment]
@DeepDiver1975 Yes, I assumed so as well, using some UI that perhaps existed in some older owncloud version.

There doesn't appear to be any UI for doing this now, though. As you can see in the attached screenshot, the Default address book can't be renamed. Is there any way to do that?

![contacts](https://cloud.githubusercontent.com/assets/2777268/16111274/0c40d11e-33b2-11e6-966e-86f5bd8e5e4a.png)

**Comment by DeepDiver1975** [comment]
technically speaking renaming the uri 'family' is not possible - this will break all connected clients.
renaming the displayname is technically possible but not yet implemented in the contacts app - you could change it in the db or using another carddav client _maybe_
