### ISSUE TITLE
Color is too bright

### ISSUE THREAD

**Issue by enoch85** [owncloud/contacts#432]
### Expected behaviour

Text in the name should be visible
### Actual behaviour

http://i.imgur.com/VP5bnXg.png
### Server configuration

**Operating system**:
Ubuntu Server 16.04
**ownCloud version:** (see ownCloud admin page)
9
**Contacts version:** (see ownCloud apps page)
1.3.1
### Client configuration

**Browser:**
Chrome
**Operating system:**
Debian

**Comment by enoch85** [comment]
cc @skjnldsv Want to change to the same colors here as in the calendar app? :)

**Comment by skjnldsv** [comment]
It is already merged! :)
see #306  and #345

**Comment by enoch85** [comment]
Great news!

**Comment by skjnldsv** [comment]
:tada:
