### ISSUE TITLE
Allow LDAP access (for VoIP phnes)

### ISSUE THREAD

**Issue by JPustkuchen** [owncloud/contacts#434]
I hope I'm right here for feature requests.
I'm looking for a solution to use Owncloud Contacts for LDAP access from a VoIP phone. I know that this has nothing to do with Owncloud LDAP (Login).

I found several users who require such a solution but could not find an implementation yet. This one is missing: https://mailman.owncloud.org/pipermail/devel/2014-April/000127.html

What can we do?

**Comment by zenlord** [comment]
This is a request to add support for an entirely different protocol... While I do agree that having multiple possible entries into the same backend is technically preferable, I think you would better set up some synchronization between your owncloud contacts and an LDAP addressbook (or look for phones supporting carddav 😃)

**Comment by JPustkuchen** [comment]
Thank you very much for your reply, Vincent. Our VoIP phones sadly only 
support LDAP and I was hoping there was a plugin or some development 
already done to prevent multiple syncs in between... :(

**Comment by zenlord** [comment]
I agree it would be a useful feature for a lot of people (including myself), but it's a non-trivial thing to do...

**Comment by DeepDiver1975** [comment]
The purpose of this app is to act as pure carddav client.
With respect in fulfilling this feature request I'd give it a try to sync ldap to carddav as @zenlord suggested.
