### ISSUE TITLE
[Questions] usability and standards

### ISSUE THREAD

**Issue by tessus** [owncloud/contacts#435]
I'm sorry, if this is not the right place, but with so many different channels, I don't really know which one to use to voice questions and/or concerns.

I've tested the latest version (1.3.1.0) of the Contacts app and there are basic features missing, which makes it practically impossible to use the app in any useful manner.
- Let's say you enter a name like `Helmut K. C. Tessarek`. Where can I specify what the first name (middle name(s) or initials) and lastname is? Another example: `Karl Heinz` can be either a first name, or a first name and a middle name.
- How do I enter a birthday? If I use the format YYYY-MM-DD, the field is gone the next time the Contacts app is started.
- How can I enter a birthday without a year?
- How do I enter: organization, position, title?
- Under `Settings`, the share icon does nothing. You click it, nothing happens.

I know that this app has undergone changes in the past, but above items are basic functionality. 

Another major problem, which caused a data loss, is the following:
I had birthdays without a year on my client (Android phone) and the sync procedure removed all birthdays without a year, because the contacts app considered these birthdays as bad and removed them.

I really don't understand why this is happening. There is a [vcard](https://tools.ietf.org/html/rfc6350) standard after all.
e.g. in the vcard standard the string `--0620` means June 20th, which is a date without a year. But the contacts app rejects it, when syncing and deletes the field altogether.

This is nothing personal and please understand that I ask an objective question (I have noticed that some developers react rather hostile when confronted with facts).
owncloud is several years old and in all this time, it was not possible to develop a functional contacts application? 
This is a fair question, please don't answer with: _you can always code it yourself_.

**Comment by DeepDiver1975** [comment]
Thanks for your feedback.
Basically all your points are discussed in individual issues.

Why is the app in the current state: we are right in the middle of implementing it and some things are not yet finished. Plain simple.

I will later reference all issues.

**Comment by DeepDiver1975** [comment]
> Let's say you enter a name like Helmut K. C. Tessarek. Where can I specify what the first name (middle name(s) or initials) and lastname is? Another example: Karl Heinz can be either a first name, or a first name and a middle name.

#265

> How do I enter a birthday? If I use the format YYYY-MM-DD, the field is gone the next time the Contacts app is started.
> How can I enter a birthday without a year?

#122 

> How do I enter: organization, position, title?

This is in the header - with exception of position
@jancborchardt 

> Under Settings, the share icon does nothing. You click it, nothing happens.

Worth a separate issue - works for me so we should analyse why this is broken for you.

**Comment by DeepDiver1975** [comment]
> Another major problem, which caused a data loss, is the following:
> I had birthdays without a year on my client (Android phone) and the sync procedure removed all birthdays without a year, because the contacts app considered these birthdays as bad and removed them.

this should not happen and has to be addresses -> new separate issue please

**Comment by jancborchardt** [comment]
@tessus For the Organization details: Title and Position seem to be used as the same on most all other contacts apps. Not sure what you mean by »Position« otherwise, and if »Title« doesn’t suffice, please give an example. :)

**Comment by jancborchardt** [comment]
@tessus but yeah as @DeepDiver1975 said – most of these are already addressed in issues, and generally for each problem there should be one _issue_ open, not a grouped one.

**Comment by DarkSteve** [comment]
Hi Tessus. The reason the app feels so far behind even though ownCloud has been out for years, is because the app is only months old!

With the release of ownCloud 9, the calendar and contacts were moved into the OC core. This meant the existing (mature) apps stopped working. The current Contacts app is missing the functionality that you've pointed out because the app basically started again from scratch.

The devs have done a hell of a lot in a short period of time, but yeah, there's still a ways to go.

Patience, Grasshopper, patience ;-)

**Comment by tessus** [comment]
@DeepDiver1975 @jancborchardt there's no field other than the name in the header I can change:

<img width="369" alt="screen shot 2016-06-14 at 21 21 56" src="https://cloud.githubusercontent.com/assets/223439/16065165/1e9b1a64-3276-11e6-81f3-9fa66d57558e.png">

Neither is there a field I can add via the drop down:

<img width="408" alt="screen shot 2016-06-14 at 21 20 09" src="https://cloud.githubusercontent.com/assets/223439/16065169/343409c6-3276-11e6-9cff-daaa46ec3e96.png">

To answer @jancborchardt questions:

**Title** is for the academic title(s)
**Position** is for the current job role/title
 **Organization** is for the current company/organization somebody works for

Some applications use the field title for the job role.

**Comment by tessus** [comment]
I believe that priorities should be assigned differently. I have the feeling that in this case people rather work on how to make the app look fancy and to improve the user experience, which in turn has unfortunately the opposite effect.

Instead, the first priority should be a solid base (backend) namely a contact data structure that adheres to the vCard/CalDAV standard. Users don't care how to enter data. At least not at first. They can live with dozens of fields (and even strange input formats), as long as storing the data and syncing it to a mobile device works perfectly.

The next priority is data presentation for input and output (transforming the input data to vCard data (internal representation) and vice versa).

After that people can add fancy javascript functionality to create a better user experience (e.g. one field for the name, when clicking next to it, this single field could transfom into several fields for firstname, middle names, lastname, title, ...).

I know, the above list is rather simplified, but I think you get the drift.

Yet again I want to underscore that it is not my intention to badmouth the product but to voice an objective (as far as possible) analysis of the current situation.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @jancborchardt there's no field other than the name in the header I can change:

![bildschirmfoto von 2016-06-15 10-06-21](https://cloud.githubusercontent.com/assets/1005065/16072379/d7b02be2-32e0-11e6-9e9f-6114a6a9df3b.png)

Which browser are you using?

**Comment by DeepDiver1975** [comment]
> Title is for the academic title(s)

as far as I'm aware of the title is part of the N array

**Comment by jancborchardt** [comment]
@tessus let me keep it short: This is an open source project, and everyone worked very hard on it to get it into the current state. Just because you have different priorities doesn’t mean the app is not good. It just means that you probably should get involved and help – this app is open source after all!
We aim to develop both functionality and design alongside each other. Because good design can’t be bolted on afterwards – Design is how it works, not just how it looks. Because an app with lots of features but lacking UX is not fun to use at all. Because we’re doing this app for us.

Besides the screenshot you show above is outdated, the current version looks like this:
![d](https://cloud.githubusercontent.com/assets/925062/16072370/caeb5ba2-32e0-11e6-9ac7-48d57fe6f87a.png)
The »Title« (as in Dr, Prof etc) distinction will be part of the name splitting: https://github.com/owncloud/contacts/issues/324

@DarkSteve thanks a lot for your kind words! :)

**Comment by DeepDiver1975** [comment]
> to voice an objective (as far as possible) analysis of the current situation.

no need to do that - we all know ourselves where we stand :speak_no_evil:

**Comment by tessus** [comment]
@DeepDiver1975 the screenshot I sent was with Calendar 1.3.1.0.
I'm using Firefox 47.0 on OSX 10.11.5 and 10.9.5.

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: true
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: true
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: true
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**Comment by tessus** [comment]
@jancborchardt 

> This is an open source project, and everyone worked very hard on it to get it into the current state. 

I'm not denying this. 

What I don't understand is that oc and its apps use object oriented architecture. Doesn't that mean that certain classes and methods can stay the same while the interfaces to the backend can easiliy be changed via adding another level to the class hierarchy or changing the existing abstraction layer class (which I hope was used in the first place)?

> Just because you have different priorities doesn’t mean the app is not good.

These are not my priorities but the usual priorities of successful software design and development.

>  It just means that you probably should get involved and help – this app is open source after all!

I just did. I gave you a list of priorities. As I mentioned before, these are not my priorities, but a means to create SW the correct way. You can't build a car by putting 4 tires on the road and build the car around it.

I don't think I'm a good fit for this kind of coding.

BUT: Coding is not the only way to help a project. I can assign priorities and plan further development.
Sometimes developers can't see the forest for the trees. That's where I could help.

> We aim to develop both functionality and design alongside each other. Because good design can’t be bolted on afterwards – Design is how it works, not just how it looks. 

I agree to disagree. In a project like this (app, not core) there are usually at least 3 layers: backend, middleware, frontend. You can code the middleware with the frontend in mind. This doesn't mean you have to code them at the same time.
As a side note, "good design" is very subjective. People seem to think it is good design to be able to delete a user by just clicking on a little icon. If you miss the 15 seconds undo timeframe, all data is lost.
Personally I think this is idiotic. See, very subjective.

> Because an app with lots of features but lacking UX is not fun to use at all. Because we’re doing this app for us.

I agree, but for UX to be successful, the underlying SW has to work.

> Besides the screenshot you show above is outdated, the current version looks like this:

How can it be outdated, when I am using the latest version?
