### ISSUE TITLE
Add Contacts works in IE but not latest Chrome

### ISSUE THREAD

**Issue by targeter21** [owncloud/contacts#436]
### Steps to reproduce
1. Start the owncloud 9.0 docker container.
2. Enable the Contacts app and navigate to it.
### Expected behaviour

I should be able to add a contact in Chrome. Also I should not see an infinite spinner on initial load of the Contacts app.
### Actual behaviour

Initial load shows a spinner that does not go away. Also, when I click 'Add Contact', nothing happens. There are no errors that I see in the dev console either.
### Server configuration

**Operating system**:
Windows and Ubuntu 16.04

**ownCloud version:** (see ownCloud admin page)
owncloud:9.0 docker image

**Contacts version:** (see ownCloud apps page)
Default available in the latest owncloud:9.0 docker image.

**Updated from an older ownCloud or fresh install:**
Fresh install

**Comment by targeter21** [comment]
After loading it in IE, it works correctly in Chrome. Very weird and leads me to believe something is not initializing in Chrome unlike IE.

**Comment by DeepDiver1975** [comment]
hmm . I fear there is not much we can do -> close
