### ISSUE TITLE
Which Contact-Tables are the correct ones - after 9.x?

### ISSUE THREAD

**Issue by Rello** [owncloud/contacts#438]
there are several tables - some from the old some from he new contacts version.
which can be cleaned up? shouldn´t the cleanup be part of the migration?

from the size, the 2 *_cards seem to be the same.

oc_addressbookchanges
oc_addressbooks

oc_cards
oc_cards_properties

oc_contacts_addressbooks
oc_contacts_cards
oc_contacts_cards_properties

**Comment by irgendwie** [comment]
The old tables will be automatically dropped with the upcoming ownCloud 9.1 version.
https://github.com/owncloud/core/issues/21889

No need to manually take care of them.

**Comment by Rello** [comment]
strange that my search did not find it.

thank you!
