### ISSUE TITLE
Problem with contacts since last app update

### ISSUE THREAD

**Issue by martingwb** [owncloud/contacts#441]
Hi,
I am having a problem with the contacts app since the last app upgrade.
I guess I will have to repair the oc_cards table. (but where can I find information what the table(s) should look like?) Or is there a way to reinstall the tables for the contacts app?
### Steps to reproduce
1. select "Contacts" ap
2. no contacts displayed, spinning wheel stays
### Expected behaviour

Contacts should be displayed
### Actual behaviour

Spinning wheel is displayed
oc.log
`{"reqId":"2YdCQ2b2Q5NkNFoDL0Ef","remoteAddr":"62.47.243.78","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT`id`,`uri`,`lastmodified`,`etag`,`size`,`carddata`FROM`oc_cards`WHERE`addressbookid`= ?' with params [\\\"6\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'carddata' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctr....`

... and the table oc_cards is empty.
### Server configuration

Os: raspbian
*_Web server: nginx
*_Database: mysql
*_PHP version: 5.6.x
*_ownCloud version: 9.0.1
*_Contacts version: 1.3.1.0
*_Updated from an older ownCloud or fresh install: fresh
**Signing status (ownCloud 9.0 and above): 
No errors have been found.

**List of activated apps:**
pi@rpi /var/www/oc $ sudo -u www-data php occ app:list
Enabled:
- activity: 2.2.1
- announcementcenter: 1.1.2
- bookmarks: true
- calendar: 1.2.2
- comments: 0.2
- contacts: true
- dav: 0.1.6
- documents: true
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_videoplayer: 0.9.8
- galleryplus: 15.1.0
- music: true
- notifications: 0.2.3
- ownbackup: true
- ownnote: 1.08
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_versions
- firstrunwizard
- gallery
- provisioning_api
- user_external
- user_ldap

**The content of config/config.php:**

pi@rpi /var/www/oc $ sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "52386aa1107aa",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "datadirectory": "\/mnt\/data\/oc-data",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "forcessl": true,
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "overwritehost": "whatever.crabdance.com:443",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/oc",
        "theme": "",
        "maintenance": false,
        "mail_domain": "gmail.com",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "trashbin_retention_obligation": "170, auto",
        "logfile": "\/mnt\/data\/oc-data\/oc.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "trusted_domains": [
            "whatever.crabdance.com",
            "rpi",
            "10.0.0.63"
        ],
        "mail_from_address": " whoever",
        "default_language": "en",
        "overwrite.cli.url": "https:\/\/whatever.crabdance.com\/oc",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "memcache.local": "\OC\Memcache\APCu",
        "mail_smtpport": "25",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "appstoreenabled": true,
        "appstore.experimental.enabled": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

*_Browser: Firefox, Chrome
*_Operating system: Windows 7, Ubuntu 16.04
**CardDAV-clients: davdroid
#### Web server error log

---
#### ownCloud log (data/owncloud.log)

see above
#### Browser log

---

**Comment by irgendwie** [comment]
Core issue now, since with 9.0 a new dav endpoint was established.
The Contacts app is just a frontend using the dav endpoint.
Maybe this is helpful: https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html#dav-commands
Otherwise please open a new issue in [owncloud/core](https://github.com/owncloud/core)
