### ISSUE TITLE
VCard4 returned with invalid PREF value

### ISSUE THREAD

**Issue by rfc2822** [owncloud/contacts#443]
Steps to reproduce:
1. Exporting contacts from Android generates VCards 2.1 with lines like `TEL;CELL;PREF:+12345`.
2. Import the vcf into OwnCloud (one contact with a line like above is enough).
3. Request the VCard with `Accept: text/vcard; version=4.0` and OwnCloud serves a VCard 4 with this line: `TEL;CELL=;PREF=:+12345`. [The missing value for `PREF` is not allowed](https://tools.ietf.org/html/rfc6350#section-5.3) and thus [causes problems](https://forums.bitfire.at/topic/1144/contacts-sync-issue-between-owncloud-android/).

OwnCloud 9.0.2, Contacts 1.3.1.0

**Comment by DeepDiver1975** [comment]
Sounds more like a pure backend issue - maybe even upstream within sabre dav

**Comment by rfc2822** [comment]
Shall I report it elsewhere?

**Comment by DeepDiver1975** [comment]
Let me find the time to analyse this. I will move the Ticket where it should go.

**Comment by PanierAvide** [comment]
Hello, any clues about this problem ? I have the same one and no solution for the moment (Owncloud 9.1.0, Contacts 1.4.0.0).

**Comment by bl4ckOut** [comment]
Same here... any update on this ?

**Comment by DeepDiver1975** [comment]
Starting with ownCloud 9.2 it will not be allowed to import vcard 2.1 - we should add a general check in the contacts apps as well ....

**Comment by DeepDiver1975** [comment]
Starting with ownCloud 9.2 it will not be allowed to import vcard 2.1 - we should add a general check in the contacts apps as well - see #540
