### ISSUE TITLE
breaking on a lot of valid vcards

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/contacts#446]
I wanted to have some testing vcard data so I grabbed files here:
https://gitlab.com/pwithnall/vcard-test-suite/tree/master/vcards/valid

and started to import them randomly.

Whaddayaknow, this broke rather quickly and now the contact app loads infinitely ;-)

Not sure if there's a testsuite of vcards atm but perhaps those can be grabbed ;-)

**Comment by DeepDiver1975** [comment]
Thanks for your feedback Jos! But I'm sorry to say that this is far from a helpful Report.

You know: issue template;-)

**Comment by jospoortvliet** [comment]
Yeah, sorry. It was more of a suggestion to use the v-cards in that repo as a test suite, in case you were looking for one. I could create issues for each of the breakage points of course but I'm not sure if that is helpful.

**Comment by DeepDiver1975** [comment]
> I could create issues for each of the breakage points of course but I'm not sure if that is helpful.

better then nothing :wink:
