### ISSUE TITLE
Display number of contacts below the contacts list

### ISSUE THREAD

**Issue by TecJon** [owncloud/contacts#449]
### Display total number of contacts

I suggest to display the total number of contacts below the contact list for convenience and verification. 

I imported a .vcf file with several hundred contacts and couldn't verify if all contacts got imported correctly. In fact they didn't and I only found out by chance that contacts were missing.

![numberofcontacts](https://cloud.githubusercontent.com/assets/11375752/16707485/d42d7c48-45cf-11e6-92eb-cfd1fff5f1cf.png)

**Comment by DeepDiver1975** [comment]
fixed with #453
