### ISSUE TITLE
OwnCloud + CloudFlare breaks new Contacts and Calendar UI

### ISSUE THREAD

**Issue by fracture-point** [owncloud/contacts#450]
### Steps to reproduce

Upgrade to 9.0.3 from 8.2.
### Expected behaviour

Contacts + Calendar works as usual
### Actual behaviour

Cloudflare is killing the Contacts and Calendar front ends (everything else works fine).  It took me a very long time to narrow this down, and I have finally determined that if you are using CloudFlare as a proxy (it's main purpose) for the owncloud domain, it will, by default, break Contacts + Calendar.  

The reason is that, by default, CF has "Auto Minifying" enabled for JavaScript, CSS, and HTML.  The break here is in the JS minifying - if I disable that ("Speed" page --> Auto Minify Section --> Uncheck JavaScript -->Clear all caches in CF and on your browser) everything works beautifully again.

Not per-se an OC issue, but as I was tearing my hair out trying to find it, I wanted to get it documented to help others.  I have never run into this type of issue with an app behind CloudFlare, though they do [acknowledge that it's possible](https://blog.cloudflare.com/cloudflare-tips-troubleshooting-common-proble/)

The symptoms are thus:

**Contacts**
The screen shows as almost completely blank.  There is one divider for the three panes (there should be too), and the settings button is there, but everything else is blank.  No contacts, no spinning wheel.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/410707/16771748/aa77a8cc-481f-11e6-9be5-03fab860fb31.png)

Oddly, no console errors (as is the case below with Calendar).

 **Calendar**
The screen shows a lot of untranslated Angular code.  Examples:
- {{ dt | datepickerFilter:SelectedView....
- {{ calendar.display...
- {{ userShare.displayname }}
- {{ groupShare.displayname }}

Screenshot:
![image](https://cloud.githubusercontent.com/assets/410707/16771571/fdfcb8ee-481e-11e6-8b60-04b944f072d8.png)
Console Errors:
![image](https://cloud.githubusercontent.com/assets/410707/16771590/0f769cac-481f-11e6-8dcb-2e87d85df686.png)
(mostly "Angular is not defined")

There are two endlessly spinning wheels; it's pretty obvious that something is wrong (unlike in Contacts). 
### Server configuration

**Operating system:**
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
MariaDB 10.0.26
PHP version:
php 5.5.9
**ownCloud version: (see ownCloud admin page)**
9.0.3
**Contacts version: (see ownCloud apps page)**
1.3.1.0 (calendar = 1.2.2)
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2
**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- calendar: 1.2.2
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- tasks: 0.8.1
- updatenotification: 0.1.0
  Disabled:
- bookmarks
- encryption
- external
- files_antivirus
- files_external
- firstrunwizard
- news
- notes
- templateeditor
- user_external
- user_ldap

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Safari and Chrome, both exhibit the same symptoms.

**Operating system:**
OS X El Capitan, Version 10.11.5

**CardDAV-clients:**
#### Web server error log

No errors
#### ownCloud log (data/owncloud.log)

No errors
#### Browser log

No console errors for Contacts, but here they are for Calendar:

[Error] SyntaxError: Unexpected identifier 'element'
    (anonymous function) (angular.js:308)
[Error] TypeError: undefined is not an object (evaluating 'angular.module')
    (anonymous function) (angular-route.js:1)
    global code (angular-route.js:32)
[Error] ReferenceError: Can't find variable: angular
    global code (ui-bootstrap.min.js:7:129)
[Error] ReferenceError: Can't find variable: angular
    global code (ui-bootstrap-tpls.min.js:7:129)
[Error] ReferenceError: Can't find variable: angular
    global code (calendar.js:1)
[Error] ReferenceError: Can't find variable: angular
    global code (app.js:1)

**Comment by maximevaillancourt** [comment]
Hi,

~~I'm having the same issue (though on NextCloud). Here's a dirty fix : in the CloudFlare DNS panel, simply disable the HTTP proxy (by clicking the orange cloud) on the record pointing to your OwnCloud/NextCloud server (so that CloudFlare only manages the DNS for that record). For some reason, the CloudFlare reverse proxy / CDN breaks OwnCloud/NextCloud.~~

~~Hope that helps!~~

EDIT: After reading a little on CloudFlare's minifying features, I believe the problem lies in the way they actually crunch the code: `angular` probably can't be found (thus, is not defined) because the order of the scripts is changed during the page load, similar to many issues regarding jQuery not being found when the script is not loaded first. Anyway, as you detailed, simply disabling the minifying feature fixes the problem and there's much to believe that OwnCloud can't do much to counter the problem, since CloudFlare plays around with the scripts on its side.

**Comment by DeepDiver1975** [comment]
> OwnCloud can't do much to counter the problem, since CloudFlare plays around with the scripts on its side.

I guess so - closing because of that- THX

**Comment by apotek** [comment]
The workaround here appears to be to log in to cloudflare, go to the "Speed" page, go to the Auto Minify section, and uncheck the box for javascript.

While your JS won't be minified anymore by cloudfront, at least it will work.

![screen shot 2017-05-17 at 5 27 05](https://cloud.githubusercontent.com/assets/279278/26147491/ba60a488-3ac1-11e7-8cfa-78d0266c3ed9.png)
