### ISSUE TITLE
Acid random colors for contacts!

### ISSUE THREAD

**Issue by savely-krasovsky** [owncloud/contacts#452]
Problem:
![vivaldi_2016-07-15_18-25-08](https://cloud.githubusercontent.com/assets/5345489/16879623/1566eb9c-4aba-11e6-8462-71556e54fe13.png)
Solution:
![2016-07-15_18-23-20](https://cloud.githubusercontent.com/assets/5345489/16879647/2ce974a6-4aba-11e6-95a9-b783e876d948.gif)
So, just convert RBG hex code to HSV, fix saturation on 30, brightness on 100, and randomize only hue. You will get light and cool shades of random colors. For better results play with saturation and brightness.

**Comment by DeepDiver1975** [comment]
Pull request welcome! THX

**Comment by irgendwie** [comment]
Should be fixed with the usage of the color generator in core, or not? ref #345 
Reopen please if I'm mistaken!

@DeepDiver1975 @skjnldsv

**Comment by skjnldsv** [comment]
Yes it is!
