### ISSUE TITLE
Can you release Alpha/Beta versions? 

### ISSUE THREAD

**Issue by enoch85** [owncloud/contacts#47]
I wonder if you could release Alpha/Beta versions so that I can integrate them in the [same way I do with the calendar app](https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L267-L281) on the VMs.

This is useful for testing purposes.

**Comment by DeepDiver1975** [comment]
Not yet. The editor is not ready yet.

**Comment by DeepDiver1975** [comment]
Let's push a very first test release .... @Henni objections?

**Comment by enoch85** [comment]
I saw the release, but could you please draft a release as well? What I would want is to be able to do [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L269-L283). Thanks!

**Comment by DeepDiver1975** [comment]
Hopefully this will happen tomorrow

**Comment by DeepDiver1975** [comment]
@enoch85 I just pushed a new tag https://github.com/owncloud/contacts/releases/tag/v0.0.0.3

travis will soo build the tar and place it in there - feel free to grab it and have fun - THX a lot!

**Comment by enoch85** [comment]
@DeepDiver1975 I can only find the source code, no built packages?

**Comment by enoch85** [comment]
@DeepDiver1975 Ok, turns out the VM is already running the latest as it pulls from master and you changed name of the repo. So contacts are in the latest VM. I will do some adjustments and release a new version soon. Please retweet when I do. Thanks for your great work!

**Comment by enoch85** [comment]
@DeepDiver1975 @Henni https://twitter.com/techandme_se/status/705619820960620544
