### ISSUE TITLE
Export suggests strange name for export file

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#470]
For me it shows: `hcLGwqdm`, whereas it should be `Addressbookname.vcf`, so by default `Contacts.vcf`.

Running on stable9 Nextcloud.

cc @Henni @irgendwie @DeepDiver1975 any idea? If I remember correctly we had that issue before, maybe it was fixed but not backported?

**Comment by DeepDiver1975** [comment]
Requires Update of sabre Library. Afaik works with  ownCloud 9.2.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/contacts/issues/396

**Comment by jancborchardt** [comment]
Ah, thanks! So this is nothing for a backport I assume cause it could cause breakage?

**Comment by DeepDiver1975** [comment]
sabre dav 3.2 is required - https://github.com/fruux/sabre-dav/commit/3b4306913e448a32be2a2c63def635c7a2638ec3#diff-dd9eff86b0d0b7e37674809f9b92f8ca
