### ISSUE TITLE
Contacts not showing up after refresh

### ISSUE THREAD

**Issue by irgendwie** [owncloud/contacts#48]
_How to reproduce:_
- Click 'Add contact'
- Refresh the page

_Expected Result:_
- Contact showing up

_Actual Result:_
- Not a single contact showing up

---

The PROPFIND request returns the correct list of contacts,
but it seems like they are not handled and shown afterwards.

**Comment by DeepDiver1975** [comment]
You have to create an addessbook named testAddr

**Comment by irgendwie** [comment]
Oh, still hardcoded? Works... :+1:
Still, will leave this open for now!

**Comment by jancborchardt** [comment]
Soo … is the address book still hardcoded? ;)

**Comment by Henni** [comment]
Yes it is.
@irgendwie had a fix which broke some other stuff. Do you want to take another look @irgendwie?

**Comment by DeepDiver1975** [comment]
we need to add an addressbook selector in the contact details to allow it's selection.

**Comment by jancborchardt** [comment]
And that addressbook selector should only show up when there are more than 1 addressbooks, of course. :)

**Comment by DeepDiver1975** [comment]
@irgendwie this should be fixed afaik

**Comment by irgendwie** [comment]
Is fixed, still - always fill in a name! :blush:
