### ISSUE TITLE
Move new Contacts button to sidebar

### ISSUE THREAD

**Issue by MariusBluem** [owncloud/contacts#483]
According to the removal of the **Search for new Messages**-Button in the Mail app, I think we should move the **New Contacts** Button to the left sidebar, because we also have the **New Message** Button in the Mail-app at this place 😉 
### Mail:

<img width="588" alt="mail_repro" src="https://cloud.githubusercontent.com/assets/19711361/17462367/d702bea0-5caa-11e6-9744-0f57fb8efb1a.png">
### Contacts:

<img width="604" alt="contacts_repro" src="https://cloud.githubusercontent.com/assets/19711361/17462370/e148bc16-5caa-11e6-9f25-139207761a73.png">

To adjust it a bit better, we could also call it **\+ New Contact** instead of **New Contact**

cc @jancborchardt

**Comment by DeepDiver1975** [comment]
Pull request welcome! :see_no_evil: 

Thanks!

**Comment by jancborchardt** [comment]
Yup, this is also something I talked about with @ChristophWurst. Will look much better and make it easier to add contacts when already scrolled down.

Do you want to go for it and open a pull request @mar1u5? :)

**Comment by jancborchardt** [comment]
(Btw, wording and casing should be »+ Add contact«. :)

**Comment by MariusBluem** [comment]
Nah ... Thats something for our design pros :stuck_out_tongue_winking_eye: @jancborchardt
