### ISSUE TITLE
Imported contacts without FN-field not showing up in contacts app

### ISSUE THREAD

**Issue by insomebox** [owncloud/contacts#485]
### Steps to reproduce
1. Import vcard file with missing FN-fields, e.g.

```
BEGIN:VCARD
VERSION:3.0
N:Contacts;Test;;;
TEL;type=CELL:123456789
PRODID:-//ContactsKit //intsig.com //1.0
END:VCARD
```

Comment: Imported contact appears in the "all contacts" list.
2. Log out from owncloud
3. Log back in and open contacts app
### Expected behaviour

Imported contact should appear in the "all contacts" list.
### Actual behaviour

Imported contact does not appear in the "all contacts" list.
Comment: Imported contact is present in oc_cards.
Comment: Imported contact gets successfully synced with iPhone.
### Server configuration

**Operating system:** Linux (armv7l)
**Web server:** lighttpd
**Database:** MariaDB
**PHP version:** 7.0.9
**ownCloud version:** 9.1.0
**Contacts version:** 1.3.1.0
**Updated from an older ownCloud or fresh install:** fresh

```
No errors have been found.
```
#### ownCloud log (data/owncloud.log)

```
none
```

That said, importing a contact with FN-field, e.g. (compare with example from above)

```
BEGIN:VCARD
VERSION:3.0
FN:Test Contacts
N:Contacts;Test;;;
TEL;type=CELL:123456789
PRODID:-//ContactsKit //intsig.com //1.0
END:VCARD
```

does show up correctly in the "all contacts" list after logout/login.

It appears that the contacts app is not showing vcards with missing FN-field. I meekly assume, that this behavior is unintended. Maybe its related to #478?!

**Story:** I exported all contacts from my iPhone using the app "IS Contacts Kit" and imported them in owncloud. After I logged out and back in, all imported contacts disappeared but two (I edited those two and gave them another name -> they obtained an FN-field). However, all contacts show up correctly on my iPhone, which is synced with owncloud. 

I tried to edit the carddata field of the missing contacts directly through mysql queries, but this seems to break the contacts app. No contacts are shown at all, because the app does not stop loading. Any chance I can edit those by hand?

**Comment by steinjer** [comment]
I've got the same problem. After importing many contacts, all vcard without a fn attribute are lost.
I'm using nextcloud 10.0.0 and  Contacts 1.4.0.0.
