### ISSUE TITLE
Support custom vCard type values

### ISSUE THREAD

**Issue by rob9** [owncloud/contacts#486]
According to rfc, type values (the descriptor like home, work other) supports lists of values and in particular custom values prefixed by x-

For example in the phone number dropdown, Home-Work-Mobile
the last entry could be "custom"
if custom is selected a string can be input, the user may input anything like "tollfree"
The phne numbver field then gets internally labeled x-tollfree and displayed as tollfree

It is beneficial to further describe phone numbers, addresses, and emails using a custom free-form type value.

Contacts version 1.0.0.0 does not support custom type values.
Ensure inter-operability with Android that does support this feature
Refer to Google Contacts for how Google implemented custom type values

vCard 4.0 https://tools.ietf.org/html/rfc6350#section-5.6
5.6 TYPE
Section 3.3 x-name

vCard 3.0 https://tools.ietf.org/html/rfc2426#section-3.8
X- value

Contacts 1.0.0.0

This used to be issues #207 #234 #373
Those are all closed, but this has not been implemented

**Comment by DeepDiver1975** [comment]
this is a duplicate of https://github.com/owncloud/contacts/issues/207
