### ISSUE TITLE
Contacts wont Work on nextcloud / MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by tobiasgraeber** [owncloud/contacts#487]
Can be Closed, Thx.

**Comment by ghost** [comment]
@graebermedien

You can't use just the github master as this will cause missing files (like the mentioned .js file) and this seen behavior.

Please either:
- Don't use github releases if don't know exactly what you're doing
- Read the readme and build the app like described here: https://github.com/owncloud/contacts/#building-the-app
