### ISSUE TITLE
Imports are only added to one addressbook

### ISSUE THREAD

**Issue by ostami** [owncloud/contacts#488]
I exported several vcard files from my Android. These were backups. I created new addressbooks call Android-backup-01 and Android-backup-02 in owncloud 6. I then imported each vcard file, selecting Android-backup-01 for my oldest backup and Android-backup-02 for my next to last backup. I'm using firefox 28 from Ubuntu repositories. All the contacts have been imported in only the Android-backup-01 addressbook. No contacts are in the Android-backup-02.

**Comment by babelouest** [comment]
this was fixed in #736 , closing it
