### ISSUE TITLE
Profile picture addede via web interface not displayed in android contacts

### ISSUE THREAD

**Issue by lysathor** [owncloud/contacts#489]
### Steps to reproduce
1. Change profile picture via web interface
2. Sync to android phone (I use CardDAV)
3. 
   ### Expected behaviour
   I expected to see the same picture that the web interface shows. 
### Actual behaviour

But an android fallback picture is shown.
### Server configuration

**Operating system**:
Synology DSM 6.0.1
**Web server:**
Apache 2.2
**Database:**
SQLite

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
OC 9.1
But bug also exists in OC 9.0.2 (I've not testet OC 9.0.4)

**Contacts version:** (see ownCloud apps page)
1.3.1.0

**Updated from an older ownCloud or fresh install:**
Updated from 9.02 via 9.0.4 to 9.1.0.
**Signing status (ownCloud 9.0 and above):**
(what does that mean?)

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```

**List of activated apps:**
Drop-down list shows: Dateien, Aktivität, Gallerie, Kontakte

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
Sorry, I have no access.
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc07....',
  'passwordsalt' => '19164....',
  'secret' => '2c4b....',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxx',
  ),
  'datadirectory' => '/volume1/web/owncloud/data',
  'memcache.local' => '\OC\Memcache\APCu',
  'overwrite.cli.url' => 'https://xxxxxxxxxx/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.1.0.15',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/owncloud',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

That was already requested above - and I added it.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.
#### LDAP configuration (delete this part if not used)
- (not used)

```

### Client configuration
**Browser:**
Opera 39.0
**Operating system:**
Win 10 / Android 6.0.1
**CardDAV-clients:**
CardDAV 1.3.1.0 (see above)

### Logs
#### Web server error log
```

Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)
```

Insert your ownCloud log here
Error   PHP chmod(): Operation not permitted at /volume1/web/owncloud/lib/private/Log/Owncloud.php#114  2016-08-15T18:34:41+00:00
Error   PHP chmod(): Operation not permitted at /volume1/web/owncloud/lib/private/legacy/util.php#916   2016-08-15T18:34:41+00:00
Error   PHP chmod(): Operation not permitted at /volume1/web/owncloud/lib/private/Log/Owncloud.php#114  2016-08-15T18:19:40+00:00

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by DeepDiver1975** [comment]
Known issue. Please test the open pull request. Thx

**Comment by lysathor** [comment]
Hi,

thanks for the info.

But how to test the pull request?
Is there a zip of the contacts app (e.g. a nightly build) that I could 
use to replace the current version?

Or could you tell me what files to replace?
In none of the subdirectories of my owncloud installation there is a 
"contact_model.js" file that I could replace by your fixed version.

I found a similar code in "js/public/script.js". Should I replace the 
code there?
I did that and it seems that this fixes the problem...

So if that what you want to know, I have good news.

Best regards,
Lysathor

Am 16.08.2016 um 10:02 schrieb Thomas Müller:
