### ISSUE TITLE
Order of Postnumber is no longer country localized

### ISSUE THREAD

**Issue by crackytsi** [owncloud/contacts#497]
### Expected behaviour

Postnumber / ZIP-Code is in germany in the order: 
zipcode city
### Actual behaviour

Using the latest Owncloud version together with latest DAVDroid the order is:
city zipcode
### Server configuration

**Operating system**:

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7

**Server version:** 
9.0.53

**Calendar version:**
1.3.3

**Updated from an older installed version or fresh install:**
fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**List of activated apps:**
Calendar, Contacts

**Comment by DeepDiver1975** [comment]
pull request welcome

**Comment by crackytsi** [comment]
I try. I would bind the configuration to the language of the user. Or do you have a better idear or comment?

**Comment by irgendwie** [comment]
@crackytsi I'm not sure if I understand the problem correctly. Would you mind providing screenshots so I can see for myself and understand the problem? Is it the problem still active?

**Comment by crackytsi** [comment]
Hi,
Issue can be closed, topic is mentioned here: https://github.com/owncloud/contacts/issues/506
