### ISSUE TITLE
Number of contacts in group is no longer displayed

### ISSUE THREAD

**Issue by crackytsi** [owncloud/contacts#498]
### Expected behaviour

The number of contacts within owncloud groups is displayed (as it was in older versions of contacts)
### Actual behaviour

The groups does not show the number of entries

I try to create a pull-request.
### Server configuration

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7

**Server version:** 
9.0.53

**Calendar version:**
1.3.3

**Updated from an older installed version or fresh install:**
fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):**

**List of activated apps:**
Calendar, Contacts

**Comment by DeepDiver1975** [comment]
Im not sure if we can do this given the carddav protocoll capabilities.

**Comment by irgendwie** [comment]
With #453 this issue should already be fixed. You should be able to see the number of contacts at the bottom of the contacts list, also when a group is selected.

This PR is not part of the current stable version of the contacts app, but feel free to test the nightly builds.
