### ISSUE TITLE
Contacts created in the app do not display names in other clients when synced

### ISSUE THREAD

**Issue by pepprim** [owncloud/contacts#499]
### Steps to reproduce
1. Create a new contact entry within the Owncloud Contacts app through the web browser, and fill at least the name field.
2. Synchronize the address book with this new contact to other clients or apps (like Rainloop Webmail or an Android phone with CardDav-Sync by dmfs GmbH) through URL offered by the Ownloud Contacts app itself.
3. Optionally repeat steps 1 and 2 _in a reverse way_ (synchronize with Owncloud a contact entry created within another third party client or app like the ones mentioned in the step 2). 
### Expected behaviour

When you open this new contact entry in any other synchronized app like the mentioned above, it should display correctly as the first name field in the synced apps the same name you entered in the name field of the Owncloud Contacts app interface.
### Actual behaviour

The field name you entered within the Owncloud Contacts app does not appear in the other syncrhonized apps. More precisely, I dectected a little difference in the two apps mentioned:
- For default contacts utility of Androd (6.0), the name does not appear at all.
- For Rainloop Owncloud app (4.23) and Rainloop Webmail standalone client (Community edition v1.10.3.15), the name appear as a sort of _contact id_ in the short list of contact entries but the two name fields (first name and last name fields) of the contact details screen display null.

However, Owncloud Contacts app displays properly the names of synced contact entries created within these other apps and environments (Android phone and Rainloop Webmail).
### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:**  9.0.4.1

**Contacts version:** 1.3.1.0

**Updated from an older ownCloud or fresh install:** Fresh install

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**
- activity: 2.2.1
- apporder: 0.1.2
- bookmarks: 0.7.1
- calendar: 1.3.3
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- direct_menu: 0.9.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notes: 2.0.2
- notifications: 0.2.3
- polls: 0.7.1
- provisioning_api: 0.4.1
- rainloop: 4.23
- systemtags: 0.2
- tasks: 0.9.2
- templateeditor: 0.1
- updatenotification: 0.1.0

```

**The content of config/config.php:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "26",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": "30",
        "defaultapp": "notes",
        "loglevel": 1
    }
}

```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none
### Client configuration

**Browser:** Firefox 48.0

**Operating system:** Ubuntu 14.04 LS

**CardDAV-clients:** Rainloop Owncloud app (4.23) and Rainloop Webmail standalone client (Community edition v1.10.3.15). Default Android 6.0 contacts utility synced through the third party Androd app CardDAV-Sync  0.4.20 by dmfs GmbH).

**Comment by irgendwie** [comment]
Thanks for your report!

When creating a new contact and filling the name field (in the header of the contact), only the full-name 'FN' property is filled. Other application should be able to read the property and split the name themselves or directly show the full-name property.

You can select "Detailed name" in the "Add field" drop-down menu in the contact detail view, to manipulate the first and last name directly.

**No** automatic detection of names is currently implemented, which means full-names are **not** split into first and last name by now.

The related issue is tracked in #324.

**Comment by pepprim** [comment]
> You can select "Detailed name" in the "Add field" drop-down menu in the contact detail view, to manipulate the first and last name directly.

Thanks for your reply and help @irgendwie, but I don't see any "Detailed Name" field in the drop-down menu... Neither First name or Last name fields (only nickname...which is  not what we are talking about). In fact, the entire list I can see in the drop-down list of the add field button (for new contacts and previous entries) is as follows:
- Address, Birthday, Email, Federated Cloud ID, Instant Messaging, Nickname, Notes, Phone, Social Network, Website.

**Comment by irgendwie** [comment]
@pepprim  I'm sorry, that was my fault - the detailed name feature was introduced by #437, which is not yet packed into a release. You can either install one of the current nightly versions (https://github.com/owncloud/contacts/releases)  or wait for the next release.
