### ISSUE TITLE
Contact birthdays

### ISSUE THREAD

**Issue by phsc84** [owncloud/contacts#5]
Is it planned to offer a CalDAV link for all contacts birthdays?

I'm not sure whether this should be addressed by the new contacts app or the new calendar app.

**Comment by Henni** [comment]
I think the right way to do this is integrating the feature into the calendar app.

If we would integrate it into the contacts app, every time a contact is created an entry in CalDAV would have to be created. The main issue with this are third-party clients which won't do this on their own.

I would approach this by crawling all birthdays from CardDAV in the calendar app and display them directly. Small problem: with this method we won't have a calendar "Contact birthdays" inside CalDAV.

Alternative idea:
Maybe we could adjust the CardDAV backend to also maintain a calendar. @DeepDiver1975 what do you think about this?

**Comment by jakobsack** [comment]
Hi, this feature already exists in the current contacts or calendar app (I think it's the first one). You might check the code for more information.

Sabre now ships a class called ```Sabre\VObject\BirthdayCalendarGenerator``` in the fruux/sabre-vobject repository. It might be useful but I do not have any experience with it.

**Comment by phsc** [comment]
The class <code>Sabre\VObject\BirthdayCalendarGenerator</code> is only part of sabre-vobject 4.0 (see pull request https://github.com/fruux/sabre-vobject/pull/239). But this version is still in alpha state. 
Furthermore, Ownclod has just been updated to sabre 3.0.5, which ships sabre-vobject 3.4.7, for release 9.0.

Therefore this class will not be included in Owncloud in the shortterm. But maybe it is still useful to get some implementation ideas...

**Comment by aspdye** [comment]
Isnt this App only the Client (Frontend) for the new CardDAV Backend. In my opionion it is a task for the backend (CardDAV) to communicate with the CalDAV Backend. The CalDAV Frontend (calendar-rework) will show the Birthdays then as well as all other Clients ;)

**Comment by DeepDiver1975** [comment]
The birthday calendar is WIP in core - https://github.com/owncloud/core/pull/22198
