### ISSUE TITLE
Deleted items folder

### ISSUE THREAD

**Issue by spoorun** [owncloud/contacts#500]
Contacts app should have a deleted items folder, working in the same way as the Files app, with a 'Deleted items' link displaying in the left-hand bar, above the Settings link.

Deletion would become a two step process, deleted items would move to that folder, and then be permanently removed if the folder was emptied, or an individual items was deleted from within the folder.

Items could also be restored from the folder to their original location.

Is is the expected behaviour that most Uses are used to in other software managing contacts (including iOS, Android, Zimbra, Outlook, Google etc....

It is more useful than the current behaviour and mitigates against unintended data loss which can be catastrophic.

**Comment by irgendwie** [comment]
Thanks for your suggestion!

A deleted folder is not planned for the contacts app. Also there is no way to sync this between different clients, connecting to the dav-backend in owncloud/core as it is not part of the carddav specification.
Plase correct me, if I'm wrong here @DeepDiver1975 @olantrust.

A 'undo'-function is probably the better solution in this case and tracked in issue #201.
