### ISSUE TITLE
importet contacts with "umlaute" ä/ö/ü are not correct

### ISSUE THREAD

**Issue by awdrfunk** [owncloud/contacts#503]
### Steps to reproduce
1. export adressbook in thunderbird (vCard)
2. import in nc
### Expected behaviour

contacts with "umlaute" ä/ö/ü are not correct
example:
"Günter" is imported as "G=C3=BCnther"
"Däppen" is imopted as "D=C3=A4ppen"
### Actual behaviour

Tell us what happens instead
### Server configuration

Version     Plesk v12.5.30_build1205150826.19 os_Debian 7.0
OS  Debian 7.11

**Web server:**
apache/ngnix
nginx   1.11.1-debian7.0.16080113
perl-Apache-ASP 2.62-1

**Database:**
mysql   5.5.50-0+deb7u2
**PHP version:**
7.0.9

**ownCloud version:** (see ownCloud admin page)
10

**Contacts version:** (see ownCloud apps page)
 Contacts 1.3.1.0

**Updated from an older ownCloud or fresh install:**
fresh

**Comment by irgendwie** [comment]
When you export address books with Thunderbird, the resulting file:

> % file contacts.vcf
> contacts.vcf: ASCII text, with CRLF line terminators

The umlauts are encoded with https://en.wikipedia.org/wiki/Quoted-printable

**Comment by irgendwie** [comment]
Closing in favor of:  #399
