### ISSUE TITLE
Two columns contact details 

### ISSUE THREAD

**Issue by irgendwie** [owncloud/contacts#505]
Since #480 the contacts app shows the contact details in a two column list, if screen size is >= 1450px. It makes use of the ['CSS3 Multiple Columns' Feature](http://www.w3schools.com/css/css3_multiple_columns.asp). This has the advantage of being less error-prone but comes with a few minor disadvantages:
- The columns are always balanced, meaning address fields, detailed name, etc. may get split
- The balance can lead to (minor) visual issues when using padding (as identified by @skjnldsv):
  ![hzplsn6](https://cloud.githubusercontent.com/assets/8360698/18181937/f5f01e2e-708d-11e6-8f02-96163d27a9bc.gif)
- ...

As suggested by @jancborchardt in #354, what was done by now:

> What is very important regarding layout:
> - [X] use 2 columns, and not more!
> - [ ] left column is phone, email address etc
> - [ ] right column is addresses
> - [X] have enough whitespace between the columns

**Comment by skjnldsv** [comment]
Ahahah! :D
Can't....look.....away!!!

**Comment by skjnldsv** [comment]
I will add that I would prefer not to split fieldset between the two columns! :)
For reference, a simple `detailsitem { break-inside: avoid-column; }` is enough to avoid this.

**Comment by irgendwie** [comment]
@skjnldsv feel free to create a PR :blush:

**Comment by skjnldsv** [comment]
Youhouuu! 

I will probably work on it and try to implement #114 too!
