### ISSUE TITLE
ownCloud Contacts don't receive contacts from iOS

### ISSUE THREAD

**Issue by alebeta** [owncloud/contacts#514]
Hello friends,

ownCloud Version: 9.1.0 Stable
OS: CentOS 7
iOS: 9.3.5

CardDav url: https://cloud.domain.com/owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/

The problem that i have is the next:

I configure my CardDav following the documentation from owncloud and for me its possible to receive some test contacts that i create in the owncloud app Contacts, but in the other direction to upload the contacts from my iOS to the owncloud is not possible. I already tried some works around like [https://github.com/owncloud/ios/issues/103](url) and i can not find a solution. from the logs when i said to my Contact App in iOS to update i see the next logs in my owncloud:

46.105.233.171 - - [08/Sep/2016:13:44:58 +0200] "REPORT /owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/ HTTP/1.1" 401 414
46.105.233.171 - USERNAME [08/Sep/2016:13:44:58 +0200] "REPORT /owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/ HTTP/1.1" 207 321
46.105.233.171 - - [08/Sep/2016:13:44:59 +0200] "PROPFIND /owncloud/remote.php/dav/principals/users/USERNAME/ HTTP/1.1" 401 414
46.105.233.171 - USERNAME [08/Sep/2016:13:44:59 +0200] "PROPFIND /owncloud/remote.php/dav/principals/users/USERNAME/ HTTP/1.1" 207 1534
46.105.233.171 - - [08/Sep/2016:13:45:00 +0200] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/USERNAME/ HTTP/1.1" 401 414
46.105.233.171 - USERNAME [08/Sep/2016:13:45:00 +0200] "PROPFIND /owncloud/remote.php/dav/addressbooks/users/USERNAME/ HTTP/1.1" 207 4013
46.105.233.171 - - [08/Sep/2016:13:45:08 +0200] "REPORT /owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/ HTTP/1.1" 401 414
46.105.233.171 - USERNAME [08/Sep/2016:13:45:08 +0200] "REPORT /owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/ HTTP/1.1" 207 321
46.105.233.171 - USERNAME [08/Sep/2016:13:45:10 +0200] "REPORT /owncloud/remote.php/dav/addressbooks/users/USERNAME/contacts/ HTTP/1.1" 207 321

But i guess if i can download the contacts should be possible also upload my contacts, but for some reason is not working. And this is something that i want to upload the contacts to my owncloud.

Thanks and all the best.

**Comment by alebeta** [comment]
UPDATE:

Now i check if i create a new contact in my iOS it is uploaded to the owncloud contacts App, but why the old users are not being uploaded?

thanks

**Comment by ghost** [comment]
I think, this is because your current contacts are saved in the Apple Cloud (iCloud).

You will have to export and import them manually (export from iCloud -> import to Owncloud) if you want to get rid of the cloud.

Every new contact gets saved to your standard addressbook (iOS-Settings).
Every then taken action gets synced to your standard addressbok (iOS-Setting).
It works for my setup this way.
(Owncloud 9.1, Contacts 9.2, iOS 9.3.5, HTTPS connection to Synology NAS via DynDNS)

**Comment by alebeta** [comment]
Hey DJstone thanks for the answer! if i export the contacts from iCloud and Import to ownCloud , when my iphone sync with the owncloud contacts i will have contacts duplicated? or not?

**Comment by alebeta** [comment]
thanks for the help! all the best

**Comment by alebeta** [comment]
DJstone i already imported and i check about the contact duplication, and is not problem with duplicate contact. Everything was ok! thanks for all
