### ISSUE TITLE
address books no visible

### ISSUE THREAD

**Issue by weisseu** [owncloud/contacts#517]
From a certain number of address books in the settings, the first address books are no longer visible!

**Comment by irgendwie** [comment]
@jancborchardt @skjnldsv Any ideas on how to solve this in a nice looking way?

![2016-09-15-113628_239x244](https://cloud.githubusercontent.com/assets/8360698/18545269/b0239f78-7b38-11e6-9f90-6effa2393b40.png)

**Comment by skjnldsv** [comment]
Ooh! That's unfortunate! :/
And we got a problem too with the length of a name: 
![screen](https://cloud.githubusercontent.com/assets/14975046/18559873/8cc3254e-7b79-11e6-902f-dd9057eede4e.png)

**Comment by irgendwie** [comment]
For the length, we could crop them with simple dots and show the full title when hovering it?

**Comment by skjnldsv** [comment]
I would have suggested otherwise! :p 
Hide the 4 items of the menu with a 3 dot icon, and ellipse the name + show menu when hovering :)

**Comment by skjnldsv** [comment]
First step done, what do you think @irgendwie : 
![kazam_screencast_00001](https://cloud.githubusercontent.com/assets/14975046/18561821/b93317e4-7b81-11e6-91d4-7c79acd7dfc0.gif)

cc @DeepDiver1975

**Comment by Henni** [comment]
@skjnldsv does this also work on mobile?

**Comment by skjnldsv** [comment]
Almost. The switch when clicking the menu button make the whole menu appear so quickly, the delete icon is beeing clicked instead! :p 
On it!

**Comment by jancborchardt** [comment]
@skjnldsv it would be better if we can keep it in line with the other apps. That is, no hover effect. One action like sharing can be out of the menu, also as indicator.

**Comment by skjnldsv** [comment]
It would, but we're still confronted to the issue with the popup size and the orientation.

**Comment by jancborchardt** [comment]
With the popup size do you mean the actions popup? If you mean the list of address books (that is, the settings view), that should just scroll at some point. :)

**Comment by skjnldsv** [comment]
I mean the popup with actions. In the files app we have a big blank empty space to prevent the popup to go outside the window. It would be a shame to have to do the same on the addressbook list :)

**Comment by jancborchardt** [comment]
@skjnldsv the empty space is not only for the popup, it’s also to signify the end of the file list. ;)
Anyhow: We have 4 actions. Sharing we can show directly. That leaves us with 3 actions in the popover. I believe there’s enough space for that, since the »Address book name« input and the Import button are below.

Btw, it seems to be a side-effect of this PR that the icon-confirm button of the »Address book name« input is only shown on hover/focus. Can you fix that? :)

**Comment by skjnldsv** [comment]
What do you mean the "icon-confirm button"?

**Comment by weisseu** [comment]
Has a solution already been found for this problem?
![grafik](https://cloud.githubusercontent.com/assets/22213814/20969067/ac9e321a-bc87-11e6-978e-e61f76016821.png)
