### ISSUE TITLE
[App request] Insource

### ISSUE THREAD

**Issue by Mannshoch** [owncloud/contacts#522]
The Oposite of Outsourcing is In my Opinion Insourcing. And an App for that is what I would Like request.

A quiz game.
More and more I outsourced my own knowledge about the contacts on my Phone to my mobile phone and PC. Thats not in every situation a good Idea.

Please made a Quiz-game:

**Easy Question:**
-  Which Person is on this Photo?
-  Choose the Photo of this Person
-  Which Person(s) life in this town.

**Difficult Question:**
-  On which date does this Person has his Birthday?
-  Which Person life in this street.

**Realy Difficult Question**
-  Which Phone Number belongs tho this Person?
-  Enter the E-Mail address of this person

**Hardcor Questions**
-  Enter the Phone Numer of this Person
  -    +49 ***

**Comment by DeepDiver1975** [comment]
This is not really in scope of this app
