### ISSUE TITLE
Dirty problem with Video plugin enabled

### ISSUE THREAD

**Issue by tsumi** [owncloud/contacts#527]
[OC 6.0.4]

Hi,
i noticed that something (js/modernizr.custom.js, i think) add lots of CSS style to ```<html>``` tag ot the page:
```
<html class="ng-csp js flexbox flexboxlegacy canvas webgl no-touch geolocation draganddrop rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage svg inlinesvg smil svgclippaths texttrackapi track">
```
This usually has no impact (these class are not defined on CSS so no style are applied), BUT, if i enable "Video" 3rd party plugin (this should happen also with some other plugin) a .video CSS class is defined:
```
.video {
margin-top: 15px;
margin-left: 15px;
margin-bottom: 40px;
width: 200px;
height: 113px;
-moz-border-radius: 15px;
border-radius: 15px;
}
```

This set a width and height to ```<html>``` that cause a glitch in  "add contact photo from owncloud" popup positioning (it appear out of window top-left).

I'm not sure WHY these CSS style are applied to ```<html>``` but i think that they should be removed if not used in order to avout problems like this.

**Comment by jancborchardt** [comment]
This should be fixed, also the video plugin is kinda outdated. Closing hence.
