### ISSUE TITLE
Unable to add new contacts

### ISSUE THREAD

**Issue by dlford** [owncloud/contacts#529]
### Steps to reproduce
1.Go to Contacts app and click +
2.Fill out information
3.Reload page

### Expected behaviour
New contact is in list of contacts

### Actual behaviour
New contact is gone

### Server configuration
**Operating system**:
Ubuntu 16.04
*Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
7.0.8
*ownCloud version:** (see ownCloud admin page)
9.1.1
**Contacts version:** (see ownCloud apps page)
1.4.0.0
**Updated from an older ownCloud or fresh install:**
Fresh install
**Signing status (ownCloud 9.0 and above):**

no errors have been found

**List of activated apps:**

  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - mail: 0.6.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - documents
  - encryption
  - external
  - files_antivirus
  - files_external
  - gallery
  - ownnote
  - user_external
  - user_ldap

**The content of config/config.php:**
<pre><code>
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocoms5udiomu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/cloudStorageVolume",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Phoenix",
        "installed": true,
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "custom",
        "maintenance": false
    }
}
</pre></code>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
**Browser:**
Chrome
**Operating system:**
Ubuntu, and Windows 10
**CardDAV-clients:**
roundcube
#### Web server error log
no relevant output

#### ownCloud log (data/owncloud.log)
no relevant output

#### Browser log
<pre>
<code>
<b>Javascript Console:</b>

JQMIGRATE: Migrate is installed, version 1.4.0
dav.js?v=721e73c…:3641 PUT ***REMOVED SENSITIVE VALUE***/contacts/fc38760a-2c26-42c7-aa49-42c72c4d848b.vcf 412 (Precondition failed)send @ dav.js?v=721e73c…:3641callee$2$0$ @ dav.js?v=721e73c…:3156tryCatch @ dav.js?v=721e73c…:121invoke @ dav.js?v=721e73c…:294Gp.(anonymous function) @ dav.js?v=721e73c…:330onFulfilled @ dav.js?v=721e73c…:3737(anonymous function) @ dav.js?v=721e73c…:3726co @ dav.js?v=721e73c…:3722send @ dav.js?v=721e73c…:3134updateObject @ dav.js?v=721e73c…:3415updateCard @ dav.js?v=721e73c…:1799updateCard @ dav.js?v=721e73c…:1524update @ contact_service.js:159ctrl.updateContact @ contactDetails_controller.js:69fn @ VM1359:4$eval @ angular.js?v=721e73c…:16820(anonymous function) @ angular.js?v=721e73c…:23589(anonymous function) @ angular.js?v=721e73c…:26348forEach @ angular.js?v=721e73c…:321$$writeModelToScope @ angular.js?v=721e73c…:26346writeToModelIfNeeded @ angular.js?v=721e73c…:26339(anonymous function) @ angular.js?v=721e73c…:26333validationDone @ angular.js?v=721e73c…:26260processAsyncValidators @ angular.js?v=721e73c…:26243$$runValidators @ angular.js?v=721e73c…:26187$$parseAndValidate @ angular.js?v=721e73c…:26326$commitViewValue @ angular.js?v=721e73c…:26294(anonymous function) @ angular.js?v=721e73c…:26431(anonymous function) @ angular.js?v=721e73c…:18744completeOutstandingRequest @ angular.js?v=721e73c…:5804(anonymous function) @ angular.js?v=721e73c…:6081
dav.js?v=721e73c…:3649 Uncaught (in promise) Error: Bad status: 412(…)request.onreadystatechange @ dav.js?v=721e73c…:3649

<b>Network:</b>

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2016-11-03T04:41:17.837Z",
        "id": "page_3",
        "title": "***REMOVED SENSITIVE VALUE***index.php/apps/contacts/",
        "pageTimings": {
          "onContentLoad": 1022.0900000058464,
          "onLoad": 1121.2800000066636
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2016-11-03T04:49:44.116Z",
        "time": 143.81800000410294,
        "request": {
          "method": "PUT",
          "url": "***REMOVED SENSITIVE VALUE***/remote.php/dav/addressbooks/users/***REMOVED SENSITIVE VALUE***/contacts/fc38760a-2c26-42c7-aa49-42c72c4d848b.vcf",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "requesttoken",
              "value": "dDcBAERgAQk/BgMtcENeBAAFcSdVbiEhFVU0BQEfBQA=:GUXiq6isYb2XFs3CHw5N44CqfcRvRofcxBoars+zoic="
            },
            {
              "name": "Origin",
              "value": "https://***REMOVED SENSITIVE VALUE***"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch, br"
            },
            {
              "name": "Host",
              "value": "***REMOVED SENSITIVE VALUE***"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36"
            },
            {
              "name": "Content-Type",
              "value": "application/xml;charset=UTF-8"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0"
            },
            {
              "name": "Cookie",
              "value": "__unam=6f69f6a-157314646c4-1c072659-29; _ga=GA1.2.2141532475.1473892943; oc_sessionPassphrase=JQ01Y%2BAeMk42QIatd24j1eFhFvbPzO%2BB5WFD50mBcWmvQDtfz1VW2ilKSONstdLv9%2BwbTHs64BAVQyVbuFdGCvGrawa6xYtBmSlXcRCukJeE6h42ldzLtpqApRfDTsu%2F; ocoms5udiomu=8maijev7jb3gkue5r54o7e00g2"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "If-Match",
              "value": "null"
            },
            {
              "name": "Content-Length",
              "value": "143"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "__unam",
              "value": "6f69f6a-157314646c4-1c072659-29",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_ga",
              "value": "GA1.2.2141532475.1473892943",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "oc_sessionPassphrase",
              "value": "JQ01Y%2BAeMk42QIatd24j1eFhFvbPzO%2BB5WFD50mBcWmvQDtfz1VW2ilKSONstdLv9%2BwbTHs64BAVQyVbuFdGCvGrawa6xYtBmSlXcRCukJeE6h42ldzLtpqApRfDTsu%2F",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "ocoms5udiomu",
              "value": "8maijev7jb3gkue5r54o7e00g2",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 919,
          "bodySize": 143,
          "postData": {
            "mimeType": "application/xml;charset=UTF-8",
            "text": "BEGIN:VCARD\r\nVERSION:3.0\r\nFN:asdf\r\nUID:fc38760a-2c26-42c7-aa49-42c72c4d848b\r\nTEL;TYPE=HOME\\,VOICE:asdf\r\nREV:2016-11-03T04:49:44.111Z\r\nEND:VCARD"
          }
        },
        "response": {
          "status": 412,
          "statusText": "Precondition failed",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Thu, 03 Nov 2016 04:49:44 GMT"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "X-Permitted-Cross-Domain-Policies",
              "value": "none"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Strict-Transport-Security",
              "value": "max-age=15552000; includeSubDomains"
            },
            {
              "name": "Content-Length",
              "value": "312"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Server",
              "value": "Apache"
            },
            {
              "name": "X-Download-Options",
              "value": "noopen"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "Content-Type",
              "value": "application/xml; charset=utf-8"
            },
            {
              "name": "Cache-Control",
              "value": "no-store, no-cache, must-revalidate"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'none';"
            },
            {
              "name": "X-Robots-Tag",
              "value": "none"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=100"
            },
            {
              "name": "Expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            }
          ],
          "cookies": [],
          "content": {
            "size": 312,
            "mimeType": "application/xml",
            "compression": 0,
            "text": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\PreconditionFailed</s:exception>\n  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>\n  <s:header>If-Match</s:header>\n</d:error>\n"
          },
          "redirectURL": "",
          "headersSize": 616,
          "bodySize": 312,
          "_transferSize": 928
        },
        "cache": {},
        "timings": {
          "blocked": 0.713,
          "dns": 87.13300000000001,
          "connect": 5.152999999999992,
          "send": 0.08200000000000784,
          "wait": 49.879000000000005,
          "receive": 0.8580000041029336,
          "ssl": 3.4949999999999903
        },
        "serverIPAddress": "***REMOVED SENSITIVE VALUE***",
        "connection": "19749",
        "pageref": "page_3"
      },
      {
        "startedDateTime": "2016-11-03T04:49:48.758Z",
        "time": 61.53199999971548,
        "request": {
          "method": "GET",
          "url": "***REMOVED SENSITIVE VALUE***/ocs/v2.php/apps/notifications/api/v1/notifications?format=json",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Cookie",
              "value": "__unam=6f69f6a-157314646c4-1c072659-29; _ga=GA1.2.2141532475.1473892943; oc_sessionPassphrase=JQ01Y%2BAeMk42QIatd24j1eFhFvbPzO%2BB5WFD50mBcWmvQDtfz1VW2ilKSONstdLv9%2BwbTHs64BAVQyVbuFdGCvGrawa6xYtBmSlXcRCukJeE6h42ldzLtpqApRfDTsu%2F; ocoms5udiomu=8maijev7jb3gkue5r54o7e00g2"
            },
            {
              "name": "requesttoken",
              "value": "dDcBAERgAQk/BgMtcENeBAAFcSdVbiEhFVU0BQEfBQA=:GUXiq6isYb2XFs3CHw5N44CqfcRvRofcxBoars+zoic="
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch, br"
            },
            {
              "name": "Host",
              "value": "***REMOVED SENSITIVE VALUE***"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36"
            },
            {
              "name": "OCS-APIREQUEST",
              "value": "true"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [
            {
              "name": "format",
              "value": "json"
            }
          ],
          "cookies": [
            {
              "name": "__unam",
              "value": "6f69f6a-157314646c4-1c072659-29",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "_ga",
              "value": "GA1.2.2141532475.1473892943",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "oc_sessionPassphrase",
              "value": "JQ01Y%2BAeMk42QIatd24j1eFhFvbPzO%2BB5WFD50mBcWmvQDtfz1VW2ilKSONstdLv9%2BwbTHs64BAVQyVbuFdGCvGrawa6xYtBmSlXcRCukJeE6h42ldzLtpqApRfDTsu%2F",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "ocoms5udiomu",
              "value": "8maijev7jb3gkue5r54o7e00g2",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 805,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Thu, 03 Nov 2016 04:49:48 GMT"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "X-Permitted-Cross-Domain-Policies",
              "value": "none"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Strict-Transport-Security",
              "value": "max-age=15552000; includeSubDomains"
            },
            {
              "name": "Content-Length",
              "value": "74"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Server",
              "value": "Apache"
            },
            {
              "name": "X-Download-Options",
              "value": "noopen"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "Content-Type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "Cache-Control",
              "value": "no-store, no-cache, must-revalidate"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *"
            },
            {
              "name": "X-Robots-Tag",
              "value": "none"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=99"
            },
            {
              "name": "Expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            }
          ],
          "cookies": [],
          "content": {
            "size": 74,
            "mimeType": "application/json",
            "compression": 0,
            "text": "{\"ocs\":{\"meta\":{\"status\":\"ok\",\"statuscode\":200,\"message\":null},\"data\":[]}}"
          },
          "redirectURL": "",
          "headersSize": 751,
          "bodySize": 74,
          "_transferSize": 825
        },
        "cache": {},
        "timings": {
          "blocked": 0.836,
          "dns": -1,
          "connect": -1,
          "send": 0.08300000000000007,
          "wait": 60,
          "receive": 0.612999999715484,
          "ssl": -1
        },
        "serverIPAddress": "***REMOVED SENSITIVE VALUE***",
        "connection": "19749",
        "pageref": "page_3"
      }
    ]
  }
}
</code>
</pre>

**Comment by DeepDiver1975** [comment]
This is the error response - looks like a concurrent save operation.

Are you using a second client in parallel?

> "text": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n <s:exception>Sabre\DAV\Exception\PreconditionFailed/s:exception\n <s:message>An If-Match header was specified, but none of the specified the ETags matched./s:message\n <s:header>If-Match/s:header\n/d:error\n"

**Comment by dlford** [comment]
@DeepDiver1975 
I have CardDAV set up in roundcube webmail client but not logged into that when trying add contacts in OwnCloud, I also have CardDAVSync set up on Android and thought that might be the issue even though it only syncs once per day.  I tried turning off the phone and rebooting the server running OwnCloud but the issue still persists.

As it stands now, adding a contact in Roundcube or OwnCloud adds an empty contact that only shows up in Roundcube, but I am able to add contacts from the Android app CardDAVSync.

**Comment by DeepDiver1975** [comment]
not reproducible -> I'm closing this as of now. Please reopen as soon as more information is available. THX

**Comment by dlford** [comment]
@DeepDiver1975

What other information is needed?  I think this issue is a little beyond the scope of my understanding. I did my best to remedy it on my own before I opened this issue, I'll take another crack at it but I don't expect to find anything new.  Will let you know if anything changes.

**Comment by DeepDiver1975** [comment]
> What other information is needed?

I'd gladly tell you if I only would know :wink: - based on all the information in here I cannot make up my mind on what the issue could be.
It's sad and a pitty - but there is no much I can do right now - sorry

**Comment by dlford** [comment]
@DeepDiver1975

Gotcha, well I appreciate your efforts nonetheless, I'll let you know if anything changes.
