### ISSUE TITLE
Wrong mapping while syncing new contact from nextcloud to android

### ISSUE THREAD

**Issue by kangaroo72** [owncloud/contacts#530]
Ubuntu 16.04LTS + Nginx or Apache (latest)
PHP 7.08
MariaDB or MySQL

I only can speak for german entries:

Add a contact on nextcloud (10.01):

Duck, Donald (Name, Firstname)
+49 555 666666 Tel. Privat (Phone Home)
+49 666 777777  Tel. Arbeit (Phone Work)

When you sync this to an german android (via DavDroid) you'll get shown both entries as
"Festnetz" - you cannot divide, where you call - office or home

Everything is clean install. Contacts app is latest (1.4.0.0)
I cannot imagine, that I'm the only one is this big problem ...

Thanks,

Tom

**Comment by DeepDiver1975** [comment]
Can you please provide the vcard? Please anonymize data within - THX

**Comment by kangaroo72** [comment]
Hi and thanks for your help. The issue is also posted in nc-repo
[https://github.com/nextcloud/contacts/issues/32](url)

There I posted following vcard:

BEGIN:VCARD
VERSION:2.1
N:Duck;Donald;;;
FN:Donald Duck
TEL;PREF:0612399999999
TEL;PREF:069777777777
END:VCARD

I'll be very glad if someone can fix this. A working carddav for android/ios should be an amazing xmas-gift

Thanks,

Tom
