### ISSUE TITLE
Add T-Shirt Size Field

### ISSUE THREAD

**Issue by hodyroff** [owncloud/contacts#535]
There is a field "T-Shirt Size" or similar missing where people can add their cloth size so they can get a nice shirt, hoodie or whatever ... @felixboehm or did I miss a way to add fields?

**Comment by hodyroff** [comment]
https://github.com/owncloud/contacts/issues/234 seems a broader request to this, but I guess this one should be standard ;)

**Comment by DeepDiver1975** [comment]
There is no standard field for this so it is necessary to create a custom file as requested in #234.

I'm closing this one in favor of the more general approach
