### ISSUE TITLE
OC7RC1: Import of contacts only imports one category

### ISSUE THREAD

**Issue by Larx** [owncloud/contacts#537]
I have many contacts which are assigned to several categories. When importing them into OC7RC1, only one category of those remains; the others are lost. 
This happens both when importing a *.vcf file or when using a CardDAV-software (KDE's kaddressbook in my case) to move contacts from one server to another.

Additional categories can, however, be assigned later on to this contact with the web interface of OC's contact app, so this does not seem to be a general restriction to only one category.

**Comment by babelouest** [comment]
this bug is probably fixed by now, lots of PR referencing this problem went through, like #903, I'm closing it now
