### ISSUE TITLE
Contacts 1.5.0 shows a blank page.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/contacts#537]
Just tested contacts 1.5.0 (master) with current master and 9.1.3RC1. Both enterprise and community. Not working. It just shows an empty page:

![screen shot 2016-11-30 at 17 52 36](https://cloud.githubusercontent.com/assets/9048796/20762190/e00b8a6a-b725-11e6-8ce3-797cced2ef07.png)

**Comment by nasli** [comment]
related https://central.owncloud.org/t/contacts-1-5-0-is-about-to-arrive/4259

**Comment by SergioBertolinSG** [comment]
My mistake, didn't run make.
