### ISSUE TITLE
Addressbook share icon doesnt show in Firefox or safari

### ISSUE THREAD

**Issue by tomneedham** [owncloud/contacts#54]
Hover over an addressbook in firefox of safari and the sharing icon does not appear. Similar issue appeared in Calendar-rework so need to look at how it got fixed. I had a suspicion that it was related to adblockers removing it - not sure if there is any merit in this

**Comment by jancborchardt** [comment]
- [ ] clicking on the share icon should not only show the share box, but also focus it with the cursor
- [ ] the suggestion dropdown should overlay the content below, not move the whole thing up like now
- [ ] remove the dash behind the name in the list

**Comment by irgendwie** [comment]
@tomneedham Icon is shown on firefox for me, issue still present?

**Comment by skjnldsv** [comment]
Same here, don't have this issue.

**Comment by skjnldsv** [comment]
@tomneedham still occurring? Can we close?

**Comment by DeepDiver1975** [comment]
works for me in FF45
