### ISSUE TITLE
Version 1.5.0 in app store config?

### ISSUE THREAD

**Issue by mm28ajos** [owncloud/contacts#547]
While installing the app it reads version 1.5.0 is going to be installed but I get the following error message:

> App can't be installed because the version in info.xml is not the same as the version reported from the app store

Might it be necessary to update the app store version config to 1.5.1 to fix this or is the app store still delivering version 1.5.0?

Running oc 9.1.1.

**Comment by urquhartwebsystems** [comment]
Having the same issue with the same error message here.

**Comment by guakamole** [comment]
Exact same error when I try to update from 1.4.0 to 1.5.0.

**Comment by tepung** [comment]
same error here 
"App can't be installed because the version in info.xml is not the same as the version reported from the app store "

- tested with oc 9.1.2 and nc 10.0.1

**Comment by lachlan-00** [comment]
broken with 1.5.1 as well now. i tried to manually install and it broke the database

**Comment by DeepDiver1975** [comment]
Please try again - there was a miss-config in the app store - my fault. I'm sorry

**Comment by SpacyNG** [comment]
Thanks that fixed it. The package.json in github still shows 1.5.0 (if that was the problem)

**Comment by Wikinaut** [comment]
fixed. thanks.

**Comment by tepung** [comment]
fixed in oc 9.1.2 and nc 10.0.1, thank you ..
