### ISSUE TITLE
Version 1.5.1 missing js/vendor and more

### ISSUE THREAD

**Issue by milesgillham** [owncloud/contacts#548]
### Steps to reproduce
1. git clone https://github.com/owncloud/contacts.git
2. Let upgrade run
3. Attempt to connect to contacts app

### Actual behaviour
Blank screen

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache 2.6.0

**Database:**
MariaDB 10

**PHP version:**
5.6.28

**ownCloud version:** (see ownCloud admin page)

**Contacts version:** (see ownCloud apps page)
1.5.1

**Updated from an older ownCloud or fresh install:**
From previous latest 1.4.x

Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: 1.5.1
  - dav: 0.2.7
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - afterlogic
  - audioplayer
  - bookmarks-
  - contacts-
  - encryption
  - external
  - files_antivirus
  - files_external
  - firstrunwizard
  - galleryplus
  - mail-
  - notes
  - rainloop
  - tasks-
  - user_external
  - user_ldap

#### ownCloud log (data/owncloud.log)
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/ngclipboard/dist/ngclipboard.min.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/clipboard/dist/clipboard.min.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/public/script.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/ui-select/dist/select.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-uuid4/angular-uuid4.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular-route/angular-route.js"	2016-12-06T12:40:00+10:00
Error	contacts	Could not find resource file "/owncloud/apps/contacts/js/vendor/angular/angular.js"	2016-12-06T12:40:00+10:00

**Comment by DeepDiver1975** [comment]
Please follown the build instructions.  You need to run make.
