### ISSUE TITLE
Feature: Add Mass import

### ISSUE THREAD

**Issue by sedrubal** [owncloud/contacts#554]
### Steps to reproduce
1. In Webapp click on <kbd>⚙ Settings</kbd>
2. Click on <kbd>⬆️ Import</kbd>
3. Try to select multiple vCards

### Expected behaviour
It should be possible to upload many vCards at once.

### Actual behaviour
It is only possible to import only one file.

### Server configuration
**ownCloud version:** `9.1.2`
**Contacts version:** `1.4.1`

**Comment by DeepDiver1975** [comment]
If your browser allows selection of multiple files this should work from my understanding

**Comment by sedrubal** [comment]
I have Mozilla Firefox 50.0.2 which supports uploading multiple files.
