### ISSUE TITLE
don't shows all contacts

### ISSUE THREAD

**Issue by ikarus13** [owncloud/contacts#556]
### Steps to reproduce
Update nextcloud 10.0.1 to 10.0.2
2.
3.

### Expected behaviour
The members of all groups should be shown in all contacts

### Actual behaviour
 After update nextcloud from 10.0.1 to 10.0.2 contacts 1.5.1 dont show contacts in "all contacts"
I have group my contacts in 5 groups. Only the members of 2 groups are shown.
There where no members in "all contacts"
No errors in nextcloud log
The url from categories which are shown looks like:
owncloud/index.php/apps/contacts/#/Sonstiges?uid=C5EF7027-E540-0001-8A62-1A788A321EEE

The categories not shown looks like:
/owncloud/index.php/apps/contacts/#/Familie

So, there is no uid, maybe this is a hint.

### Server configuration
**ubnutu  16.04.1 LTS**:
**apache 2.4.18-2ubuntu3.1 amd64 :**

**Database:**
Type: mysql
Version: 5.7.16

**PHP version:**
Version: 7.0.8

**ownCloud version:** (see ownCloud admin page)
10.0.2

**Contacts version:** (see ownCloud apps page)
1.5.1
**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - audioplayer: 1.3.1
  - calendar: 1.4.1
  - contacts: 1.5.1
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - news: 9.0.4
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.5
  - survey_client: 0.1.5
  - templateeditor: 0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - gallery
  - systemtags
  - theming
  - user_external
  - user_ldap
  - user_saml
```
**The content of config/config.php:**
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "513ef09ca9cb5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/html\/owncloud_data",
        "overwrite.cli.url": "\/var\/www\/html\/owncloud",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "version": "9.1.2.2",
        "installed": true,
        "loglevel": 1,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/apache2\/nextcloud.log",
        "log_rotate_size": 5242880,
        "logtimezone": "Europe\/Berlin",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "trusted_domains": [
            "dbis-cloud.uni-muenster.de",
            "dbis-cloud"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.uni-muenster.de",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "dbis-konf",
        "mail_domain": "uni-muenster.de",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"

using external storage, if yes which one:** local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 50.0.2
**Operating system:**
Ubuntu 16.04
**CardDAV-clients:**
Thunderbird adressbook
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ikarus13** [comment]
After update to 1.5.2 it works fine.

**Comment by DeepDiver1975** [comment]
> After update to 1.5.2 it works fine.

let's close this then - THX - have fun
