### ISSUE TITLE
Enabling LDAP breaks owncloud

### ISSUE THREAD

**Issue by wtayyeb** [owncloud/contacts#557]
Hi.
I dont know what is LDAP! but in admin page when I mistakenly click on  **Enable LDAP backend** checkbox my owncloud instance die! and throw this error on every page :
{"app":"PHP","message":"syntax error, unexpected T_OBJECT_OPERATOR at \/www\/owncloud\/apps\/contacts\/lib\/backend\/ldap.php#607","level":3,"time":"2014-07-25 00:41:50"}

and I have to disable it from phpmyadmin to return owncloud working.

**Comment by blizzz** [comment]
Original issue was solved.
