### ISSUE TITLE
address book import does not work properly

### ISSUE THREAD

**Issue by tbeitter** [owncloud/contacts#566]
First, it's not consistent how the import is solved in the UI:

Address Book:
1) Import via "Contacts" app > Settings > Import
2) Import via a previously uploaded VCF file in the "Files"-App

Calendar:
Import only via click on a previously uploaded ICS file in the "Files"-App

Second, if importing via "Files"-App the progress bar is broken:

Address Book:
After choosing the Address Book to import I see the progress bar "Importing..." until I reload the page. The progress bar is animated but there is no progress and no "Finished" message. If I reload the page after some time no contacts were added.

**Comment by Raydiation** [comment]
Oh man, Sti still not fixed? Got hit again by this bug today for the second time

**Comment by Raydiation** [comment]
Guys, please review  #915

**Comment by Raydiation** [comment]
And test ofc ;)

**Comment by babelouest** [comment]
@Raydiation , it works for me, clean and sharp, thanks :)

Can you check #906 while we're into code review ? I'd like to submit this for next release if possible.
