### ISSUE TITLE
restore contacts (mysql - sqlite)

### ISSUE THREAD

**Issue by 466** [owncloud/contacts#571]
Using mysql database for owncloud, where does this app save the contacts to?

I had to reinstall everything from scratch, choosing sqlite3 over mysql results in having no contacts anymore ... . 
As i do have my database directory (/var/lib/mysql) from my previous installation, is there an easy way, getting my contacts back?

**Comment by DeepDiver1975** [comment]
Connect to the mysql database and query for the information like this:

```sql
select carddata from oc_cards

**Comment by 466** [comment]
Thanks for your reply, seems i still got a problem left ... .
Any ideas?
Selecting carddata:
> mysql> select carddata from oc_cards;
ERROR 1146 (42S02): Table 'cloud.oc_cards' doesn't exist

> mysql> select carddata from oc_calendar_objects;
ERROR 1146 (42S02): Table 'cloud.oc_calendar_objects' doesn't exist


These are the tables, stored in database "cloud"
> mysql> SHOW TABLES;
+-----------------------------------+
| Tables_in_cloud                   |
+-----------------------------------+
| oc_activity                       |
| oc_activity_mq                    |
| oc_addressbookchanges             |
| oc_addressbooks                   |
| oc_appconfig                      |
| oc_authtoken                      |
| oc_calendarchanges                |
| oc_calendarobjects                |
| oc_calendars                      |
| oc_calendarsubscriptions          |
| oc_cards                          |
| oc_cards_properties               |
| oc_comments                       |
| oc_comments_read_markers          |
| oc_credentials                    |
| oc_dav_shares                     |
| oc_documents_invite               |
| oc_documents_member               |
| oc_documents_op                   |
| oc_documents_revisions            |
| oc_documents_session              |
| oc_external_applicable            |
| oc_external_config                |
| oc_external_mounts                |
| oc_external_options               |
| oc_federated_reshares             |
| oc_file_locks                     |
| oc_filecache                      |
| oc_files_trash                    |
| oc_group_admin                    |
| oc_group_user                     |
| oc_groups                         |
| oc_jobs                           |
| oc_mimetypes                      |
| oc_mounts                         |
| oc_notifications                  |
| oc_ocsms_config                   |
| oc_ocsms_conversation_read_states |
| oc_ocsms_sendmessage_queue        |
| oc_ocsms_smsdatas                 |
| oc_ocsms_user_datas               |
| oc_ownnote                        |
| oc_ownnote_parts                  |
| oc_passwords                      |
| oc_passwords_categories           |
| oc_passwords_share                |
| oc_polls_comments                 |
| oc_polls_dts                      |
| oc_polls_events                   |
| oc_polls_notif                    |
| oc_polls_particip                 |
| oc_polls_particip_text            |
| oc_polls_txts                     |
| oc_preferences                    |
| oc_privatedata                    |
| oc_properties                     |
| oc_schedulingobjects              |
| oc_share                          |
| oc_share_external                 |
| oc_storages                       |
| oc_systemtag                      |
| oc_systemtag_group                |
| oc_systemtag_object_mapping       |
| oc_trusted_servers                |
| oc_users                          |
| oc_vcategory                      |
| oc_vcategory_to_object            |
+-----------------------------------+
67 rows in set (0,00 sec)

**Comment by DeepDiver1975** [comment]
Please seek out for help at https://central.owncloud.org - THX
