### ISSUE TITLE
Cannot create or import contacts

### ISSUE THREAD

**Issue by Peweuk** [owncloud/contacts#572]
I have just installed Owncloud 9.1.3 and activated the Contacts app.

When I go to 'Contacts' the loading wheel just keeps spinning.
If I try to create a new contact - nothing happens.
If I go to import an addressbook, after I select a ,vcf file on the pc - nothing happens.

There are no errors in the log so I can't see what might be going wrong.

![image](https://cloud.githubusercontent.com/assets/10102600/22400228/058ee5d4-e5a7-11e6-93ba-17797332717e.png)

**Comment by DeepDiver1975** [comment]
Any errors in the browser error console?
Which version of contatcs are you using?

**Comment by Peweuk** [comment]
Hi DD.

I am using V 1.5.1 of contacts - which is installed automatically by OC when I activate it on the site (use the apps panel for this as I am on a shared server).

Strangely, when I went to the site to check the web console after seeing your message I found that the page loaded OK this time and I was able to import contacts.
However, when the import started I had 2 lines of errors appear at the top of the page saying 'Unable to import contact' with no reference to which one.
On completion of the import I had 2 less than I should have showing in the total addresses in the Addressbook, and on checking the Log found 2 errors reporting problems with the import.
Although these state the error was with Webdav, they appeared in the log at the time of the import

![image](https://cloud.githubusercontent.com/assets/10102600/22421174/e2d37798-e6dd-11e6-88af-d48212d8c1f4.png)

I then went back to the contacts page and found 'all' the contacts had imported, despite the errors.

When I check the web console there is an error warning which appears a multitude of times - here is a snippet

![image](https://cloud.githubusercontent.com/assets/10102600/22421240/244ce07e-e6de-11e6-95e1-c154e33966a1.png)

On completion of the above actions I setup a sync for the contacts in Thunderbird and added a contact in Thunderbird, resynced and it was added to OC.
I then made an alteration to a contact and resynced and once agin the changes were reflected in Owncloud.

So I am at a loss.

I re-installed Owncloud on the server at least 4 times and each time the vcf import failed.
This morning it worked with errors displayed, but no actual errors appearing in the contacts list.

So now I wonder - has it somehow miraculously fixed itself, or should I be wary of future issues arising!!!!!

Time for a coffee and a lie down in a dark room I feel ;)

**Comment by DeepDiver1975** [comment]
How many contacts are there in your addressbooks?

**Comment by Peweuk** [comment]
In the addressbook I imported there are only 74.
When I first imported the list showed 72 at the bottom of the list before I went to the admin/log section.
On returning from admin to the contacts section it was showing 74 in the addressbook and they were all there.

**Comment by Peweuk** [comment]
It is weird though - because I had OC9.1.1 working perfectly on a hosted server where it worked for quite some time.
Suddenly I had page load errors and tried to re-install - but continued to get page load errors and contacts would not import.
The host was most unhelpful so I moved to my current host last week and after installing OC 9.1.3 I could not import contacts.
I tried OC 9.1.1 on the new server and still could not import contacts.
Until this morning when suddenly 9.1.3 was able to import - but with the errors above.

**Comment by DeepDiver1975** [comment]
I guess you are facing a combination of issues:
- the amount of contacts is putting quite some load on your sever and causes a long waiting time for you
- while not all contacts are loaded any attempt to create a new contacts or import them causes further confusion

The initial loading is really painful at the moment - we need to work on this.

**Comment by Peweuk** [comment]
Thanks DD.

I am surprised that you say that 74 contacts is putting a load on the server. I always thought (comparatively speaking) that was a low number. My other address book (which I also always thought was small) has over 300 names in it.
The other reason I am surprised is that I also installed Nextcloud on the same server, and although that uses a later version of the contacts app (1.5.2) the page loaded quickly and the import of the same file was virtually instantaneous.

Anyway, I am no coder and I bow to your greater knowledge and thank you for your assistance.

**Comment by Peweuk** [comment]
I have just found an error which has appeared in the log

- contacts
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

This is new.

**Comment by DeepDiver1975** [comment]
> I have just found an error which has appeared in the log

This is most probably because you mixed the contacts apps and the server as of owncloud and nextcloud.

**Comment by Peweuk** [comment]
Would there be any information which may cause this error held in the database or anywhere other than the in the Apps/Contacts directory?

Before running the currently used version (1.5.1) I had disabled the contacts app in admin, then uninstalled it in admin and finally checked using ftp to ensure that the apps/contacts directory was gone. I then re-installed the app using admin - so all the files should be those downloaded and installed by OC.

**Comment by Peweuk** [comment]
OK.

There had been a few issues with this instal so I decided to try again and did a completely new install of OC in a different directory.
This time everything went OK the first time round and I now have my contacts (and calendar/tasks) all imported and sync'e with my PC/Phone.

All I have to do now is delete the original directory and see if I can rename the new one to get back to consistency.

Thanks for all your help.

**Comment by DeepDiver1975** [comment]
> Thanks for all your help.

You are welcome - is was not that much :wink: 

Please let us know if we can close the ticket - THX

**Comment by Peweuk** [comment]
Yup - closed.
Thanks again
