### ISSUE TITLE
Google GMail import not working properly

### ISSUE THREAD

**Issue by thedd** [owncloud/contacts#574]
When i try to import my GMail contacts (via the GMail csv format) then alle the Phone numbers are not imported.
Also multiple E-Mail addresses are not correctly imported. e.g. test@mail.com ::: test2@mail.com
The address field has also some issues when importing, but I can live with that.

**Comment by babelouest** [comment]
I think this is fixed by now, #903 and other PR have solutions for multiple values imported in one property. I will close this issue but if the problem remains, you can reopen it.
