### ISSUE TITLE
ImportVCardConnector::convertElementToVCard does not import multiple groups

### ISSUE THREAD

**Issue by clanganke** [owncloud/contacts#579]
In OC 7.0, if a given VCard specifies a list of CATEGORIES, it does does not import all of the groups of a given contact properly, instead only the last one is added to the imported contact.

ImportVCardConnector::convertElementToVCard checks for special handling for each property, being configured by import_entry config elements. AFAIU if a sub element vcard_favourites is defined, but the property name does not match the examined property, the line

     $this->updateProperty($property, $importEntry, trim($oneValue));

is executed, and if vcard_favourites is not even defined, the line

    $this->updateProperty($property, $importEntry, $sourceProperty->value);

gets executed. In both cases these lines get executed once for each entry in the CATEGORIES list, setting the property to exactly one value. For properties specifying a list, such as CATEGORIES, only the last value in the list is imported, and the others are lost. To avoid that, the array having been split up before the check loop must be rejoined with the remaining entries before setting the property list at the end.

For now I just helped myself with a patch, by adding the line

    $dest->CATEGORIES = $source->CATEGORIES;

at the end of the method, just before the call to $dest->validate, but of course I would not want to break the otherwise meaningful scheme of the VCard connector config.

**Comment by babelouest** [comment]
This was fixed by some PR like #903, I'm closing it but if the problem remain you can reopen it.
