### ISSUE TITLE
 PROPFIND responses contain doubly encoded hrefs

### ISSUE THREAD

**Issue by untitaker** [owncloud/contacts#581]
See https://github.com/fruux/sabre-dav/issues/498. I am testing this from ownCloud 7.0.1, but the bug also occurs with version 6.0.3. The problematic code in ownCloud is also linked there.

Versions affected:

* ownCloud 7.0.1
* ownCloud 6.0.3
* ownCloud 8.0.4

*Below is the copy-pasted issue*

---

When uploading a VCARD file into an addressbook where the filename contains special characters such as ``@``, the URL to use for the PUT request has the ``@`` encoded as ``%40``:

    PUT http://127.0.0.1:8080/remote.php/carddav/addressbooks/asdf/test/0.900055620659%40vdirsyncer.vcf
    Headers: {'If-None-Match': '*', 'Content-Type': 'text/vcard', 'User-Agent': 'vdirsyncer'}
    Request body:

    BEGIN:VCARD
    VERSION:3.0
    FN:Cyrus Daboo
    N:Daboo;Cyrus
    ADR;TYPE=POSTAL:;2822 Email HQ;Suite 2821;RFCVille;PA;15213;USA
    EMAIL;TYPE=PREF:cyrus@example.com
    NICKNAME:me
    NOTE:Example VCard.
    ORG:Self Employed
    TEL;TYPE=VOICE:412 605 0499
    TEL;TYPE=FAX:412 605 0705
    URL:http://www.example.com
    X-SOMETHING:0.900055620659@vdirsyncer
    UID:0.900055620659@vdirsyncer
    END:VCARD

    Status Code: 201

So I do that, and when fetching the contact list via an addressbook-query, it gives me back the correct href. The problem arises when using PROPFIND instead of ``addressbook-query``/REPORT to list all items of a collection:

    PROPFIND http://127.0.0.1:8080/remote.php/carddav/addressbooks/asdf/test/
    Headers: {'Depth': 1, 'Content-Type': 'application/xml; charset=UTF-8', 'User-Agent': 'vdirsyncer'}
    Request Body:

    <?xml version="1.0" encoding="utf-8" ?>
                <D:propfind xmlns:D="DAV:">
                    <D:prop>
                        <D:resourcetype/>
                        <D:getcontenttype/>
                        <D:getetag/>
                    </D:prop>
                </D:propfind>
                
    Status Code: 207

    Response Body:
    <?xml version="1.0" encoding="utf-8"?>
    <d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav">
        <d:response>
            <d:href>/remote.php/carddav/addressbooks/asdf/test/</d:href>
            <d:propstat>
                <d:prop>
                    <d:resourcetype>
                    <d:collection/>
                    <card:addressbook/>
                    </d:resourcetype>
                </d:prop>
                <d:status>HTTP/1.1 200 OK</d:status>
            </d:propstat>
            <d:propstat>
                <d:prop>
                <d:getcontenttype/>
                <d:getetag/>
                </d:prop>
                <d:status>HTTP/1.1 404 Not Found</d:status>
            </d:propstat>
        </d:response>
        <d:response>
            <d:href>/remote.php/carddav/addressbooks/asdf/test/0.900055620659%2540vdirsyncer.vcf</d:href>
            <d:propstat>
                <d:prop>
                    <d:resourcetype/>
                    <d:getcontenttype>text/x-vcard; charset=utf-8</d:getcontenttype>
                    <d:getetag>"e7f5e1496c31d22f39fed9b4f0f50211"</d:getetag>
                </d:prop>
                <d:status>HTTP/1.1 200 OK</d:status>
            </d:propstat>
        </d:response>
    </d:multistatus>

In the response body, ``@`` is URL-encoded twice, making it ``%2540`` instead of the expected ``%40``.

**Comment by untitaker** [comment]
This bug is still present in ownCloud 8. Any updates on this?

**Comment by rfc2822** [comment]
This bug causes problems for many DAVdroid users since DAVdroid 0.8.1+ handles encoding correctly now.

Is there any way to assist in fixing this?

**Comment by untitaker** [comment]
Another issue I've found is:

* Create item with href containing `%20` (space)
* Send the same PROPFIND request to list all contacts of a collection (see OP)
* Instead of `%20`, `%2B` (plus sign) is used.

This bug doesn't happen with the calendar app I think.

**Comment by derkostka** [comment]
@PVince81 can you help communicating this is a Problem ?

**Comment by childnode** [comment]
:information_source:  fix 484fce0 seems to be scheduled for owncloud 8.2 release https://github.com/owncloud/contacts/releases/tag/v0.5.0.0 :zzz:
