### ISSUE TITLE
Request: CLI Contact Import

### ISSUE THREAD

**Issue by oraclesod** [owncloud/contacts#584]
I'm in need of a way to be able to query / add / update / remove contacts via the command line.
Or at least export per user contacts. So i can use another script to query / add / remove / update and then re-import and replace the original contact list.

Perhaps something where the contacts are imported/exported with CSV ?

**Comment by DeepDiver1975** [comment]
I see this more as a request to the backend -> https://github.com/owncloud/core/issues/new
