### ISSUE TITLE
Request:Auto importing/populating addressbook from the phone contacts to owncloud

### ISSUE THREAD

**Issue by Dr34ml4and3r** [owncloud/contacts#586]
Right now , you have to manually export contacts from your phone and import in Owncloud Contacts.
For example,on google contacts service when the phone connect to the service for the first time, all the contacts from the phone are saved/imported automatically , so it populates the new empty addressbook from google.
Can you have also this feature on owncloud?
Or is it a bug?
Thank you!

**Comment by DeepDiver1975** [comment]
I see no way to do this. ownCloud exposes a carddav interface and any client can connect.
If the phone (being the carddav client) cannot provide such a service there is not much we can do on the server side. Sorry
