### ISSUE TITLE
One-letter groups created, also not showing in contact

### ISSUE THREAD

**Issue by ojob** [owncloud/contacts#589]
Hi to All,
I've created new contacts, and have set them to new groups. Most often this works, but sometimes (~30% ?) I have two defaults:

  1. New groups are created as an explode of the name of the group I wanted to create, e.g. I wrote "Kayak" and I obtain "K", "a", "y", "a", and "k".
  2. The new Contact is created, and visible under all these groups, including the intended one. But these groups are most often not visible under in the Group field of this contact. In some cases I can see these groups, though, so I can make some clean-up, but this is pretty rare.

This results in a mess in Group list, and some Contacts not correctly assigned to Groups. As there is no way to assign Contacts to Groups in a grouped manner, I see no way to correct the assignment, i.e. I have no workaround this issue.

This arose with latest stable updates (ownCloud 9.0.8; Contacts 1.5.1); I did not have this problem before.

Thanks for your help.
Joël

### Steps to reproduce

1. Select a group
2. Create a new contact and set some values in fields
3. Open another Contact

### Expected behaviour

Most often (60% ?), the behaviour is as expected:

- The new Contact appears in the Group.
- In the new Contact, the selected Group appears in Group field.

### Actual behaviour

Not always (and cannot find a rule for that), the behaviour is as follows:

- The group in Step 1 does contain the new contact (that's ok)
the new contact (that's 
- New groups are created, named by explode of Selected group name (e.g. "Kayak" -> "K", "a", "y", "a", "k"), all containing the Contact
- The 'groups' field in the Contact is empty (but selection list does not contain the linked groups).

See capture below: Group selection is "F", that was created automatically when I tried to associate Contact "Alex DXXX". This same contact is visible under groups "Famille", "F", "a", "m", etc.
![capture d ecran_2017-04-17_12-47-17](https://cloud.githubusercontent.com/assets/1648261/25087163/4356ccc0-236d-11e7-8cee-5d7cf476d68b.png)

### Server configuration
**Operating system**:
Unknown

**Web server:**
Apache, but version unknown

**Database:**
MySQL

**PHP version:**
php 5.6

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.8 (stable)

**Contacts version:** (see ownCloud apps page)
Contacts 1.5.1

**Updated from an older ownCloud or fresh install:**
Updated from older version.

**Signing status (ownCloud 9.0 and above):**
"No errors have been found."

**List of activated apps:**
[I copied this list from the Application page, and deleted the extra sentences by myself, so some entries may be missing.]

Activity 2.2.1
Admin Config Report 0.1.1
Collaborative tags 0.2
Comments 0.2
Deleted files 0.8.0
Federation 0.0.4
First Run Wizard 1.1
Full Text Search 0.7.0
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8.1
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Video player 0.9.8
Calendar 1.4.1
Contacts 1.5.1
Documents 0.12.1
File Locking
Gallery+ 15.1.1
OwnNote 1.08
Video Viewer 0.1.3

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'ocpmddym7kp2',
  'passwordsalt' => XXXXXXXXXX,
  'secret' => XXXXXXXXXX,
  'trusted_domains' => 
  array (
    0 => 'bourgault.fr',
  ),
  'datadirectory' => '/var/www/vhosts/bourgault.fr/httpdocs/data/data',
  'overwrite.cli.url' => 'http://bourgault.fr/data',
  'dbtype' => 'mysql',
  'version' => '9.0.8.2',
  'dbname' => XXXXXXXXXX,
  'dbhost' => 'sql01.ouvaton.coop',
  'dbtableprefix' => XXXXXXXXXX,
  'dbuser' => XXXXXXXXXX,
  'dbpassword' => XXXXXXXXXX,
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => XXXXXXXXXX,
  'mail_smtpmode' => XXXXXXXXXX,
  'mail_domain' => XXXXXXXXXX,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:**
No

**Are you using encryption:** 
Yes

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:**
Firefox 52, Chrome

**Operating system:**
Ubuntu, Windows7, Android 6

**CardDAV-clients:**
Webclient throught ownCloud Contact app
CardDAV-Sync free on my android phone (which seems not to retrieve / take care of groups)

#### Web server error log
No access (shared server)

#### ownCloud log (data/owncloud.log)
[owncloud.log.zip](https://github.com/owncloud/contacts/files/925388/owncloud.log.zip)

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by willem2668** [comment]
+1

**Comment by falcongoat** [comment]
+1
