### ISSUE TITLE
Ubuntu 16.04 official repositories contains owncloud 10, but still older contacts

### ISSUE THREAD

**Issue by wolfen351** [owncloud/contacts#593]
So the title says it all.. owncloud 10 seems to be have been opened for general release yesterday, I apt-get updated my machine, and i'm stuck where contacts is concerned - the repo seems to contain older contacts package.

### Steps to reproduce
1. Use ubuntu 16.04
2. Upgrade to owncloud 10 - see contacts not upgraded
3. unable to disable maintenance mode

### Expected behaviour
Upgrade of owncloud should be seamless. (The occ commands are annoying anough, when you are just doing server maintenance)

### Actual behaviour
Stuck in maintenance mode, because contacts app cannt be updated

### Server configuration
Ubuntu 16.04 LTS
Apache 
MySQL

**Comment by wolfen351** [comment]
`
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled.
Repair warning: please install app manually with tarball or disable them
occ app:disable contacts
OC\RepairException: Upgrade is not possible
Update failed
Maintenance mode is kept active
Reset log level
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

                                                                                                                               
  [Exception]                                                                                                                  
  App "Contacts" cannot be installed because the following dependencies are not fulfilled: ownCloud 9.2 or lower is required.  
                                                                                                                               

app:enable [-g|--groups GROUPS] [--] <app-id>
`

**Comment by DeepDiver1975** [comment]
@wolfen351 please disable the contacts app as advised, perform the upgrade to oc10 and next install the new contacts version from the market app.
