### ISSUE TITLE
Allow events/hooks to trigger other apps

### ISSUE THREAD

**Issue by Schack17** [owncloud/contacts#594]
Allow events/hooks to trigger other apps on create, change or delete contacts.
Usecase: Trigger a change and export the changed contact to an external phonebook. Fritz!Box as example.

**Comment by DeepDiver1975** [comment]
this request has to go into core because the contacts app only holds the front end.

but good news these hooks already exist - e.g. https://github.com/owncloud/core/blob/master/apps/dav/lib/CardDAV/CardDavBackend.php#L529

**Comment by Schack17** [comment]
Great. Thanks @DeepDiver1975 .
Have you a documentation for me how to use this hook?

**Comment by DeepDiver1975** [comment]
> Have you a documentation for me how to use this hook?

documentation and comments lie - the truth is only in code ;-)

sorry - this is not really documented - please have a look at the pointed code locations - in case of questions feel free to reach out to me.

Take care
