### ISSUE TITLE
From tine20 to owncloud

### ISSUE THREAD

**Issue by guettli** [owncloud/contacts#597]
Up to now I host my contacts in tine20.

I would like to switch to owncloud.

I could not find a migration guide.

It would be very kind, if someone could provide the basic steps how to transfer the contacts
from tine20 to owncloud.

Thank you.

**Comment by DeepDiver1975** [comment]
No idea if tine has an export function to export contacts/addressbooks as vcards. but with the contacts app you can import vcard.

maybe this helps.

for further discussion please join https://central.owncloud.org/ - thx

**Comment by guettli** [comment]
Just for the records, I found a solution, and posted it here: https://android.stackexchange.com/a/176960/40698
