### ISSUE TITLE
Handle not existing .well-known gracefully

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#6]
I'm running owncloud with the php integrated web server and .htaccess is not supported.
As a result .well-known is not know - this results in fatal error

![bildschirmfoto von 2015-11-17 12-28-44](https://cloud.githubusercontent.com/assets/1005065/11210209/c42fb656-8d26-11e5-9c46-6599f5576322.png)

**Comment by Henni** [comment]
Even though this error shows up in the console it should still work.
So if I understand correctly your request is to get rid of the message in the console. Is this correct?

**Comment by DeepDiver1975** [comment]
> So if I understand correctly your request is to get rid of the message in the console. Is this correct?

I had the impression it is not working - but it is working.

Sorry for the noise
