### ISSUE TITLE
Contacts not working on fresh install

### ISSUE THREAD

**Issue by KhaosFarbauti** [owncloud/contacts#620]
### Steps to reproduce
1. Fresh owncloud install
2. Install contacts via market in owncloud
3. Go to Contacts tab

### Expected behaviour
Normal contacts page with new/import button

### Actual behaviour
"Partial" contacts page : No new button, no import button
Only a settings button on bottom left without any option in it

### Server configuration
**Operating system**: Wheezy
**Web server:** Apache
**Database:** MariaDB 10.0
**PHP version:** PHP 7.1

**ownCloud version:** (see ownCloud admin page) 10.0.2 (Community)

**Contacts version:** (see ownCloud apps page) 1.5.3

**Updated from an older ownCloud or fresh install:** fresh install

**Signing status (ownCloud 9.0 and above):** Community free

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Standard, only default install apps + Contacts

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

$CONFIG = array (
  'instanceid' => 'ociqw2xv9tky',
  'passwordsalt' => XXXXXXXXXXXXXXXXXXXXXXXX
  'secret' => XXXXXXXXXXXXXXXXXXXXXXXX
  'trusted_domains' => 
  array (
    0 => 'kloud.chaosklub.com',
  ),
  'datadirectory' => '/home/users3/k/khaos/data_k-space/',
  'overwrite.cli.url' => 'https://kloud.chaosklub.com/k-space',
  'dbtype' => 'mysql',
  'version' => '10.0.2.1',
  'dbname' => XXXXXXXXXXXXXX
  'dbhost' => XXXXXXXXXXXXXXXX
  'dbtableprefix' => 'oc_',
  'dbuser' => XXXXXXXXXXXXXX
  'dbpassword' => XXXXXXXXXXXXXX
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 55.0.3 64bits

**Operating system:** Windows 7

**CardDAV-clients:** N/A

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
owncloud.log empty

#### Browser log
```
Javascript console log :
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
SyntaxError: expected expression, got '*'[En savoir plus]  angular.js:311:1
TypeError: angular is undefined[En savoir plus]  angular-route.js:3:30
ReferenceError: angular is not defined[En savoir plus]  angular-uuid4.js:12:1
TypeError: invalid 'in' operand angular[En savoir plus]  angular-cache.js:1:339
TypeError: angular is undefined[En savoir plus]  angular-sanitize.js:1:44
ReferenceError: angular is not defined[En savoir plus]  select.js:2:279
ReferenceError: angular is not defined[En savoir plus]  main.js:1
ReferenceError: angular is not defined[En savoir plus]  ui-bootstrap.min.js:7:4
ReferenceError: angular is not defined[En savoir plus]  ui-bootstrap-tpls.min.js:7:4
TypeError: a is undefined[En savoir plus]  ngclipboard.min.js:4:191
Deprecation warning: tipsy is deprecated. Use tooltip instead.  js.js:127:36
```
![sans titre](https://user-images.githubusercontent.com/32091918/30584222-66c814f8-9d29-11e7-9c57-ce94faeee983.png)

**Comment by nsa-a1** [comment]
I have the same issue.
Workaround is:
1. download contacts app from [https://apps.owncloud.com/content/show.php/Contacts?content=168708](https://apps.owncloud.com/content/show.php/Contacts?content=168708) 
2. Extract gzip into <path to owncloud root>/apps (in my case the path is /var/www/owncloud/apps)
3. Enable contacts app.

**Comment by KhaosFarbauti** [comment]
This workaround doesn't seem to work with Owncloud 10.0.2. Can't enable an old contacts version.

**Comment by KhaosFarbauti** [comment]
Ok after playing around i manage to find the cause : It seems to be Cloudflare (specificaly Cloudflare JS optimization) that make Contacts crash.

Disabling Cloudflare performance (not caching or SSL) make Contacts works again.

Any idea on how to make Contacts and Cloudflare works together ?

**Comment by DeepDiver1975** [comment]
> Any idea on how to make Contacts and Cloudflare works together ?

Not really - but this is already somewhere in the issues tracker.
I'm sorry to let you know but there are no plans to support this.

**Comment by DeepDiver1975** [comment]
see https://github.com/owncloud/contacts/issues/450
