### ISSUE TITLE
iOS sync doesn't get names, just orgnaization (as name)

### ISSUE THREAD

**Issue by jzeevi** [owncloud/contacts#622]
### Steps to reproduce
1. set up carddav per instructions
2.go to contacts on iOS
3.

### Expected behaviour
Expect to see names, phones, email, etc.

### Actual behaviour
Every "Name" is the organization field. The org does also appear in the "company" field with the title.
For those that have numbers, emails, etc that seems to work. Pictures come across

### Server configuration
**Operating system**:
CentOS

**Web server:**
apache
**Database:**
mysql?
**PHP version:**
56
**ownCloud version:** (see ownCloud admin page)
10.0.3
**Contacts version:** (see ownCloud apps page)
1.5.3? How can I tell what I'm running? The market only shows the currently available version (I'm not sure how to upgrade)
**Updated from an older ownCloud or fresh install:**
fresh install
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**
iOS calendar
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Can you Please Export the Contact and Post Herr for testing? Thx

**Comment by jzeevi** [comment]
Thomas,

   I hope I've done as you asked. I downloaded the contacts into a vcf file that I zipped for upload.

   josef

**Comment by jzeevi** [comment]
Oops. Sorry - pressed the wrong button.

**Comment by DeepDiver1975** [comment]
Evolution uses the ORG as displayname as well .... I'll have a look

**Comment by jzeevi** [comment]
Thanks. I know iOS apps can be tricky.

**Comment by DeepDiver1975** [comment]
To me this looks like a general issue within vcards.

Since your vcard hold no N element - ORG will be chosen as SORT-AS property.
To solve this: set the N element with the names of the people and this will be taken.

Let me know if this works for you.

(The N element is set if you enter data into the 'Detailed Name' section)

**Comment by jzeevi** [comment]
So that did fix it. Seems like owncloud should fill in the N element with the basics from the "New Contact" (first name, last name) if it can figure it out or perhaps change that mechanism so the user will enter data for the N element that will also show as the "New Contact" info.

Thoughts?

**Comment by DeepDiver1975** [comment]
Well - processing FN and filling in N is not an easy task. Algorithms do exist but they are language/country/region specific. 
I guess the best would be to add SORT-AS support. Something like a checkbox on attributes...

**Comment by jzeevi** [comment]
Ah. I see. Perhaps creation of  a new contact could require N element info and use that to create an FN? I get that ti may not be simple and do appreciate the chance to brainstorm it with you.

**Comment by DeepDiver1975** [comment]
> Ah. I see. Perhaps creation of a new contact could require N element info and use that to create an FN?

quite valid approach - let's see ... moving to backlog for now

**Comment by Julian1998** [comment]
@jzeevi So finally....... We decided that this is an iOS bug... You can prevent it by setting a detailed name instead of just only a display name.... But if u like to... fork calendar and create the detailed name out of your display name... we can't do that because of names/regions ;)
