### ISSUE TITLE
Contacts not syncing/multiple birthdays on calender

### ISSUE THREAD

**Issue by UtechtDustin** [owncloud/contacts#629]
### Expected behaviour
Synchronizing of contacs not working
Contact birthdays will be not deleted on change

### Actual behaviour
The App CardDAV-Sync(0.4.21) free shows "last sync before x minutes" also i can see the the corect name of the contat "group".
But there are no contacts from owncloud on my mobile phone after the sync.
I can also see the request of the app to owncloud.
--------------------------
I also got the issue that if i change a birthday of a contact the old calender entry will be not deleted (similar issue #576 )

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2

**PHP version:**
7.0.27

**ownCloud version:** (see ownCloud admin page)
10.0.4

**Contacts version:** (see ownCloud apps page)
1.5.3

**Updated from an older ownCloud or fresh install:**
fresh install

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.0.4.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ockyrxwr53fd",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "cloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by DeepDiver1975** [comment]
> 10.0.4

there is an issue in the web interface which will be fixed in 10.0.5 - which shall be release asap
