### ISSUE TITLE
README.md - Redesign

### ISSUE THREAD

**Issue by aspdye** [owncloud/contacts#63]
Hi there,

I think we should redesign the README.md of the contacts app as @georgehrke described for calendar-rework in https://github.com/owncloud/calendar-rework/issues/159 ;)

I have already done this task for the ownCloud core's README.md and I am planning to do this for contacts in the next days ;)

It will be based on my guidelines i published here: https://github.com/owncloud/core/wiki/README.md-Guidelines

**Comment by Henni** [comment]
I'm looking forward to your PR

**Comment by ghost** [comment]
Re-post from: https://github.com/owncloud/calendar/issues/1037#issuecomment-190285228

-> Make sure that the README.md contains the info that this is the repository of the new calendar app and that:
- issues within the CardDAV backend code should reported to core
- issues within the old contacts app shouldn't reported here

**Comment by Henni** [comment]
@aspdye any update on this?
Would be great to have a prettier README for the 9.0 release on Monday.

**Comment by aspdye** [comment]
@henni do you have a good screenshot of the contacts-app?

**Comment by Henni** [comment]
I'll prepare one.

**Comment by Henni** [comment]
This should be good enough for now:
![image](https://cloud.githubusercontent.com/assets/1267827/13547408/db85f36e-e2d1-11e5-81c0-626b65b88a13.png)

@jancborchardt feel free to contribute on this ;)

**Comment by aspdye** [comment]
cool ;) put this into the screenshot-repository :wink:

**Comment by Henni** [comment]
https://github.com/owncloud/screenshots/pull/9

**Comment by jancborchardt** [comment]
Yeah, possible enhancements: Add some groups, and add some avatars. :)

**Comment by aspdye** [comment]
@jancborchardt Simple to fix in the future. Only changing the file in the screenshot-repository is needed :rocket:
