### ISSUE TITLE
Kontakte werden nicht Syncronisiert

### ISSUE THREAD

**Issue by Andreas111** [owncloud/contacts#633]
Ich benutze Own-Cloud in der 10.0.4 version dazu Outlook 2016 zur Syncronisation benutze ich cFos Outlook Dav und Contakt, leider wird nichts syncronisiert
owncloud läuft auf einem Raspberry piII

Was kann ich machen?

Andreas

**Comment by Julian1998** [comment]
https://github.com/aluxnimm/outlookcaldavsynchronizer#install-instructions ;)

Not sure if cFos Outlook Dav supports ownCloud. I would recommend that tool (It's already tested with ownCloud)

**Comment by Andreas111** [comment]
Danke Dir erst einmal, werde ich die nächsten Tage Testen, ob wohl ich OWNCloud in deer 8 ter Version immer benutzt habe und dort hat es wunderbar funktioniert

Thank you for once, I will test the next few days, although I have always used OWNCloud in the 8 ter version and there it worked wonderfully

**Comment by DeepDiver1975** [comment]
Please note that 10.0.4 has an issue in the dav implementation which can cause issues in some sync scenarios. 10.0.6 will fix this - release is planned for January 31st

**Comment by Julian1998** [comment]
@Andreas111 @DeepDiver1975 Thx
