### ISSUE TITLE
importing vcf files with a UTF-8 BOM will cause PHP exception

### ISSUE THREAD

**Issue by afflux** [owncloud/contacts#635]
Import will fail with

    Call to undefined method Sabre\VObject\Property::children() at /var/www/owncloud/apps/contacts/lib/connector/importvcardconnector.php#109

Using owncloud 7.0.2

**Comment by dagbdagb** [comment]
I can confirm that a UTF-8 file with a BOM causes trouble. However, this appears to be a problem in sabre/vobject. Moreover, it is still a problem in the latest upstream version of sabre/vobject (3.3.4).
I have created an issue in sabre/vobject for this. https://github.com/fruux/sabre-vobject/issues/175

**Comment by dagbdagb** [comment]
For now, my bug report about this to sabre-vobject has been rejected. Thus, I hope owncloud will handle this issue 'natively'. I.e. recognize if a *.vcf file has a BOM, and strip the BOM prior to feeding it to vobject for validation.

As noted in https://github.com/fruux/sabre-vobject/issues/175, both notepad.exe and libreoffice writer will add a BOM to a utf-8 file, even if the original file had none.

**Comment by Hywan** [comment]
sabre/vobject now skips the BOM.

**Comment by jbtbnl** [comment]
@Hywan thank you for your effort!

**Comment by jbtbnl** [comment]
The next step towards closing this issue is updating sabre/vobject in core: https://github.com/owncloud/core/issues/12876

**Comment by babelouest** [comment]
:+1: 
Awesome, thanks @Hywan !

**Comment by babelouest** [comment]
I can see that in core, https://github.com/owncloud/core/issues/12876 the fix has been merged, is it updated in owncloud too ?

**Comment by babelouest** [comment]
this seems resolved by now, closing this issue

**Comment by Hywan** [comment]
:+1:
