### ISSUE TITLE
Looking for a working OC v8.0.x release

### ISSUE THREAD

**Issue by disy-mk** [owncloud/contacts#639]
**Please report only issues corresponding to the contacts app for ownCloud 9 or later.**
**The old contacts app, which is compatible with ownCloud 8.2 or earlier, is discontinued!**

OK, I read the above lines, however I upgraded my OC instance from 7.0.x to 8.0.16 just right now.

This disabled several plugins, including contacts.

As I am still on my upgrading roadmap I however want to verify that each upgrade went through correctly. Therefore two or 3 days of productive usage shall pass.
Without the contacts app however this is difficult to achieve.

I tried to find out which release of the contacts plugin might work with OC 8.0.x. Alls releases I checked so far (0...238, 0...211, 0...200, 0...180, 0...155) have minimum requirements of OC9 and up.

How to find the last release to work with OC v8.0.16?
Also: Do new plugin versions update contacts DB structure as well? Is the some update path to go?

Would upgrading OC v7 through all major releases up to v9 or v10 work for the contacts, created with v7 contacts plugin?

**Comment by Julian1998** [comment]
@DeepDiver1975 Do you know something about that?

**Comment by DeepDiver1975** [comment]
First of all you need to move on to ownCloud 10. Any other previous version is out of support.

If you follow the upgrade process going from 7 -> 8.0 -> 8.1 -> 8.2 -> 9.0 -> 9.1 -> 10 all your data will be preserved and properly migrated. Please not that php minimum requirements are changing through out the releases.

Nevertheless a backup is always neccessary.

**Comment by disy-mk** [comment]
So contacts DB data is not impressed about upgrading through all the releases without contact app being installed/used after each upgrade?

I have some major issues with my installation which I don't want to resolve, as they are hunting me since 2013/2014.

I decided to install a new OC10 instance and then reimport the most important data, which is users/passes and contact data, maybe folders shares (after upgrading the old instance to OC10 as well. Files are going to be synced to the server, without trying to migrate them.

**Comment by DeepDiver1975** [comment]
Hint for importing contact data: on user basis you can export and import addressbook in both contacts apps. No idea how many users/addressbooks you have but this would be the easiest approach.

Good luck!

In case you face issues during migration look out for help at https://central.owncloud.org

**Comment by disy-mk** [comment]
thought about that as well. However, I am not sure if contacts images are exported as well in vcard format? Do you happen to know if they are stored (as BLOB or BASE64) in the same contacts table or simply referenced somewhere to the file system?

**Comment by DeepDiver1975** [comment]
the export and import is based on the vcard standard. it will for sure be the easiest solution.

In the release step from 8.2 to 9.0 contacts and calendar information are stored in different tables.
We had a migration script in place which copied information over.

**Comment by disy-mk** [comment]
Thanks for the information - should be able to find my path from now on.
