### ISSUE TITLE
Restoring Contacts app

### ISSUE THREAD

**Issue by QuietOcean** [owncloud/contacts#641]
Hello,
My question would: Where could I find information on how to restore the contacts app without access to a command line i.e. not the information in it.

At the moment a similar threat is going to on find out what ownBackup app could provide for support for restoring the information within the contacts app: https://github.com/pbek/ownbackup/issues/28#issuecomment-409242428

###Steps to reproduce
Primarily
1. Go to admin settings 'Additional'
2. With the ownBackup app select a suitable date
3. Select the tables oc_cards, oc_cards_properties, oc_dav_shares, oc_dav_properties.
4. Click on restore

Secondly
5. Deleting the contacts app
6. Reinstalling the contacts app

### Expected behaviour
Primarily
The return of contact app functioning properly and perhaps the return of all contacts.

Secondly
The return of contact app functioning properly

### Actual behaviour
First issue the an error message as stated here below and contacts app attempting to load contacts but doing that for minutes or hours without result.

**Tables restored
Table(s) could not be restored: Inserting data row failed: An exception occurred while executing ‘INSERT INTO oc_cards (id,addressbookid,carddata,uri,lastmodified,etag,size) SELECT ?,?,?,?,?,?,? FROM oc_cards WHERE id = ? AND addressbookid = ? AND carddata = ? AND uri = ? AND lastmodified = ? AND etag = ? AND size = ? HAVING COUNT(*) = 0’ with params [“1”, “2”, “BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 4.1.2//EN\r\nUID:username1\r\nEMAIL:username2\r\nCLOUD:username1@domain.org\r\nPHOTO;ENCODING=b;TYPE=image/png:iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc\r\n 4AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQ… a very long string of digits…Fu4SZyTlASjwAAAABJR\r\n U5ErkJggg==\r\nFN:user\u00f2 user\r\nN:user;user\u00f2;;;\r\nEND:VCARD\r\n”, “Database:username.vcf”, “1532608157”, “d3dfc14d2837594079879d9f447056c2”, “24420”]: SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘carddata’ in ‘where clause’**

### Server configuration
unRAID:

**Docker**

**latest**

**latest**

**10.0.8 (stable)** (see ownCloud admin page)

**1.5.4** (see ownCloud apps page)

**no observable issues**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
If someone is willing to explain me how to do this please do let me know.
**The content of config/config.php:**
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'instanceid' => 'ocMYOB',
  'passwordsalt' => 'MYOB',
  'secret' => 'MYOB',
  'trusted_domains' => 
  array (
    0 => '192.168.20.60',
    1 => 'https://cloud-IIYY.org',
  ),
  'datadirectory' => '/config/www/owncloud/data',
  'overwrite.cli.url' => 'https://cloud-IIYY.org',
  'dbtype' => 'mysql',
  'version' => '10.0.8.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'MYOB',
  'dbpassword' => 'MYOB',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'sdata',
  'mail_domain' => 'MYOB',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'MYOB',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'MYOB',
  'mail_smtppassword' => 'MYOB,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpsecure' => 'ssl',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No we do not

**Are you using encryption:** yes/no
Yes we do

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope we are not

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

I fear I could not obtain access and doubt a little of its necessity. 

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

**Comment by DeepDiver1975** [comment]
As explained on central - this is an issue in the ownbackup app.

**Comment by QuietOcean** [comment]
Thank you for your reply and yes this is also an issue of ownBackup app but also of 'Market' or 'contacts'. Mainly because it does not seem possible to restore the app to its original function without a command line. Especially in the case of ownBackup functioning not as expected, it seems desirable to me that at least the option should be available to "factory restore" contacts app without a command line. Therefore returning to the original question: 

"Where could I find information on how to restore the contacts app without access to a command line i.e. not the information in it."

Therefore I would like to ask if you or someone else would be so very kind to re-open the threat to allow others ask questions or perhaps point me to information. Unless I misunderstood the rules to which I would offer my apologies and ask for change of rules.

**Comment by DeepDiver1975** [comment]
The contacts app is a pure frontend app. The data is stored in the server which is part of core. Just for the overall understanding.

With respect to database backup and restore from my pov native database tools shall be used. Depending on the setup this can be done using the command line of some web ui (phpmyadmin?).
