### ISSUE TITLE
Drone setup

### ISSUE THREAD

**Issue by davitol** [owncloud/contacts#644]
Move from Travis to Drone

**Comment by phil-davis** [comment]
- [x] move unit tests into ``test/unit`` folder
- [x] put ``phpunit.xml`` into the root folder
- [x] review Makefile etc to make the test infrastructure "standard"
- [x] anything else to make the CI and drone "standard"

**Comment by phil-davis** [comment]
ToDo:
- [x] change repo from require travis to require drone - done
- [x] delete ``.travis.yml`` #651

**Comment by phil-davis** [comment]
ToDo:
- [x] apply code style changes #652 
- [x] run code style checks in drone #652
