### ISSUE TITLE
[For Semver] Contacts 1.5.5

### ISSUE THREAD

**Issue by PVince81** [owncloud/contacts#647]
### Reason

- Set max version to 10 because core platform is switching to Semver
- PHP 7.2 unit tests

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test: Install from the provided tarball and enable in ownCloud stable10 and check it works

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/XzMzeCcBaLJTif8
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/contacts/pull/650

**Comment by PVince81** [comment]
@davitol please test RC https://cloud.owncloud.com/index.php/s/XzMzeCcBaLJTif8

**Comment by davitol** [comment]
@PVince81 CHANGELOG.md and README.md are missed in the tarball

**Comment by PVince81** [comment]
@davitol try again with RC2 https://cloud.owncloud.com/index.php/s/iiuiquiSbThp3q3

**Comment by davitol** [comment]
> @PVince81 CHANGELOG.md and README.md are missed in the tarball

Readme.md file is still missed in the tarball

**Comment by davitol** [comment]
Also if you click on 1.5.5. link in the CHANGELOG.md file, you are redirected to calendar Changelog instead of contacts one.

![screen shot 2018-12-10 at 13 13 37](https://user-images.githubusercontent.com/10596560/49732014-76db5f80-fc7d-11e8-8fd5-5bfd5f523274.png)

**Comment by PVince81** [comment]
I looked at the README and it didn't look useful so decided against bundling

**Comment by PVince81** [comment]
and now revoked my decision and RC3 has README.md and the correct links in the changelog.

@davitol please check https://cloud.owncloud.com/index.php/s/ynf6j4i6tP1Q2Ot

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready
