### ISSUE TITLE
Contact property undelete

### ISSUE THREAD

**Issue by tanghus** [owncloud/contacts#65]
Each contact object has a queue to hold deleted properties. When a property is deleted, it is pushed to the queue, and an undo button/dropdown is shown. The user can select properties for undeletion at random in the list, and they will be re-inserted into the contact.
The deletion queues life-time is until refresh e.g. changing app, but it persists if the user closes the contact, changes group etc.

**Comment by jancborchardt** [comment]
What’s the call on this btw @babelouest?

**Comment by babelouest** [comment]
there is a 5-seconds popup display to allow the user to cancel the deletion if he realises he did wrong. Besides that, there is no way in oc ui to undelete a property

**Comment by jancborchardt** [comment]
Closing for now then, as that’s the normal undo mechanism. Apps should not implement their own thing on top of that so if we want to do more we should somehow standardize that first.
