### ISSUE TITLE
Importing contacts with special characters

### ISSUE THREAD

**Issue by danieliancu** [owncloud/contacts#656]
Upon importing contacts from a Nokia phone using "Standard Vcard" format, all the names which had special characters, have been encoded in UTF-8 with "=" signs and the hex code.
For example, the space character is "=20" and "ă" is "=C4=83".
If the Vcard had no special characters, then the spaces would not get encoded as described above, they would be simple spaces " ".

Here's an example of a Vcard without special characters:
BEGIN:VCARD
VERSION:2.1
N:;Test Name
TEL;CELL:+10000000000
X-CLASS:private
END:VCARD

And here's one with special characters:
BEGIN:VCARD
VERSION:2.1
N;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:;Test=20Name=20Special=C4=83Character
TEL;CELL:+10000000000
X-CLASS:private
END:VCARD

Upon importing those Vcards, I get one contact with the name "Test Name" and the other "Test=20Name=20Special=C4=83Character" instead of "Test Name SpecialăCharacter".

**Comment by babelouest** [comment]
this kind of issue has been resolved by now, I'm closing it but if you think you still have the problem, you can reopen it or open a new one)
