### ISSUE TITLE
Feature request: api or other ways to connect to contact from outside ?

### ISSUE THREAD

**Issue by alirezaimi** [owncloud/contacts#688]
Hi
Is there any way to connect to contact app from outside like api or ?
thanks .

**Comment by DeepDiver1975** [comment]
The owncloud server is exposing contacts via the CardDAV protocol

**Comment by alirezaimi** [comment]
thanks, but how can i retrieve them ?! is there any api for that ? i search it and not found anything related .

**Comment by Julian1998** [comment]
https://tools.ietf.org/html/rfc6352

The owncloud server instance provides your carddav server. So you can access it according to the carddav specs above
