### ISSUE TITLE
Importing contacts from CSV problem with non-latin

### ISSUE THREAD

**Issue by dkoukoul** [owncloud/contacts#689]
Importing CSV file with latin (English) contacts first and non-latin (Greek) contacts was importing the Greek names as "??$#*@!~".
It was a google CSV export. When I split the CSV into 2 separate files, one with just the Greek and one with the rest both imported fine. I had checked in all cases the files where UTF-8 ecnoded.

**Comment by babelouest** [comment]
This has been resolved in other PRs by now, I'm closing this issue. You can reopen it if you still have this problem
