### ISSUE TITLE
No CardDAV Link available for shared addressbooks

### ISSUE THREAD

**Issue by shoelzle** [owncloud/contacts#701]
If an addressbook (family) is shared with me (myname) by another user (otherUser), I can access it, I can even sync it using the following link scheme:
https://myocserver.../remote.php/carddav/addressbooks/myname/family_shared_by_otherUser/
But this link is not shown in the Web-GUI (any more).

I updated from owncloud 6, maybe the link was present before ?

**Comment by Golem69** [comment]
Hello
in file addressbooks.js at line 37 in js directory, change :

if (['local', 'ldap'].indexOf(this.getBackend()) === -1) {
    this.$li.find('a.action.carddav').hide();
}

for:

if (['local', 'shared', 'ldap'].indexOf(this.getBackend()) === -1) {
    this.$li.find('a.action.carddav').hide();
}

and back carddav link :-D

**Comment by shoelzle** [comment]
works, thanks !

**Comment by brianjmurrell** [comment]
@Golem69 Thanks for the solution, works great!

**Comment by bierbo** [comment]
Worked for me (7.0.2)! Thanks a lot!
