### ISSUE TITLE
LDAP delete sharing not work

### ISSUE THREAD

**Issue by JB1985** [owncloud/contacts#715]
Deleting a share in contacts is not working.

I see in the database oc_share that owncloud delete the group (share_type 1) but not the users (share_type2). After that, all users - of the deleting group - have full permission.

Version: ownCloud 7.0.3 (stable)
OS: Debian 7

**Comment by blizzz** [comment]
Does the issue still exist?

**Comment by JB1985** [comment]
Fixed in OC8.0

**Comment by blizzz** [comment]
Sup, thanks for the confirmation!
