### ISSUE TITLE
Adding new field which already exists results in existing field being emptied

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#73]
Instead of the field being emptied, there are 2 cases:
- If the field can only exist once (like »Organization« or »Nickname« or »Notes«) the entry should be removed from the »Add new field« dropdown as soon as the field already exists
- If there can be multiple fields (like telephone, address, email), there should of course be another one added.

Not sure how much of this is possible til release, but for sure we shouldn’t clear any data. As a quick fix, only focus the already existing field.

**Comment by DeepDiver1975** [comment]
known ... working on it
