### ISSUE TITLE
Backend for managing backends ;)

### ISSUE THREAD

**Issue by tanghus** [owncloud/contacts#76]
With the option of using other backends than `local` and `shared`, we need a way to store properties for those. To keep it as simple as possible I suggest to store properties for the backend (URL, credentials etc), and for the address book (lastModified, ctag whatever the backend can't get/set elsewhere) in a serialized/json_encoded value. That way we don't have to add a multitude of fields - or worse save each value in oc_preferences.

oc_contacts_user_backend:
* id (int)
* backend (string)
* userid (string)
* permissions (int)
* properties (clob/mediumtext)

oc_contacts_user_addressbook:
* id (int)
* backendid (int)
* identifier (string) This can be a URI or something.
* permissions (int)
* properties (clob/mediumtext)

This way a user can have different instances using the same backend type (e.g. ldap), which each can define several address books.
Normally an instance of a backend will probably only have one address book, but the backend class could also allow to map e.g. ldap groups as different address books.

Comments? @babelouest @georgehrke @blizzz

**Comment by jancborchardt** [comment]
What’s the current status on this? Input welcome @babelouest @DeepDiver1975 @ChristophWurst

**Comment by DeepDiver1975** [comment]
> What’s the current status on this? Input welcome @babelouest @DeepDiver1975 @ChristophWurst

no idea

**Comment by jancborchardt** [comment]
Closing this then to focus. If it becomes a topic again we can revive this.
