### ISSUE TITLE
error while vcard contact import.

### ISSUE THREAD

**Issue by athulrajdr** [owncloud/contacts#774]
this v card file is exported from google contacts. when i import this file to my owncloud contacts, the status shows the content of vcf file is,

BEGIN:VCARD
VERSION:3.0
FN:Z New Kni Bz Rp: Wr.no
N:Rp\: Wr.no;Z New Kni Bz;;;
TEL;TYPE=MAIN:+919999999999
END:VCARD

I tried to import this file to my google contacts, and the contact imported successfully. .
The details which i entered to the contact on phone
First name: Z New Kni Bz
Last name: Rp: Wr.no

when this contact comes with a multiple contacts in a single .vcf file. the entire import shows the same status as "Total:0, Success:0, Errors:0",

**Comment by athulrajdr** [comment]
no issue while importing with standard Vcard format.

**Comment by babelouest** [comment]
@athulrajdr , actually, this is a known issue from automatic import, but thanks for reporting your problem. Glad you found a workaround :)
