### ISSUE TITLE
Latest master branch not loading

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/contacts#781]
cc @Raydiation @MorrisJobke @georgehrke any idea why Contacts and Calendar are failing with the latest core master branch? Something with a mysterious `en` script.

```
Fatal error: Uncaught exception 'Exception' with message 'js file not found: script:en serverroot:/var/www/owncloud' in /var/www/owncloud/lib/private/template/resourcelocator.php:46 Stack trace: #0 /var/www/owncloud/lib/private/templatelayout.php(153): OC\Template\ResourceLocator->find(Array) #1 /var/www/owncloud/lib/private/templatelayout.php(104): OC_TemplateLayout::findJavascriptFiles(Array) #2 /var/www/owncloud/lib/private/template.php(118): OC_TemplateLayout->__construct('error', '') #3 /var/www/owncloud/lib/private/template/base.php(103): OC_Template->fetchPage() #4 /var/www/owncloud/lib/private/template.php(227): OC\Template\Base->printPage() #5 [internal function]: OC_Template::printExceptionErrorPage(Object(Exception)) #6 {main} thrown in /var/www/owncloud/lib/private/template/resourcelocator.php on line 46
```

**Comment by MorrisJobke** [comment]
Could this be the cause: https://github.com/owncloud/core/pull/13350

**Comment by MorrisJobke** [comment]
Or this: https://github.com/owncloud/contacts/blob/ec065cc8abe78fd899df23b7609fd4b1427faa97/templates/contacts.php#L452

**Comment by Raydiation** [comment]
Works for me, are you on the latest master?

**Comment by jbtbnl** [comment]
@Raydiation yes, I am. It seems to depend on the language setting: English results in the previously mentioned error, Dutch results in the apps loading just fine.

**Comment by Raydiation** [comment]
Ah right, yep it's also failing for me

@DeepDiver1975 didnt we ignore missing js libs?

**Comment by Raydiation** [comment]
@jbtbnl here is your problem: https://github.com/owncloud/contacts/blob/master/templates/contacts.php#L4

It is not allowed to simply set an empty string as app id, that's why it fails. Use script('core', .. instead

**Comment by jbtbnl** [comment]
@Raydiation thanks, that fixes it! The error message is quite unclear though :)

**Comment by Raydiation** [comment]
@jbtbnl thats because you gave the system '' as app id which is basically printed as '' in the error message ;)

**Comment by Raydiation** [comment]
Also if you look at the public api docs: https://github.com/owncloud/core/blob/master/lib/private/template/functions.php#L28 it says it needs the app name. If you pass in weird stuff, weird stuff is bound to happen ;)
