### ISSUE TITLE
TypeError: addressBook is undefined error after deleting the last address book 

### ISSUE THREAD

**Issue by rehrumesh** [owncloud/contacts#786]
I delete the last address book and press "New Contact" button. Then I get an error on the console saying "TypeError: addressBook is undefined" (contacts.js:2394). However before press"New Contact" button if I refresh the page error will not occur. This was tested in Firefox browser on Ubuntu 14.10 & Chrome browser on Windows 8.1 

I have added a video link of how to recreate the error on demo site in windows environment.

https://docs.google.com/file/d/0By3mkkj9kVGhQnh0aHBtLWxZWms/edit?pli=1

**Comment by babelouest** [comment]
That's true. Although deleting all adressbooks is not a goog idea, not having an error message saying that you can't create a contact since you don't have an adressbook is not good either.

**Comment by jbtbnl** [comment]
So the suggested fix is to show a message "Please create an addressbook first" before a new contact can be created?

**Comment by rehrumesh** [comment]
I'll work on bug

**Comment by rehrumesh** [comment]
@jbtbnl can you review the PR #801 ?
