### ISSUE TITLE
accessing /index.php/apps/contacts/addressbook/local/1/export

### ISSUE THREAD

**Issue by abrumloop** [owncloud/contacts#805]
### Steps to reproduce
1. curl -u <user>:<pw>  https://<url>/owncloud/index.php/apps/contacts/addressbook/local/1/export > adressbook.vcf

### Expected behaviour
This command should download the adressbook
### Actual behaviour
Everything i get is a login error:
{"message":"Current user is not logged in"}

The same command does the job with owncloud 7. With firefox / chrome downloading still works.

### Server configuration

**Web server:**
apache
**Database:**
sql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
contacts, calendar, share, activities, deleted files, file locking, first run wizard, mail template editor, pdf-viewer, pictures, text, Provisioning API, updater, versions, video viewer 
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
'instanceid' => 'oczxzjxdmzrh',
'passwordsalt' => '',
'secret' => '',
'trusted_domains' =>
array (
0 => '',
),
'datadirectory' => '/mnt/webr/c3/66/54458666/htdocs/owncloud/data',
'overwrite.cli.url' => 'https:///owncloud',
'dbtype' => 'mysql',
'version' => '8.0.0.7',
'dbname' => 'DB2016509',
'dbhost' => 'rdbms.strato.de',
'dbtableprefix' => 'oc_',
'dbuser' => 'U2016509',
'dbpassword' => '',
'installed' => true,
'loglevel' => 1,
'forcessl' => true,
'forceSSLforSubdomains' => true,
'mail_from_address' => 'oc',
'mail_smtpmode' => 'php',
'mail_domain' => '',
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
no entry

**Comment by RealRancor** [comment]
Hi,

i think that is a long deprecated URL which shouldn't be used anymore. Have you tried:

https://example.com/remote.php/carddav/addressbooks/$username/$addressbook?export

which works here just fine.

**Comment by abrumloop** [comment]
Thank you very much. I though the above link should work too, because if i hover the mouse over "settings, export" it was shown. Anyway, the solution posted by you works fine.

**Comment by speeskeek** [comment]
hi there
sorry to reopen this, but I cant get it to work with my config. 
As OP : it used to work. 

I've been trying all the URL's that I found on the net for doing this (and there are many :) ).

**Comment by RealRancor** [comment]
> http://URL.net/owncloud/remote.php/carddav/addressbooks/bart/2?export

Thats very likely wrong. Where do you get the 2 from? Your addressbook is probably not called 2?

**Comment by speeskeek** [comment]
/owncloud/remote.php/carddav/addressbooks/bart/contactpersonen?export


that doesn't work either. I tried with and without capital for "Contactpersonen"

wget returns a internal 500 error

**Comment by RealRancor** [comment]
An internal server error (500) just means a "generic error". Please check your logfiles for more infos.

**Comment by speeskeek** [comment]
ngnix log doesn't show anything. So I guess I need to turn on debug somewhere

when I open the link in my browser (in stead of wget on terminal) the browser returns "ERR_INVALID_RESPONSE".

When I go to the url without the "?export"

/owncloud/remote.php/carddav/addressbooks/bart/contactpersonen

I see a lot of vcards (I guess 1 for each contact).
