### ISSUE TITLE
Import google contacts from *.vcf file fails.

### ISSUE THREAD

**Issue by smirkybg** [owncloud/contacts#807]
First I experienced a missing file: core/vendor/jquery/dist/jquery-migrate.min.map
which indeed isn't present in the latest stable ownCloud version (8).
Then, after disabling the JavaScript source maps from the Dev Tools, in the attempt to import contacts again, I got a Internel Server Error (500) with the logs giving me:
[Tue Feb 10 17:28:04.360752 2015] [:error] [pid 27168] [client xx.xx.xx.xx:43016] PHP Fatal error:  Call to a member function select() on boolean in /usr/share/webapps/owncloud/apps/contacts/lib/connector/importvcardconnector.php on line 202, referer: https://cloud.domain.ltd/index.php/apps/contacts/

There seems to be a lot of problems regarding with the Contacts application. I'm using the latest package from my distribution (Archlinux).

**Comment by babelouest** [comment]
can you post an anomized sample of the .vcf file causing problem ? I think I found the problem, and the way to solve it, but your file may have problems in the first place (encoding, vcf format, etc.)

**Comment by smirkybg** [comment]
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=D0=9C=D0=B8=D1=82=D0=BA=D0=BE=20=D0=9A=D0=BE=D0=BB=D1=87=D0=B0=D0=BA=
=D0=BE=D0=B2;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=9C=D0=B8=D1=82=D0=BA=D0=BE=20=D0=9A=D0=BE=D0=BB=D1=87=D0=B0=D0=BA=
=D0=BE=D0=B2
TEL;CELL:+12311111
END:VCARD


Here's a sample which I made. As far as my tests show, I can import contacts if they don't have UTF-8 symbols inside (i.e. my contacts are on Cyrillic which might be the issue). I tried importing a contact with normal ASCII symbols, no issues.

**Comment by babelouest** [comment]
OK, this is a known problem, the ENCODING parameter is not allowed in the VCard 3 standard, only UTF8 strings.
Anyway I'm working on a patch to avoid import failing.

**Comment by smirkybg** [comment]
Thanks you. I'm still curious though. By avoiding the import failing, do you mean that the info would be trimmed or it converted properly in some sort?

**Comment by babelouest** [comment]
this should fix the error message, although you should fix your import file first then, the quoted-printable properties are not allowed in the vcard 3 rfc.

Can you test this PR ?
