### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by gstuartj** [owncloud/contacts#813]
Owncloud 8.0 (8.0.0-5 package, Ubuntu, fresh install)
PHP version: PHP 5.5.9-1ubuntu4.5

When searching contact entries the search operation for all fields (and importantly, the name field) is case sensitive. This behavior is probably not expected by the user; it definitely caused me some confusion.

**Comment by gstuartj** [comment]
Case sensitivity of other search fields confirmed. Title updated.

**Comment by jelle-e** [comment]
Yes, confirmed. When using the API for searching contacts I also have this problem. Any quick fix for this?

**Comment by ntassani** [comment]
Yes... same here, any solution? Thanks for your help :)

**Comment by jancborchardt** [comment]
@babelouest @LEDfan @jbtbnl can you look into this? :) We also experience this in the Mail app https://github.com/owncloud/mail/issues/197

(Btw, also join the IRC channel at #owncloud-contacts! A bunch of other people who want to help with the Contacts app are there already. :)

**Comment by jelle-e** [comment]
Fixed!
https://github.com/owncloud/contacts/pull/910
