### ISSUE TITLE
Google CSV import incorrectly processes phone number delimiters

### ISSUE THREAD

**Issue by gstuartj** [owncloud/contacts#818]
Owncloud 8.0 (8.0.0-5 package, Ubuntu, fresh install)
PHP version: PHP 5.5.9-1ubuntu4.5
DB: MySQL Ver 14.14 Distrib 5.5.41

Importing a Google formatted CSV causes entries with multiple home phones associated to be delimited by the string " ::: " instead of a comma, the way the Contacts app handles other import formats.

**Comment by babelouest** [comment]
this commit should fix the problem: 8f29f21, can you update pr #816 and test it ?

**Comment by gstuartj** [comment]
Confirmed working with commit 8f29f21.

**Comment by gstuartj** [comment]
Confirmed working with commit 8f29f21. Multiple numbers of the same type are now separated by commas, as expected.

**Comment by babelouest** [comment]
closing this issue now
