### ISSUE TITLE
Google CSV import fails to process address delimiters

### ISSUE THREAD

**Issue by gstuartj** [owncloud/contacts#820]
Owncloud 8.0 (8.0.0-5 package, Ubuntu, fresh install)
PHP version: PHP 5.5.9-1ubuntu4.5
DB: MySQL Ver 14.14 Distrib 5.5.41

Contacts imported from a Google CSV with multiple home addresses associated will have all addresses placed in the same address field in the Contacts app, separated by the delimiter string " ::: ". Ideally those addresses would be broken into separate address fields.

**Comment by babelouest** [comment]
Working on it, the gmail csv format has a lot of surprises like this one.

**Comment by babelouest** [comment]
this problem has been fixed in recent releases, I'm closing it but you can reopen it if you still have the problem
