### ISSUE TITLE
ownCloud 8 Contacts 0.3.0.18: name editing problem (caused by CSS)

### ISSUE THREAD

**Issue by eckelmi** [owncloud/contacts#823]
I have just upgraded to ownCloud 8.0, and have noticed a problem with the Contacts app (version 0.3.0.18):

When editing a contact, the pen next to the full „Name“ text input field does not appear anymore when hovering over the field (as it did in earlier versions), therefore it is not possible to get to the text input fields for „First name“, „Additional names“ and „Last name“.

I have checked with IE11 (most up to date version) and Chrome browsers on Windows 8.1 x64, the problem occured in both of them.

As a quick fix, adding the following line to the contacts.css solved the problem for me (but perhaps there is another solution):
.singleproperties .icon-rename { position:absolute; }

**Comment by deMattin** [comment]
Problem fixed with this to me, too (in OC 8.0.1).

Are there no updates on Contacts app any more?
I mostly see transiflex merges and only rare bug fixing in contacts master and no version updates.

This fix here works and seems to be really simple and "sleeps" here since 3 weeks.

**Comment by deMattin** [comment]
I made a pull request and hope, I did it the right way ...

**Comment by RalfWW** [comment]
Fix still not included to 8.0.3!

**Comment by sysdev41** [comment]
No, unfortunately not. I was facing the same problem. Meanwhile, i have to manually fix multiple bugs after each upgrade, since fixes are not getting merged. 

The focus at owncloud is propably mainly filesharing, PIM/groupware functionality seems to be of low interest.
