### ISSUE TITLE
Contacts page not loading

### ISSUE THREAD

**Issue by tmoehle** [owncloud/contacts#828]
Hey,

I upgraded Owncloud to the new Version 8.0, but now the contacts app is not working anymore. When I click it, there is just the spinner turning, as you can see in the attached screenshot.
Server: Owncloud 8 on Apache 2.4.7, PHP 5.5.9 with mod_fcgid

![capture](https://cloud.githubusercontent.com/assets/185613/6226055/e39b7f14-b691-11e4-8a83-2268ac225e28.PNG)

There is no message in the log, so I guess it might have something to do with JavaScript.
I can reproduce the error with current Crome and Firefox versions.

I'd like to give more specific information on this Issue, but I'm not sure how to do that.

**Comment by tmoehle** [comment]
By tracing JavaScript errors, I found out, that the error occurs while having 'enable_avatars' => false, in the config.php. Enabling avatars again solves the issues.

**Comment by RealRancor** [comment]
Hi,

are you running the latest contacts app for OC8 (0.3.0.18) from the appstore https://apps.owncloud.com/content/show.php/Contacts+8.0?content=168708

**Comment by tmoehle** [comment]
Yes

**Comment by 150d** [comment]
Same issue here, shared hosting with PHP v5.6. Commenting out the line 'enable_avatars' => false in config.php (as suggested by tmoehle) made the contacts page appear again. (Thank you!)

**Comment by charno6** [comment]
#893 
Also had this issue on shared hosting with PHP version 5.6 after upgrading from 7.0.5 to 8.0.3, enabling avatars fixed it.

**Comment by mroi** [comment]
This is my workaround for this problem:
#926
