### ISSUE TITLE
Access to undeclared static property: Sabre\VObject\Component\VCard::$componentMap

### ISSUE THREAD

**Issue by dsiggi** [owncloud/contacts#859]
Hi,
when I activate the contact app in owncloud 8.0.0 my php installation not working anymore.
This is the message that I become:

lighttpd@server ~/owncloud/apps $ php ../occ app:list
PHP Fatal error:  Access to undeclared static property: Sabre\VObject\Component\VCard::$componentMap in /var/www/localhost/htdocs/owncloud/apps/contacts/appinfo/app.php on line 15

When I comment out the line 15 & 16 all working fine.

**Comment by asavah** [comment]
That happens because of a mismatch in Sabre versions.
After upgrading to OC 8.0.2 I've been hit by this issue.
Solved by checking out stable8 branch of owncloud/contacts instead of master.
git checkout stable8
solved the issue for me without modyfing the code.

**Comment by DeepDiver1975** [comment]
you are using the wrong version of the app - please upgrade the app to the correct version.
