### ISSUE TITLE
detailsitems need class of type of field so they can be identified

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#86]
For styling the address fields for example, I need the `detailsitem` elements to have a class. For example for the address detailsitem, give it a class="address" or whatnot. Otherwise I can’t specifically style it. cc @Henni @DeepDiver1975

**Comment by jancborchardt** [comment]
Also, for the address: Can you put a container around every label+input group? I want to have a line for each. Also, can we cut the »PO box« field? It’s first up, and kinda unusual?

**Comment by jancborchardt** [comment]
Aaaah ok, I can do this myself apparently? Just found the detailItems folder. :)

**Comment by jancborchardt** [comment]
Actually I can’t add the classes since they should be on the detailItems container wrapped around. Can you help me there @DeepDiver1975 @Henni

**Comment by Henni** [comment]
@jancborchardt I'll take a look

**Comment by jancborchardt** [comment]
It’s not that important anymore btw since I found that just wrapping a div around the label+input groups will take care of the layout already. :)
