### ISSUE TITLE
Fails to import VCF file with ENCODING=QUOTED-PRINTABLE

### ISSUE THREAD

**Issue by mcepl** [owncloud/contacts#861]
When downloading VCF addressbook from an Android phone I got also this record on which ownCloud (7.0.4) chokes:

```vcard
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=43=65=70=6C;=4D=61=74=C4=9B=6A;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=4D=61=74=C4=9B=6A=20=43=65=70=6C
TEL;VOICE:+420604893825
END:VCARD
```

**Comment by babelouest** [comment]
That's a known problem with non standard vcards, like #656 , I'd rather closing this issue and continuing in the originally opened one if you don't mind.

**Comment by mcepl** [comment]
Sure, just to note that this "non standard vcard" is produced by Android Contacts, which is unfortunately quite important step outside of standards to be ignored (no, I am not saying you ignore this).
