### ISSUE TITLE
Table name 'contacts_cards_properties' too long

### ISSUE THREAD

**Issue by gnuppek** [owncloud/contacts#868]
When using owncloud with Oracle database as backend, activating contacts leads to this error:

```
An exception occurred while executing 'CREATE SEQUENCE "oc_contacts_cards_properties_SEQ" START WITH 1 MINVALUE 1 INCREMENT BY 1': ORA-00972: identifier is too long
```

As these names are built with a prefix (here: 'oc_') and a suffix (here: '_SEQ') please shorten the tablenames to at most 22 bytes length as Oracle supports only identifier names up to 30 chars.

'contacts_cards_properties' could be shortened to 'contacts_cards_props' without losing meaning.

**Comment by DeepDiver1975** [comment]
there are no plans to support oracle in the contacts app. Feel free to contribute.
