### ISSUE TITLE
importcontroller object object

### ISSUE THREAD

**Issue by neo243** [owncloud/contacts#876]
Hi Guys,

when i want to import Contacts via csv or vcard i it just starts with [object_object] and stays there.
i can't even export contacts from owncloud and then import them again.

Some informations about my system:

its a xampp 32-5.6.3-0-vc11 with an Owncloud 8.0.2 installed by bitnami.

Here is the error message from the log and on the Disk is enough Space i checked it.

Error	contacts	E:\xampp\apps\owncloud\htdocs\apps\contacts\lib\controller\importcontroller.php. Line: 105: Übertragen der Kontakte fehlgeschlagen.

Error	PHP	file_put_contents(): Only 0 of 267 bytes written, possibly out of free disk space at E:\xampp\apps\owncloud\htdocs\lib\private\files\storage\mappedlocal.php#184.

Greetings neo

**Comment by babelouest** [comment]
Hello,

What does "Übertragen der Kontakte fehlgeschlagen." mean ?
Also, you have a file_put_contents error. Do you, by any chance try to import a file by selecting it in the file application ? If so that's not the good way anymore, you should use the import dialog for it in the contact app.

**Comment by DeepDiver1975** [comment]
ownCloud no longer support windows platform -> closing
