### ISSUE TITLE
Unable to edit contacts in iOS and Yosemite

### ISSUE THREAD

**Issue by soerpoers** [owncloud/contacts#881]
Hey there,

I've an weird Issue. I can edit my imported Contacts from iOS and Yosemite - that’s not the point - but it overwrites all changes with the next Sync. In the Webinterface there is no Problem - all works fine.
If I add a new Contact, that Issue isn't there - all Changes are synced and it all works perfect.
I've only one adressbook and no groups to sync.

I don't can change much on OC, cause i've an Account @ owncube and they can't reproduce this.

So what can I do now?

Sorry for my bad english…

**Comment by babelouest** [comment]
you mean that when you make changes on your iOS device, they are overwritten after the next sync ?

That looks like a CardDAV client problem to me.
What client are you using ? are you sure you didn't check the option "read-only" on your client ?

**Comment by soerpoers** [comment]
i use the normal iOS and Yosemite ContactApp and therein the normal "/remote.php/carddav/principals/admin/-Path"
Before that owncube account I use several OC-Accounts and they work fine. I don't know, if I can check any access permissions

**Comment by babelouest** [comment]
OK so it could come from owncube configuration too, can you check your owncube logs ?

**Comment by soerpoers** [comment]
Hmm - sorry - it's like Chinese Language for me. Maybe you find something.
I should say that I had some Problems at importing my Contacts, so that I import them in three Parts.
Maybe I should import them again and see if this Issue is there anymore…

The log is there --> https://poersn.owncube.com/index.php/s/f5qUGmY3uly7vJ2

Thank you

**Comment by babelouest** [comment]
not helping me either :/

I'm still not sure the problem comes from import, but maybe from your server configuration

**Comment by soerpoers** [comment]
so i've had access to the owncube-contact-folder-config and set the permissions to the right ones. from this point on it works fine. thanks for your help babelouest…
