### ISSUE TITLE
Importing contacts is broken on master and 8.1

### ISSUE THREAD

**Issue by Raydiation** [owncloud/contacts#885]
{"reqId":"QQf\/7OGyRKikMOrZyoQg","remoteAddr":"80.110.122.65","app":"PHP","message":"Class 'OC_FileProxy' not found at \/var\/www\/owncloud\/apps\/contacts\/lib\/controller\/importcontroller.php#89","level":3,"time":"2015-04-26T09:41:04+00:00"}

Seems to rely on an old deprecated private api class

**Comment by babelouest** [comment]
@jbtbnl , it looks like there is no more `*FileProxy*` owncloud class. I don't recall using it when I reimplemented file import. I removed `OC_FileProxy` references and the problem looks to have disappeared. Do you know if this class is obsolete or is it replaced by another one ?

**Comment by babelouest** [comment]
@Raydiation , can you test #886 to see if this fixes your problem ? It does fix for me.

**Comment by Raydiation** [comment]
PR fixes it for me, gave you a thumbs up ;)

**Comment by babelouest** [comment]
:+1:
