### ISSUE TITLE
Creation of multiple fields for Organization and Nickname possible

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#89]
This should not be possible, right? Fields like organization and nickname should only exist once I assume?

**Comment by DeepDiver1975** [comment]
> This should not be possible, right? Fields like organization and nickname should only exist once I assume?

sure - on it

**Comment by Henni** [comment]
@DeepDiver1975 do you have an approach where we can store this in the `vCardMeta` object?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 do you have an approach where we can store this in the vCardMeta object?

yep - https://github.com/owncloud/contacts/pull/92
