### ISSUE TITLE
Contacts not working anymore after upgrade to 8.0.3 (avatar related)

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/contacts#893]
I just upgraded my ownCloud installation from 7.0.5 to 8.0.3 and the contacts app does not work. It just shows the loading spinning wheel and nothing happens.

Now I already had this issue in the past (see #677) where this happened because I had the avatars disabled like here:

```
  'enable_avatars' => false,
```

and indeed if I enable the avatars contacts works again. Looks like someone broke this again...

Can please some fix this in v8?

**Comment by hostingnuggets** [comment]
could someone please take a look? I can't upgrade from 7.0.5 to 8.0.3 due to this annoying bug which makes the contacts unusable if you have avatars disabled...

**Comment by hostingnuggets** [comment]
ping @jbtbnl and @sorglos

**Comment by DeepDiver1975** [comment]
fixed with #926
