### ISSUE TITLE
Import does not import profile image

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#904]
I have a vcf file with a bunch of contacts, most of them with user image. None of them is imported.

This is an example of the exported file, only the photo portion: https://cloud.jancborchardt.net/public.php?service=files&t=6370883caffc4a986fc9ef5315b1ffc5 (beautiful face of @DeepDiver1975 ;)

As you can’t see, you can’t see anything:
![capture du 2015-05-19 16 08 36](https://cloud.githubusercontent.com/assets/925062/7704895/59226788-fe41-11e4-995d-fc6f9921c598.png)

@babelouest @jbtbnl @LEDfan

**Comment by jancborchardt** [comment]
(Latest master of both core and Contacts app.)

**Comment by jancborchardt** [comment]
And strangely enough, in the Mail app it then looks like this:
![capture du 2015-05-19 16 33 57](https://cloud.githubusercontent.com/assets/925062/7705516/f5b1d540-fe44-11e4-8025-52ae0d6868bb.png)
(Jos I did not have a photo of, but Frank I did.)

cc @DeepDiver1975 @zinks- @clementhk @irgendwie

**Comment by jancborchardt** [comment]
The relevant error messages in the Mail app:
```
{"reqId":"rkCUOZF91wcNFuJx+PhU","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-19T14:36:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/301\/photo"}
{"reqId":"FKfFs3mBEtchtfgr4HpN","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-05-19T14:36:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/352\/photo"}
```
Browser console:
```
Resource interpreted as Image but transferred with MIME type application/json: "http://localhorst/owncloud/index.php/apps/contacts/addressbook/local/2/contact/301/photo".
Resource interpreted as Image but transferred with MIME type application/json: "http://localhorst/owncloud/index.php/apps/contacts/addressbook/local/2/contact/352/photo".
```

**Comment by babelouest** [comment]
When I try to import your picture I have no display either, but if I try to edit it, I have the following error on my apache logs:
`PHP Fatal error:  Call to a member function fixOrientation() on a non-object in <owncloud>/contacts/lib/utils/temporaryphoto.php on line 191`
When you import a vcard file, the profile image is imported as is so I don't know what would be wrong in this place.

**Comment by jancborchardt** [comment]
@babelouest something with the image handling? I mean, does this work for you:
1. Export your address book from ownCloud (which includes images)
2. Import it in another ownCloud

Do the images show or not? Not for me.

**Comment by OliverKohlDSc** [comment]
@jancborchardt I've the very same problem and the images doesn't show up, but they are existent in the DB and in the export.

**Comment by babelouest** [comment]
@jancborchardt , I see the problem too with the picture you sent me, but if I export cards with pictures that I can see and re-import them in owncloud, I see the pictures. Also, if I look at the code of the imported vcard with your picture, the `PHOTO` property remains the same than the one you provided me.

To me it means that the problem doesn't probably come from the import itself, but the picture that is corrupted and owncloud picture viewer that probably can't handle such problems.

**Comment by jancborchardt** [comment]
@DeepDiver1975 are you looking into this?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 are you looking into this?

yes

**Comment by DeepDiver1975** [comment]
@jancborchardt the data in the PHOTO property is expected to be base64 encoded - no idea if this is a bug in the vcf or in the contacts code ...

**Comment by jancborchardt** [comment]
@DeepDiver1975 the file was exported using ownCloud Contacts as well.

**Comment by jancborchardt** [comment]
@DeepDiver1975 when you export all your contacts and then import them back again, does it work?

**Comment by DeepDiver1975** [comment]
single export/import works ... testing multiple ...

**Comment by DeepDiver1975** [comment]
exporting and importing all contacts works as well (there are some js hickups and errors - but the server side is working)

**Comment by jancborchardt** [comment]
Let's debug this when coworking then. Maybe my vcf / contact list is faulty.

**Comment by DeepDiver1975** [comment]
Yes. Let's do that

**Comment by LEDfan** [comment]
Note that this *may* be caused by the Sabre upgrade Just like this issue: https://github.com/owncloud/contacts/issues/878

**Comment by DeepDiver1975** [comment]
@jancborchardt you are exporting the contacts on an oc8 instance?

**Comment by DeepDiver1975** [comment]
Okay - seems to be an issue with different versions of ownCloud - I just exported a contact from OC8 adn the image cannot be imported.

**Comment by DeepDiver1975** [comment]
From what I can tell: oc8 vcf and older are valid - vcfs as generated using master branch are broken

**Comment by LEDfan** [comment]
> From what I can tell: oc8 vcf and older are valid - vcfs as generated using master branch are broken

That's what I experience too :) On my oC 8 instance everything works as expected, when updating to 8.1 too, but then when you change something (e.g. some text field) the vcf is generated again and overwritten in the DB. But then there happens something with the base64 code.

**Comment by LEDfan** [comment]
Note that when:
 - importing and exporting 
 - accessing the contacts via sabredav (e.g. thunderbird)
 - editing the contact in ownCloud GUI

the cardav is re-generated.

**Comment by jancborchardt** [comment]
If I remember correctly, the export was from my 7.0.* instance, and I tried to import it to master.
