### ISSUE TITLE
Import jumbles together people with more than one group

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/contacts#905]
If people are in more than one group, the import creates weird jumbled groups for them, not respecting the comma-separation:
![capture du 2015-05-19 16 11 08](https://cloud.githubusercontent.com/assets/925062/7704947/ae5d28b4-fe41-11e4-9b87-ee20e55a1292.png)

So for example in »Design,Hospitality« are only a few people who are in both these groups. Instead they should simply be in the groups »Design« and »Hospitality« and this joint group should not exist.

(Latest master of both core and Contacts app.)

@babelouest @DeepDiver1975 @jbtbnl @LEDfan

**Comment by babelouest** [comment]
Can you post a sample import to reproduce the problem ?

I imported the following VCard and I have 2 new groups after the import:
```VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 3.4.2//EN
FN:Test 3
N:3;Test;;;
EMAIL;TYPE=INTERNET,HOME:lol@lol
TEL;TYPE=CELL:+33 564458887
BDAY:1970-06-16
REV:2015-05-20T11:48:18+00:00
CATEGORIES:groupe2,groupe1
END:VCARD
```

**Comment by jancborchardt** [comment]
@babelouest here you go:
```

**Comment by jancborchardt** [comment]
@babelouest sorry, missed the example. Here you go:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.17//EN
UID:20140201T115448.013ef784c3@myowncloud.com
FN:Firstname Lastname
N:Lastname;Firstname;;;
ADR;TYPE=home:;;Berlin;;;;
LABEL;TYPE=home:Berlin
REV:2014-10-22T07:39:37+00:00
CATEGORIES:Hospitality,Free Culture,Design
END:VCARD
```
(Removed the picture and some other private fields.)

In this case, the contact will be imported and part of two groups: »Design« and »Hospitality,Free Culture«.

**Comment by jancborchardt** [comment]
@Deepdiver1975 @babelouest so this was fixed, right?

**Comment by DeepDiver1975** [comment]
> @Deepdiver1975 @babelouest so this was fixed, right?

sounds so - mind quick testing?

**Comment by jancborchardt** [comment]
In the last imports this worked. I just wondered why the issue wasn’t autoclosed. :)
