### ISSUE TITLE
Address Book buttons for share,delete,etc hidden in Safari

### ISSUE THREAD

**Issue by atrias** [owncloud/contacts#908]
When using safari browser the buttons that would allow to share, delete, download, etc for Address Books are not displayed. On firefox it works fine.

Expected result in firefox:
![firefox](https://cloud.githubusercontent.com/assets/1192231/7788735/b0524a1a-0250-11e5-9269-4fd3c67af7c0.png)

Buttons missing in safari:
![safari](https://cloud.githubusercontent.com/assets/1192231/7788738/bc74ee2e-0250-11e5-93ea-18952d30d37a.png)

Safari ver. 8.0.6 (no extensions installed)
OSX 10.10

**Comment by RealRancor** [comment]
Hi,

looks to me like a duplicate of https://github.com/owncloud/contacts/issues/837

**Comment by jakobsack** [comment]
Closed because this is a duplicate of #837
