### ISSUE TITLE
Unable to enable

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/contacts#909]
Every time I try to enable Contacts v8 I get the warning `App directory already exists`.

But in the log I see

```
Fatal	remote	App not installed: contacts	2015-05-26T20:20:51+00:00
```

Weird. What should I do? Using owncloud v8.0.3 here, on Ubuntu 14.10

**Comment by RealRancor** [comment]
Hi,

why enable another issue as this was already reported here: https://github.com/owncloud/contacts/issues/892

**Comment by binarykitchen** [comment]
okay, will comment over there. closing ...

**Comment by RealRancor** [comment]
You already commented there, thats why i've asked the question above. :grinning:

**Comment by binarykitchen** [comment]
It is still happening

**Comment by RealRancor** [comment]
Please stick on the open issue, no need to post this also in here.

**Comment by binarykitchen** [comment]
Yeah, sorry, I realized that too late.
