### ISSUE TITLE
All contacts are sent to browser when opening contacts app

### ISSUE THREAD

**Issue by sybrenstuvel** [owncloud/contacts#923]
When I open the contacts app (https://my.cloud.url/index.php/apps/contacts/), all 577 contacts are sent to the browser. This takes a second to load over 100 Mbit LAN, and then 5 seconds to render on a reasonably fast Intel Core i7 PC / Firefox 38.0. This is acceptable, but becomes a real issue when I try to access my contacts via my mobile phone over mobile internet. Another thing is that I'm often trying to find a single contact, yet I have to wait for all of them to be loaded & displayed before I can start the search.

It would be nice if only a subset of the contacts would be sent, for example only the currently visible ones, and then allow me to use the search field to find whoever I'm looking for.

**Comment by RealRancor** [comment]
Hi,

seems this is an already known issue which got discussed here:

https://github.com/owncloud/contacts/pull/337
https://github.com/owncloud/contacts/issues/334
https://github.com/owncloud/contacts/issues/869
https://github.com/owncloud/contacts/issues/576

**Comment by sybrenstuvel** [comment]
@RealRancor thanks for linking those issues together. I do want to point out that "my issue" not only points out browser performance, but also used bandwidth (which is an issue on metered connections like many mobile internet subscriptions).

**Comment by RealRancor** [comment]
If some one takes over and implement a paging of the contacts list the bandwith problems are probably also gone.
