### ISSUE TITLE
import with this character >> $

### ISSUE THREAD

**Issue by superjey** [owncloud/contacts#925]
Hello. (sorry, I do not know if it's already posted..?... )
just for info:
I had a problem to import my Google contact ( with internal server error)
and I've realized it was from some chars.
with notepad I removed "$" and it worked.

voilà .

(ownCloud 8.1 alpha 2 )

**Comment by superjey** [comment]
the problem is the "home page" label in the info contact of google

**Comment by babelouest** [comment]
Hello @superjey ,

Can you be more specific ? I tried to reproduce your bug on both the master branch in contacts and my owncloud 8.0.4 instance, each time by importing a csv and a vcf file of the same contact that has a '$' and also a '#' in its website (just to be sure). I alwaays had the website imported successfully...

Can you specify your owncloud version, the webserver (type, version) it's hosted into, and post a sample anonymized import file that could help me reproduce the bug ?

**Comment by superjey** [comment]
hello.
--my config:

3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
debian 7.8
nginx/1.2.1
PHP Version 5.6.7-1
ownCloud 8.1 alpha 2 (git)

--my error log:
>>> http://pastebin.com/j9B1TLQP

--vCard exemple:
>> http://pastebin.com/J5tX9a7u

**Comment by babelouest** [comment]
Your error log is already known with another issue. There's a PR that should fix it: #906 , can you test it ?

I tried your sample file with it, and it seems fine to me.

**Comment by superjey** [comment]
i finally reinstall the stable version ( https://download.owncloud.org/community/owncloud-8.0.4.zip )
and all work perfectly

**Comment by babelouest** [comment]
that's not the answer I was expecting but ok...
If you want you can close this issue then.

**Comment by superjey** [comment]
sorry, but i'm not a dev ;-p
