### ISSUE TITLE
no share button etc. 

### ISSUE THREAD

**Issue by nextx42** [owncloud/contacts#928]
Hi,

i've installed owncloud on my QNAP NAS. Than i manually installed the contacts app. 

Now the problem is, that there is no share option available for my contacts. 

![bildschirmfoto 2015-06-22 um 22 29 30](https://cloud.githubusercontent.com/assets/6486375/8292310/51b8cb28-192f-11e5-960b-5cb336076bc4.png)

How can i fix this issue?

**Comment by RealRancor** [comment]
Hi,

looks to me like a dup of https://github.com/owncloud/contacts/issues/837 , https://github.com/owncloud/contacts/issues/908
