### ISSUE TITLE
OC 8.0.3 - contacts not enabling 

### ISSUE THREAD

**Issue by donrwilson** [owncloud/contacts#935]
I manually downloaded the contacts app per issue https://github.com/owncloud/core/issues/14033 and placed in the apps folder.

however, when attempting to endable it through Recommended apps, it provides:
App does not provide an info.xml file
even though i see this file in the appinfo subfolder.
i tried to copy this up one level and the issue remains.

this is on Fedora 20 64bit

**Comment by donrwilson** [comment]
### Steps to reproduce
1.  add apps button
2.  recommended
3.  click Enable button for Contacts 8.0 0.3.0.18

### Expected behaviour
App should enable

### Actual behaviour
App does not provide an info.xml file

### Server configuration
**Operating system**:
Fedora 20 x64

**Web server:**
Apache/2.4.10 (Fedora)

**Database:**
SQLite3

**PHP version:**
5.5.26

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0.3.4

**Updated from an older ownCloud or fresh install:**
yum updated on Sat 27 June

**List of activated apps:**
Activity 1.2.0
Deleted files 0.6.2
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.1
Text Editor 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**

<?php
$CONFIG = array (
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => NULL,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'log_type' => 'syslog',
  'datadirectory' => '/var/lib/owncloud/data',
  'updatechecker' => false,
  'check_for_working_htaccess' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/apps-appstore',
      'writable' => true,
    ),
  ),
  'instanceid' => 'ocb01277ca06',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'dwilson.pointto.us',
    2 => '10.10.1.27',
    3 => '74.123.104.117',
  ),
  'overwrite.cli.url' => 'http://dwilson.pointto.us/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.3.4',
  'installed' => true,
  'mail_smtpmode' => 'sendmail',
  'theme' => '',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
file storage is local


### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log

when attepting to Enable Contacts 8.0.0.3.0.18 the following is generated in the access_log:

[28/Jun/2015:08:59:25 -0500] "POST /owncloud/index.php/settings/ajax/enableapp.php HTTP/1.1" 200 77 "http://localhost/owncloud/index.php/settings/apps" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
74.123.104.117 - don [28/Jun/2015:08:59:33 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 513 "-" "Mozilla/5.0 (Linux) mirall/1.5.4"
74.123.104.117 - don [28/Jun/2015:08:59:38 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 2447 "-" "Mozilla/5.0 (Linux) mirall/1.5.4"

nothing is generated in any other webserver log file

#### ownCloud log (data/owncloud.log)

this file is empty

**Comment by RealRancor** [comment]
You need to enable it from the "not enabled" category. The "App does not provide an info.xml file" is an issue within core (or better within your system itself) where oC 8.1 will ship a workaround:

https://github.com/owncloud/core/issues/14840 (This and tons of other duplicates should be easy to find when searching in core)

**Comment by donrwilson** [comment]
Thank you RealRancor!
That fixed it.
And of course it is in the one place I did not think to look.

**Comment by donrwilson** [comment]
Closing as RealRancor's suggestion of using Not Enabled section rather than Recommended worked.
