### ISSUE TITLE
CSP issue on contacts images

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#936]
````
Refused to load the image 'data:image/png;base64,R0lGODlhIAAgAPcAAAwNG1x2fHSmrCQ+dGRAPpx1b1RaZLSon2yOl…hAJSbwBzI04gh7GAYLWTFBdwBCFvRQAg1HEQM+XGMJU5hAIxjAgEZ4sRFk+MMEpqCAgAAAOw==' because it violates the following Content Security Policy directive: "img-src 'self'".
x.expr.x.expr.filters.x.expr.filters.hidden @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:6x.expr.x.expr.filters.x.expr.filters.visible @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:6a @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4s @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4kt @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4at @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.fn.extend.find @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5ContactList.setSortOrder @ contacts.js?v=0bcf62d27b0c03d7d179937a88a84453:2494ContactList.showContacts @ contacts.js?v=0bcf62d27b0c03d7d179937a88a84453:2108(anonymous function) @ app.js?v=0bcf62d27b0c03d7d179937a88a84453:740x.event.dispatch @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5x.event.add.v.handle @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5x.event.trigger @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5e.event.trigger @ jquery-migrate.min.js?v=0bcf62d27b0c03d7d179937a88a84453:2(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5x.extend.each @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.fn.x.each @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.fn.extend.trigger @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:5GroupList.selectGroup @ groups.js?v=0bcf62d27b0c03d7d179937a88a84453:113(anonymous function) @ app.js?v=0bcf62d27b0c03d7d179937a88a84453:208(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.c @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.p.fireWith @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.c @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.p.fireWith @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.extend.Deferred.x.each.i.(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4(anonymous function) @ storage.js?v=0bcf62d27b0c03d7d179937a88a84453:308(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.c @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.p.fireWith @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.extend.Deferred.x.each.i.(anonymous function) @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4(anonymous function) @ storage.js?v=0bcf62d27b0c03d7d179937a88a84453:708x.Callbacks.c @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4x.Callbacks.p.fireWith @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:4k @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:6x.ajaxTransport.send.r @ jquery.min.js?v=0bcf62d27b0c03d7d179937a88a84453:6

**Comment by DeepDiver1975** [comment]
@LukasReschke any chance to add an exception here or shall we "simply" fix contacts to not use base64 encoded image source?

**Comment by DeepDiver1975** [comment]
evil location: https://github.com/owncloud/contacts/blob/master/js/contacts.js#L1628

**Comment by DeepDiver1975** [comment]
Solution to fix it:
instead of transmitting the base64 encoded blog we should transmit the photo id and set the image url

**Comment by LukasReschke** [comment]
Depends on how scary the code is. On my mobile at the moment. Let me check this tomorrow. Should be doable.

**Comment by LEDfan** [comment]
Branch fixes the issue :+1:

**Comment by jancborchardt** [comment]
Where is the PR / branch for this? @DeepDiver1975 :)

**Comment by LukasReschke** [comment]
![2015-06-30_20-38-01](https://cloud.githubusercontent.com/assets/878997/8438732/fd68d308-1f67-11e5-9ff0-8c2fe5634443.png)

**Comment by jancborchardt** [comment]
@lukasreschke

**Comment by jancborchardt** [comment]
@LukasReschke nice try, but look at the time difference between the commit and the PR reference. ;) n00b

**Comment by LukasReschke** [comment]
> > @LukasReschke nice try, but look at the time difference between the commit and the PR reference. ;)

> DeepDiver1975 referenced this issue from a commit 2 days ago 
> jancborchardt commented 17 hours ago

:speak_no_evil:

**Comment by LukasReschke** [comment]
Clicking on the commit will lead you to the PR :speak_no_evil:

**Comment by jancborchardt** [comment]
@lukasreschke there was no pr mon frère ;D

**Comment by LukasReschke** [comment]
Mon dieu! Baguette! Baguette!

**Comment by z000ao8q** [comment]
Hello,
This change seems to leave an issue with the caching because the thumbnails are transferred again and again

the base64 were cached.
the news files come with header:
Pragma	          no-cache
Cache-Control	  no-cache, must-revalidate

**Comment by jancborchardt** [comment]
@LukasReschke @DeepDiver1975 please check it out ^

**Comment by LukasReschke** [comment]
My solution would just have been to adjust the CSP to allow `data:`, something like in https://github.com/owncloud/bookmarks/pull/182 but for the image attribute. I can submit a PR tomorrow…

**Comment by LukasReschke** [comment]
Or we can keep it and adjust the caching headers. Whatever @DeepDiver1975 prefers.

**Comment by DeepDiver1975** [comment]
> Or we can keep it and adjust the caching headers. Whatever @DeepDiver1975 prefers.

to me this is like :apple: or :banana: ....

.... I don't care - this app is dead from my pov.

**Comment by sualko** [comment]
Can someone explain, why the csp is so restrictive compared to the file app? It prevents to display  avatars in my [chat app](www.jsxc.org).

**Comment by LukasReschke** [comment]
Because CSP is applied on a per app base with 8.1. Per default pretty much everything is blocked and apps can adjust this policy. - All legacy apps that do not use the app framework have a rather open policy  while apps using the appframework do have a rather strict one.

**Comment by LukasReschke** [comment]
Global CSP modifications are in evaluation for 8.2 though: https://github.com/owncloud/core/issues/16927

(though hijacking apps via app.php is not really something I'd recommend at the moment)

**Comment by sualko** [comment]
Thanks for that explanation.

**Comment by z000ao8q** [comment]
Hello,
anything which can be done here to get the app working?
I tried to undo the last commit 1cb89b0 from DeepDiver1975 to get back the original working base64.
but then I get a CSP error

I am still remaining with 8.05 only because of this :-(

...can this issue be reopened to have it on the radar?

**Comment by sualko** [comment]
A dirty hack would be to add <code>'data:'</code> to <a href="https://github.com/owncloud/core/blob/master/lib/public/appframework/http/contentsecuritypolicy.php#L64"><code>$allowedImageDomains</code></a> to allow base64 images. The clean way would be to modify the response in this app.

**Comment by gvde** [comment]
I don't know what way you plan to go. Do I have to expect to that OCP\Image will parse data: URIs at some point?
For what it's worth, I have created a pull request #1030 do to split off the base64 content from the URI so that the photo and the thumbnail are shown correctly in the web ui.
Thus, depending on the way it goes this PR may be necessary or not...

This goes in hand with commit 874bddb953394a4bdef74473f424cbc128e087f3 which prevents vcards to be downgraded from 4.0 to 3.0. Before the validate function downgraded but tried to decode and fix properties in a fashion which IMHO only applies to 2.1->3.0 upgrades. In the process it destroyed the data: URIs...

**Comment by z000ao8q** [comment]
Hello,
any news on this?
I tried the change from gvde but it does not change anything to the caching issue. Unfortunately I am not that deep into the topic yet. Also the suggestion from sualko does not work for me (or I don´t know where to put it correctly).

What I am a little surprised is about the comment that "contacts is dead".
What is the alternative? move away from owncloud to another solution?

I think contacts and calandar are very valuable and bring a lot of people to owncloud because they want an alternative to Apple & Google sync. This is why I am here since years.

how to go from here?
by the way: can the issue be re-opened?

**Comment by z000ao8q** [comment]
Bump
anything?
