### ISSUE TITLE
Setup proper milestones

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#938]
@jancborchardt 

Since we depend on sabredav in core it seems reasonable to sync up milestones.

Objections?

**Comment by jancborchardt** [comment]
Yeah, sounds good! Can we use a script for that, or just add Contacts to the list of apps using the core milestones? Or should we simply set up our own?

**Comment by DeepDiver1975** [comment]
@jancborchardt let's create them manually in here - and let's also review the current open ones.

**Comment by jancborchardt** [comment]
Ok, I added »8.1-current« and 8.2-next« and added some bugs to the current milestone. Let’s go through the existing milestones and issues together tomorrow.
