### ISSUE TITLE
[master/8.1] CardDAV problem: There was no handler found for this "GET" method

### ISSUE THREAD

**Issue by codeling** [owncloud/contacts#939]
### Steps to reproduce
1. Install nightly core from yesterday (or 8.1RC1 from  http://download.owncloud.org/community/testing/owncloud-8.1.0RC1.tar.bz2)
2. Install master of contacts app
3. Try to access CardDAV

### Expected behaviour
Access should work

### Actual behaviour
A 501 error occurs. When trying via browser, I see this:
```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.3</s:sabredav-version>
<s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
<s:message>There was no handler found for this "GET" method</s:message>
</d:error>
```

### Server configuration
**Operating system**:Ubuntu 14.04.2 LTS
**Web server:** Apache/2.4.12 (Ubuntu)
**Database:** 10.0.19-MariaDB
**PHP version:** PHP 5.5.25-1
**ownCloud version:** OC 8.1RC1

**Updated from an older ownCloud or fresh install:** Tried both, same result

**List of activated apps:** default apps + contacts
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '...',
  'trusted_domains' =>
  array (
    0 => 'mydomain',
  ),
  'datadirectory' => 'mydatadir',
  'overwrite.cli.url' => 'https://mydomain/octest/oc81rc1',
  'dbtype' => 'mysql',
  'version' => '8.1.0.7',
  'dbname' => 'octest81rc1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_test',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

### Client configuration
**Browser:** Chrome/Firefox Windows/Linux

#### Web server error log
nothing related

#### ownCloud log (data/owncloud.log)
```
{"reqId":"ENiDv9lCJSnwVpWdl5sS","remoteAddr":"localip","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/octest\/oc81rc1\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-06-29T21:53:11+00:00"}
{"reqId":"ENiDv9lCJSnwVpWdl5sS","remoteAddr":"localip","app":"PHP","message":"touch(): Unable to create file \/var\/www\/octest\/oc81rc1\/data\/owncloud.log because No such file or directory at \/var\/www\/octest\/oc81rc1\/lib\/private\/log\/owncloud.php#60","level":3,"time":"2015-06-29T21:53:11+00:00"}
{"reqId":"TS0Os3Lxqr3Jrx6S1b+0","remoteAddr":"localip","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/octest\/oc81rc1\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-06-29T21:53:50+00:00"}
{"reqId":"CNF8TEj1MW7tbWvdopkC","remoteAddr":"localip","app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Contact not registered, OCA\\Contacts\\Share\\Contact is already registered for contact","level":2,"time":"2015-06-29T21:57:04+00:00"}
{"reqId":"CNF8TEj1MW7tbWvdopkC","remoteAddr":"localip","app":"OCP\\Share","message":"Sharing backend OCA\\Contacts\\Share\\Addressbook not registered, OCA\\Contacts\\Share\\Addressbook is already registered for addressbook","level":2,"time":"2015-06-29T21:57:04+00:00"}
{"reqId":"dgnHQOT67e+pBi7tuPX8","remoteAddr":"localip","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"GET\\\" method\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/octest\\\/oc81rc1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/octest\\\/oc81rc1\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/octest\\\/oc81rc1\\\/remote.php(84): require_once('\\\/var\\\/www...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/octest\\\/oc81rc1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2015-06-29T21:57:50+00:00"}
```

**Comment by DeepDiver1975** [comment]
There seems to be a misunderstanding - the CardDAV url cannot be used in a browser but requires a CardDAV client.

**Comment by codeling** [comment]
I thought this was a legitimate way of testing CardDAV because it used to work in previous versions.
I was using it as part of a simple script to retrieve all email addresses. I now realize this is not part of the standard, I'll use a "proper" CardDAV client instead.
Sorry for the noise!

**Comment by DeepDiver1975** [comment]
No worries!  Thanks for testing!  Let me know if other issues pop up.

**Comment by RealRancor** [comment]
@codeling 
The SabreDAV browser at the *DAV urls was removed in OC 8.1:

https://github.com/owncloud/core/wiki/ownCloud-8.1-Features#security
https://github.com/owncloud/core/issues/16359

**Comment by StephanRichter** [comment]
Actually, when performing an "OPTIONS" request against owncloud/sabredav, it returns "GET" as a possible request method. Either "GET" should be removed from the options, or it should remain available.

I know this is an issue with sabreDAV, but unfortunately, i'm not sure, where to report this.

**Comment by Happyfeet01** [comment]
I have this issue also. 
I have create an Calendar with the name "Persönlich". The CALDAV URL showing /remote.php/caldav/calendars/Lars/pers%C3%B6nlich

When I open the Caldav URL at the Browser, I get this info "There was no handler found for this "GET" method"

And the ownCloud log says: 


Sicherheits- & Einrichtungswarnungen

All checks passed.
Teilen 
Anwendungen erlauben, die Share-API zu benutzen
Benutzern erlauben, Inhalte über Links zu teilen
Passwortschutz erzwingen
Öffentliches Hochladen erlauben
Benutzern erlauben, E-Mail-Benachrichtigungen für freigegebene Dateien zu senden
Standardablaufdatum einstellen
Weiterverteilen erlauben
Benutzer auf das Teilen innerhalb ihrer Gruppen beschränken
Benutzern erlauben, E-Mail-Benachrichtigungen für freigegebene Dateien an andere Benutzer zu senden
Gruppen von Freigaben ausschließen
Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.
Federated-Cloud-Sharing 
 Benutzern auf diesem Server das Senden von Freigaben an andere Server erlauben
 Benutzern auf diesem Server das Empfangen von Freigaben von anderen Servern erlauben	
Externer Speicher

Ordnername	Externer Speicher	Authentication	Konfiguration	Verfügbar für	 	 
 
Lokal
Lokal		
/mnt/usb/downloads
Lars

 
Ordnername
 			

Externen Speicher für Benutzer aktivieren
Erlauben Sie Benutzern, folgende externe Speicher einzubinden
FTP 
WebDAV 
ownCloud 
SFTP 
Amazon S3 
Dropbox 
Google Drive 
Openstack-Objektspeicher 
SMB / CIFS 
Dateibehandlung

Maximale Upload-Größe 
1 GB
 (maximal möglich:2 GB) 
With PHP-FPM this value may take up to 5 minutes to take effect after saving.	
Speichern
Kontakte

 LDAP-Backend aktivieren
LDAP-Backend für die Kontakte-Anwendungen aktivieren 
Warnung: LDAP-Backend ist im Beta-Modus, mit Vorsichtsmaßnahmen verwenden
Dokumente

MS Word Unterstützung (benötigt OpenOffice/LibreOffice)
 Lokal
OpenOffice/LibreOffice ist auf diesem Server installiert. Der Pfad zur Binärdatei wird über preview_libreoffice_path in der config.php bereit gestellt.
 Extern
OpenOffice/LibreOffice ist auf einem externen Server installiert und läuft dort als Formatfilter-Server
 Deaktiviert
Keine MS Word Unterstützung

Übernehmen und Testen
News

 ownCloud-Cron für Aktualisierungen nutzen
Deaktivieren Sie dies, wenn Sie einen eigenen Updater sowie den Python-Updater aus der App laufen lassen
Säuberungssintervall
Minimum an Sekunden, nachdem gelöschte Feeds und Ordner aus der Datenbank entfernt werden; Werte unter 60 Sekunden werden ignoriert

60
Maximale Anzahl an einzulesende Feeds
Definiert die maximale Anzahl an Artikeln, die pro Feed gelesen und bei einem Säuberungsauftrag nicht aus der Datenbank gelöscht werden; wenn ältere Artikel nach dem Lesen erhalten bleiben sollen, erhöhen Sie diesen Wert; negative Werte sowie -1 deaktiviert diese Funktion komplett

200
Maximale Anzahl Weiterleitungen
Anzahl Weiterleitungen die der Feed-Sammler folgen soll

10
Maximale Seitengröße des Feeds
Maximale Feedgröße in Bytes. Wenn die RSS/Atom-Seite größer als dieser Wert ist, wird die Aktualisierung abgebrochen

104857600
Zeitüberschreitung Feed-Sammler
Maximale Anzahl Sekunden zum Laden eines RSS- oder Atom-Feeds; wenn dies länger dauert, wird die Aktualisierung abgebrochen.

60
Service-URL entdecken
Falls angegeben, wird die URL dieses Dienstes zur Feed-Anzeige innerhalb des Explore-Feed-Bereichs abgefragt. Lassen Sie dieses Feld unausgefüllt, um auf den eingebauten Explore-Dienst zurückzugreifen.

ocDownloader

Leave fields blank to reset a setting value
YouTube DL Binary Path 
/usr/local/bin/youtube-dl
Proxy settings
Proxy Address 
http://
Proxy Port  
8080
If no authentication is required by your proxy, leave the following fields blank
Proxy User  
Username
 Proxy Password  
Password
Only use proxy settings with YouTube-DL ? 
General settings
Check for updates ?  
WARNING !! Switching from ARIA2 to another downloader engine will remove all current downloads from ARIA2
Which downloader do you want to use ?  Available protocols: HTTP(S) / FTP(S) / YouTube
Max download speed ?  
10000
KB/s (empty or 0 : unlimited, default : unlimited)
Allow protocols for users (except for members of the admin group)
Allow HTTP ?  
Allow FTP ?  
Allow YouTube ?  
Allow BitTorrent ? No
OwnBackup

Deine Backups

 Create Backup
Shorten

Which type of URL shortener to use:


Your goo.gl API key. To get an API key, follow these instructions.

Mail-Vorlagen

Theme

Vorlage

Cron  Letzte Cron-Job-Ausführung: Gerade eben.  
 AJAX
Eine Aufgabe bei jedem Laden der Seite ausführen
 Webcron
cron.php ist als Webcron-Dienst registriert, der die cron.php alle 15 Minuten per HTTP aufruft.
 Cron
Benutzen Sie den systemeigenen Cron-Dienst, um die cron.php alle 15 Minuten aufzurufen.
Serverseitige Verschlüsselung 
Serverseitige Verschlüsselung aktivieren 
Standard-Verschlüsselungs-Modul auswählen:

 Default encryption module 
Wiederherstellungsschlüssel deaktivieren	
Der Wiederherstellungsschlüssel ist ein zusätzlicher Verschlüsselungsschlüssel, der zum Verschlüsseln von Dateien benutzt wird. Er erlaubt die Wiederherstellung von Benutzerdateien auch dann, wenn der Benutzer sein Passwort vergessen hat.	

Wiederherstellungschlüsselpasswort
 
Passwort für den Wiederherstellungsschlüssel wiederholen
 Wiederherstellungsschlüssel deaktivieren


Wiederherstellungsschlüsselpasswort ändern	

Altes Passwort für den Wiederherstellungsschlüssel


Neues Passwort für den Wiederherstellungsschlüssel
 
Neues Passwort für den Wiederherstellungsschlüssel wiederholen
 Passwort ändern
E-Mail-Server 
Dies wird für das Senden von Benachrichtigungen verwendet.
Sendemodus  Verschlüsselung 
Absenderadresse 
cloud-email
@ 
smartdroidblog.de
Authentifizierungsmethode   Authentifizierung benötigt
Serveradresse 
smtp.strato.de
 :  
Port
Zugangsdaten 
Cloud-email@smartdroidblog.de
 
••••••••••••
 Anmeldeinformationen speichern

E-Mail-Einstellungen testen  E-Mail senden
Log

Log-Level 
Fatal	caldav	Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"GET\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":472}

**Comment by Happyfeet01** [comment]
I have the same issue. I create an Calendar with the name: "Persönlich". 
With this URL:
https://Domain.tld/remote.php/caldav/calendars/Lars/pers%C3%B6nlich

When I open this URL in an Browser, I have this message. 

"There was no handler found for this "GET" method" 

The ownCloud Log says this error:

Fatal	caldav	Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"GET\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":472}


I can't Sync this Calendar with my android device, or other clients. What can I do?

**Comment by RealRancor** [comment]
@Happyfeet01 There is no issue here. The message about GET is the expected behavior there.

Please ask for support at the forums.
