### ISSUE TITLE
 You can not set the date in the field. The pop-up window is hidden.

### ISSUE THREAD

**Issue by thfree** [owncloud/contacts#950]
You can not set the date in the field. The pop-up window is hidden.
![untitled](https://cloud.githubusercontent.com/assets/13134495/8454033/db694d0a-2002-11e5-8b0d-fe0b856f0287.png)
Versions:
   owncloud-8.1.0RC2
   contacts-8.1.0RC2

**Comment by MorrisJobke** [comment]
Not fixed by the mentioned issue

**Comment by thfree** [comment]
Not fixed? I can offer to look.
https://test.thfree.ru/
test / test

**Comment by schiesbn** [comment]
@thfree for me the issue wasn't fixed with the PR above... Would be great if you could also have a look at it.

**Comment by libasys** [comment]
the datepicker div has only a z-index of 2, so i think you have a greater z-index for it!

**Comment by jancborchardt** [comment]
@libasys do you mind submitting a pull request for this to fix it? :)

**Comment by thfree** [comment]
contacts-0.4.0.0
Now, everything works fine.

**Comment by jancborchardt** [comment]
@thfree thank you for testing and confirming the fix! :) You are welcome to join our IRC channel #owncloud-contacts as well.
