### ISSUE TITLE
Not displayed thumbnail photo in the list. In the detailed version okay.

### ISSUE THREAD

**Issue by thfree** [owncloud/contacts#953]
Not displayed thumbnail photo in the list. In the detailed version okay.
![untitled](https://cloud.githubusercontent.com/assets/13134495/8457000/a890349c-2017-11e5-8464-85bfae25bc3f.png)
Versions:
owncloud-8.1.0RC2
contacts-8.1.0RC2

**Comment by MeCias** [comment]
Can confirm this for the 8.1 as well, a few of the contacts have no thumbnail at all like mentioned above and the rest have the standard colored thumbnails. The photo thumbnails disappeared out of the overview list completely.

**Comment by thfree** [comment]
ownCloud 8.1.0 (daily)
Build:2015-07-02T22:33:50+00:00 06ec916b1128b9a1ec79751bdd78cc4a8c64ace8 
contacts 8.1.0

The situation has not changed

**Comment by MeCias** [comment]
Seems to be fixed with version 4.0.0
Thanks

**Comment by thfree** [comment]
contacts-0.4.0.0
Thank you Now everything is fine.
