### ISSUE TITLE
8.1rc2 No possibility to choose a date that is newer than the actual month/day

### ISSUE THREAD

**Issue by libasys** [owncloud/contacts#962]
TestEnviro:
8.1rc2

Step to reproduce:
1. create new contact
2. add field birthday
3. open datepicker

Expected result
you can choose a date

Actual result 
you can't choose a date that is newer than the actual month/ day

**Comment by DeepDiver1975** [comment]
Does it make sense to set a birthday in the future? One never knows exactly the arrival of child! :speak_no_evil:

**Comment by jancborchardt** [comment]
True story. :D
